import { Link } from 'react-router-dom'
export default function BeneficiariesPhcAdmin1() {
  return (
    <>
<nav className="hidden md:flex flex-col h-screen fixed left-0 top-0 p-md gap-sm bg-surface-container-low dark:bg-inverse-surface border-r border-outline-variant w-64 z-40">
<div className="flex items-center gap-sm mb-md px-sm"><span className="material-symbols-outlined text-[32px] text-primary" style={{ fontVariationSettings: '\'FILL\' 1' }}>local_hospital</span><div className="flex flex-col"><span className="font-headline-md text-headline-md font-black text-primary">Admin Portal</span><span className="font-caption text-caption text-on-surface-variant">District Health Office</span></div></div>
<button className="bg-primary-container text-on-primary-container font-label-md text-label-md py-sm px-md rounded-full flex justify-center items-center gap-xs hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all mb-md shadow-sm"><span className="material-symbols-outlined text-[18px]">add</span>
            Add New Worker
        </button>
<div className="flex-1 flex flex-col gap-xs overflow-y-auto">
<Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all font-label-md text-label-md" to="/phc/dashboard"><span className="material-symbols-outlined">dashboard</span>
                Dashboard
            </Link>
<Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all font-label-md text-label-md" to="/phc/ashas"><span className="material-symbols-outlined">groups</span>
                Workers
            </Link>
<Link className="flex items-center gap-md px-md py-sm bg-secondary-container dark:bg-secondary text-on-secondary-container dark:text-on-secondary font-bold rounded-lg transition-transform duration-150 font-label-md text-label-md" to="/phc/beneficiaries"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>person_celebrate</span>
                Beneficiaries
            </Link>
<Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all font-label-md text-label-md" to="/phc/reports/maternal"><span className="material-symbols-outlined">analytics</span>
                Reports
            </Link>
<Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all font-label-md text-label-md" to="/phc/vaccination"><span className="material-symbols-outlined">inventory_2</span>
                Inventory
            </Link></div>
<div className="flex flex-col gap-xs mt-auto pt-md border-t border-outline-variant">
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all font-label-md text-label-md" href="#"><span className="material-symbols-outlined">settings</span>
                Settings
            </a>
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all font-label-md text-label-md" href="#"><span className="material-symbols-outlined">help</span>
                Support
            </a></div></nav>
<header className="md:hidden fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target bg-surface dark:bg-on-background border-b border-outline-variant dark:border-outline shadow-sm"><div className="flex items-center gap-sm"><span className="material-symbols-outlined text-primary text-[24px]">local_hospital</span><span className="text-headline-md font-headline-md font-bold text-primary dark:text-primary-fixed-dim tracking-tight">ASHA Sathi</span></div><div className="flex items-center gap-md text-primary dark:text-primary-fixed-dim"><button className="hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors rounded-full p-xs"><span className="material-symbols-outlined">sync</span></button><button className="hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors rounded-full p-xs"><span className="material-symbols-outlined">notifications</span></button><img alt="User Profile" className="w-8 h-8 rounded-full object-cover border border-outline-variant" data-alt="A small circular profile avatar showing a professional Indian healthcare administrator in a clean white office setting. The lighting is soft and neutral, conveying competence and calm. Corporate modern style." src="https://lh3.googleusercontent.com/aida-public/AB6AXuDNR-uIuqOCBMy3VuDNkMh3-0LVwmyUvkZ5zfmd9bestmpsgcgIwzzpiHsihmfzaPhFbOxJpHd8ZjugcfBL57aJYtE2o49gB3iY2rj2TX5r0loMlDhlW-S76zldgyr8hvJq-8NBIm5pLi-MlHC_UnF4EJlZV2UQhJGR27DelasPy744QvpFBdH3zKEJ6nZgMZsQHWNhDgZSGrCRgQmczzZOPNbD2tCJfbsPOn4qj8tCWjgTlnlHkWzXgw" /></div></header>
<main className="flex-1 md:ml-64 pt-[64px] md:pt-0 min-h-screen bg-surface"><div className="max-w-[1440px] mx-auto p-md md:p-lg space-y-lg">
<div className="flex flex-col lg:flex-row lg:items-center justify-between gap-md"><div><h1 className="font-display-lg text-display-lg text-on-background">Beneficiaries</h1><p className="font-body-md text-body-md text-on-surface-variant mt-xs">Manage and monitor patient records across all villages.</p></div><div className="flex flex-col sm:flex-row gap-sm w-full lg:w-auto">
<div className="relative flex-1 sm:w-64"><span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline">search</span><input className="w-full h-12 pl-10 pr-4 rounded-lg bg-surface-container border border-outline-variant focus:border-primary focus:ring-1 focus:ring-primary font-body-md text-body-md text-on-background placeholder:text-on-surface-variant/70 outline-none transition-colors" placeholder="Search by ID or Name..." type="text" /></div><button className="h-12 bg-primary text-on-primary px-lg rounded-lg font-label-md text-label-md font-bold flex items-center justify-center gap-xs hover:bg-primary/90 transition-colors shadow-sm whitespace-nowrap"><span className="material-symbols-outlined text-[20px]">add</span>
                        Add Patient
                    </button></div></div>
<div className="grid grid-cols-2 lg:grid-cols-4 gap-md md:gap-lg">
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group"><div className="absolute top-0 right-0 p-sm opacity-10 group-hover:opacity-20 transition-opacity"><span className="material-symbols-outlined text-[64px] text-primary">groups</span></div><div className="flex flex-col relative z-10"><span className="font-caption text-caption text-on-surface-variant uppercase tracking-wider font-semibold mb-xs">Total Beneficiaries</span><span className="font-display-lg text-display-lg text-primary">4,285</span><div className="flex items-center gap-xs mt-xs text-secondary"><span className="material-symbols-outlined text-[16px]">trending_up</span><span className="font-caption text-caption">+12 this week</span></div></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group"><div className="absolute top-0 right-0 p-sm opacity-10 group-hover:opacity-20 transition-opacity"><span className="material-symbols-outlined text-[64px] text-tertiary">pregnant_woman</span></div><div className="flex flex-col relative z-10"><span className="font-caption text-caption text-on-surface-variant uppercase tracking-wider font-semibold mb-xs">Pregnant Women</span><span className="font-display-lg text-display-lg text-tertiary">342</span><div className="flex items-center gap-xs mt-xs text-secondary"><span className="material-symbols-outlined text-[16px]">check_circle</span><span className="font-caption text-caption">85% ANC covered</span></div></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group"><div className="absolute top-0 right-0 p-sm opacity-10 group-hover:opacity-20 transition-opacity"><span className="material-symbols-outlined text-[64px] text-secondary">child_care</span></div><div className="flex flex-col relative z-10"><span className="font-caption text-caption text-on-surface-variant uppercase tracking-wider font-semibold mb-xs">Infants (0-5)</span><span className="font-display-lg text-display-lg text-secondary">890</span><div className="flex items-center gap-xs mt-xs text-on-surface-variant"><span className="material-symbols-outlined text-[16px]">info</span><span className="font-caption text-caption">Active monitoring</span></div></div></div>
<div className="bg-error-container border border-error/20 rounded-xl p-md shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group"><div className="absolute top-0 right-0 p-sm opacity-10 group-hover:opacity-20 transition-opacity"><span className="material-symbols-outlined text-[64px] text-error">warning</span></div><div className="flex flex-col relative z-10"><span className="font-caption text-caption text-on-error-container uppercase tracking-wider font-semibold mb-xs">Overdue Vaccinations</span><span className="font-display-lg text-display-lg text-error">45</span><div className="flex items-center gap-xs mt-xs text-error"><span className="material-symbols-outlined text-[16px]">error</span><span className="font-caption text-caption">Requires immediate action</span></div></div></div></div>
<div className="bg-surface-container border border-outline-variant rounded-xl p-md shadow-sm"><div className="flex flex-col lg:flex-row gap-md items-start lg:items-center justify-between"><div className="flex items-center gap-xs text-on-surface-variant"><span className="material-symbols-outlined">filter_list</span><span className="font-label-md text-label-md font-bold">Filters:</span></div><div className="flex flex-wrap gap-sm flex-1">
<div className="relative min-w-[150px]"><select className="w-full h-10 pl-3 pr-8 rounded-lg bg-surface-container-lowest border border-outline-variant focus:border-primary focus:ring-1 focus:ring-primary font-caption text-caption text-on-background appearance-none outline-none"><option value="">All Villages</option><option value="rampur">Rampur</option><option value="sitapur">Sitapur</option><option value="laxmanpur">Laxmanpur</option></select><span className="material-symbols-outlined absolute right-2 top-1/2 -translate-y-1/2 text-outline pointer-events-none text-[20px]">arrow_drop_down</span></div>
<div className="relative min-w-[150px]"><select className="w-full h-10 pl-3 pr-8 rounded-lg bg-surface-container-lowest border border-outline-variant focus:border-primary focus:ring-1 focus:ring-primary font-caption text-caption text-on-background appearance-none outline-none"><option value="">All Risk Levels</option><option value="high">High Risk (Red)</option><option value="medium">Medium Risk (Orange)</option><option value="low">Low Risk (Green)</option></select><span className="material-symbols-outlined absolute right-2 top-1/2 -translate-y-1/2 text-outline pointer-events-none text-[20px]">arrow_drop_down</span></div>
<div className="relative min-w-[150px]"><select className="w-full h-10 pl-3 pr-8 rounded-lg bg-surface-container-lowest border border-outline-variant focus:border-primary focus:ring-1 focus:ring-primary font-caption text-caption text-on-background appearance-none outline-none"><option value="">Vaccination Status</option><option value="up_to_date">Up to Date</option><option value="overdue">Overdue</option></select><span className="material-symbols-outlined absolute right-2 top-1/2 -translate-y-1/2 text-outline pointer-events-none text-[20px]">arrow_drop_down</span></div></div><button className="text-primary font-label-md text-label-md hover:underline whitespace-nowrap">Clear Filters</button></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="bg-surface-container-high border-b border-outline-variant"><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant font-bold">Patient Name / ID</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant font-bold">Age & Gender</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant font-bold">Village</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant font-bold">Assigned ASHA</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant font-bold">Risk Level</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant font-bold">Last Visit</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant font-bold text-right">Actions</th></tr></thead><tbody className="divide-y divide-outline-variant">
<tr className="hover:bg-surface-container-low transition-colors h-10 relative"><td className="py-3 px-4"><div className="flex items-center gap-sm">
<div className="w-1 h-8 bg-error rounded-full absolute left-1"></div><div><div className="font-label-md text-label-md font-bold text-on-background">Aarti Devi</div><div className="font-caption text-caption text-on-surface-variant">ID: BEN-9021</div></div></div></td><td className="py-3 px-4 font-body-md text-body-md text-on-background">28y, Female</td><td className="py-3 px-4 font-body-md text-body-md text-on-background">Rampur</td><td className="py-3 px-4"><div className="flex items-center gap-xs"><img alt="ASHA Avatar" className="w-6 h-6 rounded-full object-cover" data-alt="A small circular avatar of a female Indian ASHA worker wearing a traditional pink sari, smiling softly. Professional healthcare context. Light background." src="https://lh3.googleusercontent.com/aida-public/AB6AXuC-kTMBuMRSqEzg1jk3RGPXmWr_oItgcphZnTbLynGAaD6C3EBhZBFpbZ-kgKhKh81cqdlNT04MQYIBJzD2ArWWlxTiK6ZZY9L1ZzPxOs8eRM0YqgICnT1S3MnWQEDqmtYLqAQvDxanu5ABStG_5S5NYpiQ5FTN-lDo2VXBf32eXHaIkRHNNqeGmCiLx6WgosxgmTBlFIQZtUGlredl82aA3SDnmEr6Z3_UBuWkXRQS_mQur0p9B-Rk0g" /><span className="font-body-md text-body-md text-on-background">Sunita Sharma</span></div></td><td className="py-3 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-error-container text-on-error-container font-caption text-caption font-bold border border-error/20">
                                        High
                                    </span></td><td className="py-3 px-4 font-body-md text-body-md text-on-background">12 Oct 2023</td><td className="py-3 px-4 text-right"><button className="text-primary hover:bg-primary-container hover:text-on-primary-container p-xs rounded-full transition-colors"><span className="material-symbols-outlined text-[20px]">more_vert</span></button></td></tr>
<tr className="hover:bg-surface-container-low transition-colors h-10 bg-surface-container-lowest relative"><td className="py-3 px-4"><div className="flex items-center gap-sm"><div className="w-1 h-8 bg-[#FF8C00] rounded-full absolute left-1"></div><div><div className="font-label-md text-label-md font-bold text-on-background">Raju Kumar</div><div className="font-caption text-caption text-on-surface-variant">ID: BEN-8842</div></div></div></td><td className="py-3 px-4 font-body-md text-body-md text-on-background">2y, Male</td><td className="py-3 px-4 font-body-md text-body-md text-on-background">Sitapur</td><td className="py-3 px-4"><div className="flex items-center gap-xs"><img alt="ASHA Avatar" className="w-6 h-6 rounded-full object-cover" data-alt="A small circular avatar of a female Indian ASHA worker wearing a traditional pink sari, looking attentive. Professional healthcare context. Light background." src="https://lh3.googleusercontent.com/aida-public/AB6AXuAmPoeMryn7dJBL2ITKYQU9k7jw-ZWW-bshXejh6W7c9TtlNRWeKqrjtWkH5BcuvXvhQk_2cQNWdOzMUa5F1o2s9iAdIkvJzBdOBaji4ckGkCFQQPTQ1Gc69etjiadZcnB0mWcTXDrLqXjPIOIfo4hEmFMuj1ZFR5knPq1adkppOEwwAKAEm_4VsqXNnrnC1KL-BgXVcvPVrtPNUxjllB0MOFyVhLP62cUMXUyngPv5L_X2zKTA4ctgjg" /><span className="font-body-md text-body-md text-on-background">Meena Patel</span></div></td><td className="py-3 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-[#FFF3E0] text-[#E65100] font-caption text-caption font-bold border border-[#FFCC80]">
                                        Medium
                                    </span></td><td className="py-3 px-4 font-body-md text-body-md text-on-background">10 Oct 2023</td><td className="py-3 px-4 text-right"><button className="text-primary hover:bg-primary-container hover:text-on-primary-container p-xs rounded-full transition-colors"><span className="material-symbols-outlined text-[20px]">more_vert</span></button></td></tr>
<tr className="hover:bg-surface-container-low transition-colors h-10 relative"><td className="py-3 px-4"><div className="flex items-center gap-sm"><div className="w-1 h-8 bg-secondary rounded-full absolute left-1"></div><div><div className="font-label-md text-label-md font-bold text-on-background">Geeta Verma</div><div className="font-caption text-caption text-on-surface-variant">ID: BEN-7710</div></div></div></td><td className="py-3 px-4 font-body-md text-body-md text-on-background">45y, Female</td><td className="py-3 px-4 font-body-md text-body-md text-on-background">Laxmanpur</td><td className="py-3 px-4"><div className="flex items-center gap-xs"><div className="w-6 h-6 rounded-full bg-primary-container text-on-primary-container flex items-center justify-center font-caption text-caption font-bold">
                                            S
                                        </div><span className="font-body-md text-body-md text-on-background">Sunita Sharma</span></div></td><td className="py-3 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-secondary-container text-on-secondary-container font-caption text-caption font-bold border border-secondary/20">
                                        Low
                                    </span></td><td className="py-3 px-4 font-body-md text-body-md text-on-background">05 Oct 2023</td><td className="py-3 px-4 text-right"><button className="text-primary hover:bg-primary-container hover:text-on-primary-container p-xs rounded-full transition-colors"><span className="material-symbols-outlined text-[20px]">more_vert</span></button></td></tr>
<tr className="hover:bg-surface-container-low transition-colors h-10 bg-surface-container-lowest relative"><td className="py-3 px-4"><div className="flex items-center gap-sm"><div className="w-1 h-8 bg-secondary rounded-full absolute left-1"></div><div><div className="font-label-md text-label-md font-bold text-on-background">Ramesh Singh</div><div className="font-caption text-caption text-on-surface-variant">ID: BEN-6599</div></div></div></td><td className="py-3 px-4 font-body-md text-body-md text-on-background">62y, Male</td><td className="py-3 px-4 font-body-md text-body-md text-on-background">Rampur</td><td className="py-3 px-4"><div className="flex items-center gap-xs"><img alt="ASHA Avatar" className="w-6 h-6 rounded-full object-cover" data-alt="A small circular avatar of a female Indian ASHA worker wearing a traditional pink sari. Professional healthcare context. Light background." src="https://lh3.googleusercontent.com/aida-public/AB6AXuB10NI7UGh7S6QV4KyKcm7kracyglPrnvJ_sizbL84fcY9_W2YLQq5_KamXMxN0JaCeF3fAsaDtFWqebcpP2Vu1JKUjfvEXiXELA_qntoSPIqTFvavRzpTygn8R0EQF01k_luo3HO28SRFpd8UEg_ng46exatmkfMW9e4E5xpNvIVBu9gpTsZIjwk2MFr8NCA8zIGkMEJD5uikKfkZw_cDqFyh3M0e_nT3jcdPmHWA8KpdPRo9yF9nEvA" /><span className="font-body-md text-body-md text-on-background">Anita Das</span></div></td><td className="py-3 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-secondary-container text-on-secondary-container font-caption text-caption font-bold border border-secondary/20">
                                        Low
                                    </span></td><td className="py-3 px-4 font-body-md text-body-md text-on-background">01 Oct 2023</td><td className="py-3 px-4 text-right"><button className="text-primary hover:bg-primary-container hover:text-on-primary-container p-xs rounded-full transition-colors"><span className="material-symbols-outlined text-[20px]">more_vert</span></button></td></tr></tbody></table></div>
<div className="flex items-center justify-between px-md py-sm border-t border-outline-variant bg-surface-container-lowest"><span className="font-caption text-caption text-on-surface-variant">Showing 1 to 4 of 4,285</span><div className="flex gap-xs"><button className="p-xs rounded border border-outline-variant text-on-surface-variant hover:bg-surface-container transition-colors disabled:opacity-50" disabled><span className="material-symbols-outlined text-[20px]">chevron_left</span></button><button className="px-sm py-xs rounded bg-primary text-on-primary font-caption text-caption">1</button><button className="px-sm py-xs rounded hover:bg-surface-container text-on-surface-variant font-caption text-caption transition-colors">2</button><button className="px-sm py-xs rounded hover:bg-surface-container text-on-surface-variant font-caption text-caption transition-colors">3</button><span className="px-sm py-xs text-on-surface-variant">...</span><button className="p-xs rounded border border-outline-variant text-on-surface-variant hover:bg-surface-container transition-colors"><span className="material-symbols-outlined text-[20px]">chevron_right</span></button></div></div></div></div></main>
<nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-sm py-xs bg-surface dark:bg-on-background border-t border-outline-variant shadow-lg rounded-t-full pb-safe"><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant px-2 py-1 rounded-lg" to="/phc/dashboard"><span className="material-symbols-outlined">home</span><span className="font-label-md text-[10px] leading-[12px] mt-1">Home</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant px-2 py-1 rounded-lg" to="/phc/households"><span className="material-symbols-outlined">cottage</span><span className="font-label-md text-[10px] leading-[12px] mt-1">Households</span></Link><Link className="flex flex-col items-center justify-center bg-primary-container dark:bg-primary text-on-primary-container dark:text-on-primary rounded-full px-4 py-1 scale-90 transition-transform duration-200" to="/phc/beneficiaries"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>person_search</span><span className="font-label-md text-[10px] leading-[12px] mt-1 font-bold">Patients</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant px-2 py-1 rounded-lg" to="/phc/alerts"><span className="material-symbols-outlined">assignment_turned_in</span><span className="font-label-md text-[10px] leading-[12px] mt-1">Tasks</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant px-2 py-1 rounded-lg" to="/phc/dashboard"><span className="material-symbols-outlined">account_circle</span><span className="font-label-md text-[10px] leading-[12px] mt-1">Profile</span></Link></nav>
    </>
  )
}
