import { Link } from 'react-router-dom'
export default function ChildVaccinationSchedulePhcAdmin() {
  return (
    <>
<header className="fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target md:px-lg bg-surface dark:bg-on-background border-b border-outline-variant dark:border-outline shadow-sm md:hidden md:flex"><div className="flex items-center gap-sm"><button aria-label="Open Menu" className="md:hidden p-xs rounded-full hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors flex items-center justify-center text-primary dark:text-primary-fixed-dim"><span className="material-symbols-outlined">menu</span></button><span className="text-headline-md font-headline-md font-bold text-primary dark:text-primary-fixed-dim">ASHA Sathi</span></div><div className="flex items-center gap-md"><button aria-label="Sync" className="p-xs rounded-full hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors flex items-center justify-center text-primary dark:text-primary-fixed-dim"><span className="material-symbols-outlined" data-icon="sync">sync</span></button><button aria-label="Notifications" className="p-xs rounded-full hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors flex items-center justify-center text-primary dark:text-primary-fixed-dim"><span className="material-symbols-outlined" data-icon="notifications">notifications</span></button><img alt="User Profile" className="w-8 h-8 rounded-full border border-outline-variant object-cover" data-alt="A small, circular profile picture of an ASHA worker in professional attire, set against a clean, light blue background. The image should be highly detailed, showing a warm, professional expression, fitting the modern healthcare aesthetic of the application." src="https://lh3.googleusercontent.com/aida-public/AB6AXuBPfsqcAYXHvW-U1zG60TCpeVtqgppFHEON4nhYRJqfNDksOvML_RbPBdkYW8wB8PhH35CH_s40bZUjoao2P5wxCku_CiZU3OqbCCicTPMKJTgQUYdqNxPS7LFldr_2f_63TfOmPOydQwJRoxTtqb36QuAEJXvO4rcZknD4Pz_VUpSRLSvB4lWnMG1SxVGV3hgN0qg2xUxVMSWlT7rt8RqK_rMHz0ob_9q2lXhUGTPj9_3-3LmNSWvkoA" /></div></header>
<nav className="hidden md:flex flex-col h-screen fixed left-0 top-0 p-md gap-sm bg-surface-container-low dark:bg-inverse-surface border-r border-outline-variant w-64 pt-[calc(48px+16px)] z-40"><div className="flex flex-col gap-xs flex-grow">
<Link className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="dashboard">dashboard</span><span className="font-label-md text-label-md">Dashboard</span></Link><Link className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" to="/phc/ashas"><span className="material-symbols-outlined" data-icon="groups">groups</span><span className="font-label-md text-label-md">Workers</span></Link><Link className="flex items-center gap-sm p-sm rounded-lg bg-secondary-container dark:bg-secondary text-on-secondary-container dark:text-on-secondary font-bold scale-95 transition-transform duration-150" to="/phc/beneficiaries"><span className="material-symbols-outlined" data-icon="person_celebrate" data-weight="fill">person_celebrate</span><span className="font-label-md text-label-md">Beneficiaries</span></Link><Link className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" to="/phc/reports/maternal"><span className="material-symbols-outlined" data-icon="analytics">analytics</span><span className="font-label-md text-label-md">Reports</span></Link><Link className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" to="/phc/vaccination"><span className="material-symbols-outlined" data-icon="inventory_2">inventory_2</span><span className="font-label-md text-label-md">Inventory</span></Link></div><div className="mt-auto flex flex-col gap-xs pt-md border-t border-outline-variant"><a className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" href="#"><span className="material-symbols-outlined" data-icon="settings">settings</span><span className="font-label-md text-label-md">Settings</span></a><a className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" href="#"><span className="material-symbols-outlined" data-icon="help">help</span><span className="font-label-md text-label-md">Support</span></a></div></nav>
<main className="flex-grow pt-[calc(48px+16px)] pb-[calc(60px+16px)] md:pb-lg md:ml-64 px-sm md:px-lg bg-background w-full">
<div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-lg gap-sm"><div><Link className="flex items-center text-primary font-label-md text-label-md hover:underline mb-xs" to="/phc/beneficiaries"><span className="material-symbols-outlined text-[16px] mr-1">arrow_back</span>
                    Back to Beneficiaries
                </Link><h1 className="font-headline-lg-mobile text-headline-lg-mobile md:font-headline-lg md:text-headline-lg text-on-surface">Vaccination Record</h1></div>
<div className="flex items-center gap-md bg-surface-container-lowest border border-outline-variant rounded-lg p-sm shadow-sm w-full md:w-auto"><div className="w-10 h-10 rounded-full bg-surface-variant flex items-center justify-center text-primary font-bold">
                    AK
                </div><div><p className="font-label-md text-label-md text-on-surface">Aarav Kumar</p><p className="font-caption text-caption text-on-surface-variant">DOB: 12-May-2023 (10 Weeks)</p></div><div className="ml-auto md:ml-md bg-secondary-container text-on-secondary-container px-2 py-1 rounded-full font-caption text-caption flex items-center gap-1"><span className="material-symbols-outlined text-[14px]">check_circle</span> On Track
                </div></div></div>
<div className="grid grid-cols-1 lg:grid-cols-3 gap-md lg:gap-lg">
<div className="lg:col-span-2 flex flex-col gap-md">
<div className="flex justify-between items-center bg-surface-container-lowest border border-outline-variant rounded-t-xl p-md border-b-0"><h2 className="font-headline-md text-headline-md text-on-surface flex items-center gap-sm"><span className="material-symbols-outlined text-primary">calendar_month</span>
                        Immunization Schedule
                    </h2><button className="bg-primary text-on-primary px-4 py-2 rounded-lg font-label-md text-label-md flex items-center gap-xs hover:bg-surface-tint transition-colors"><span className="material-symbols-outlined text-[18px]">add</span> Record Dose
                    </button></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-b-xl rounded-t-none shadow-sm flex flex-col gap-0 overflow-hidden relative">
<div className="absolute left-[36px] top-0 bottom-0 w-[2px] bg-outline-variant z-0 hidden md:block"></div>
<div className="flex flex-col relative z-10 border-b border-outline-variant last:border-b-0"><div className="bg-surface-container-low px-md py-sm sticky top-[48px] z-20 border-y border-outline-variant first:border-t-0 flex items-center"><div className="w-[24px] h-[24px] rounded-full bg-secondary flex items-center justify-center mr-md hidden md:flex border-2 border-surface-container-lowest z-10 shadow-sm"><span className="material-symbols-outlined text-on-secondary text-[14px]">check</span></div><h3 className="font-label-md text-label-md text-on-surface-variant uppercase tracking-wider">Birth</h3></div><div className="p-md md:pl-[68px] flex flex-col gap-sm">
<div className="flex flex-col md:flex-row justify-between md:items-center bg-surface border border-outline-variant rounded-lg p-sm relative overflow-hidden group"><div className="absolute left-0 top-0 bottom-0 w-[4px] bg-secondary"></div><div className="pl-xs flex flex-col"><span className="font-label-md text-label-md text-on-surface">BCG</span><span className="font-caption text-caption text-on-surface-variant">Tuberculosis</span></div><div className="mt-xs md:mt-0 flex items-center justify-between md:justify-end gap-md w-full md:w-auto"><div className="flex flex-col text-left md:text-right"><span className="font-label-md text-label-md text-secondary flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">done_all</span> Administered
                                        </span><span className="font-caption text-caption text-on-surface-variant">12-May-2023 • Dr. Sharma</span></div></div></div>
<div className="flex flex-col md:flex-row justify-between md:items-center bg-surface border border-outline-variant rounded-lg p-sm relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-[4px] bg-secondary"></div><div className="pl-xs flex flex-col"><span className="font-label-md text-label-md text-on-surface">OPV 0</span><span className="font-caption text-caption text-on-surface-variant">Polio</span></div><div className="mt-xs md:mt-0 flex items-center justify-between md:justify-end gap-md w-full md:w-auto"><div className="flex flex-col text-left md:text-right"><span className="font-label-md text-label-md text-secondary flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">done_all</span> Administered
                                        </span><span className="font-caption text-caption text-on-surface-variant">12-May-2023 • Dr. Sharma</span></div></div></div>
<div className="flex flex-col md:flex-row justify-between md:items-center bg-surface border border-outline-variant rounded-lg p-sm relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-[4px] bg-secondary"></div><div className="pl-xs flex flex-col"><span className="font-label-md text-label-md text-on-surface">Hepatitis B - Birth Dose</span><span className="font-caption text-caption text-on-surface-variant">Hepatitis B</span></div><div className="mt-xs md:mt-0 flex items-center justify-between md:justify-end gap-md w-full md:w-auto"><div className="flex flex-col text-left md:text-right"><span className="font-label-md text-label-md text-secondary flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">done_all</span> Administered
                                        </span><span className="font-caption text-caption text-on-surface-variant">12-May-2023 • Dr. Sharma</span></div></div></div></div></div>
<div className="flex flex-col relative z-10 border-b border-outline-variant last:border-b-0"><div className="bg-surface-container-low px-md py-sm sticky top-[48px] z-20 border-y border-outline-variant flex items-center"><div className="w-[24px] h-[24px] rounded-full bg-secondary flex items-center justify-center mr-md hidden md:flex border-2 border-surface-container-lowest z-10 shadow-sm"><span className="material-symbols-outlined text-on-secondary text-[14px]">check</span></div><h3 className="font-label-md text-label-md text-on-surface-variant uppercase tracking-wider">6 Weeks</h3></div><div className="p-md md:pl-[68px] flex flex-col gap-sm">
<div className="flex flex-col md:flex-row justify-between md:items-center bg-surface border border-outline-variant rounded-lg p-sm relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-[4px] bg-secondary"></div><div className="pl-xs flex flex-col"><span className="font-label-md text-label-md text-on-surface">OPV 1</span><span className="font-caption text-caption text-on-surface-variant">Polio</span></div><div className="mt-xs md:mt-0 flex items-center justify-between md:justify-end gap-md w-full md:w-auto"><div className="flex flex-col text-left md:text-right"><span className="font-label-md text-label-md text-secondary flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">done_all</span> Administered
                                        </span><span className="font-caption text-caption text-on-surface-variant">25-Jun-2023 • ASHA Worker Maya</span></div></div></div>
<div className="flex flex-col md:flex-row justify-between md:items-center bg-surface border border-outline-variant rounded-lg p-sm relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-[4px] bg-secondary"></div><div className="pl-xs flex flex-col"><span className="font-label-md text-label-md text-on-surface">Pentavalent 1</span><span className="font-caption text-caption text-on-surface-variant">DPT, Hep B, Hib</span></div><div className="mt-xs md:mt-0 flex items-center justify-between md:justify-end gap-md w-full md:w-auto"><div className="flex flex-col text-left md:text-right"><span className="font-label-md text-label-md text-secondary flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">done_all</span> Administered
                                        </span><span className="font-caption text-caption text-on-surface-variant">25-Jun-2023 • ASHA Worker Maya</span></div></div></div></div></div>
<div className="flex flex-col relative z-10 border-b border-outline-variant last:border-b-0 bg-primary-fixed opacity-95"><div className="bg-primary-container px-md py-sm sticky top-[48px] z-20 border-y border-primary-container flex items-center"><div className="w-[24px] h-[24px] rounded-full bg-primary flex items-center justify-center mr-md hidden md:flex border-2 border-surface-container-lowest z-10 shadow-sm animate-pulse"><div className="w-[10px] h-[10px] bg-on-primary rounded-full"></div></div><h3 className="font-label-md text-label-md text-on-primary-container uppercase tracking-wider font-bold">10 Weeks (Current)</h3></div><div className="p-md md:pl-[68px] flex flex-col gap-sm">
<div className="flex flex-col md:flex-row justify-between md:items-center bg-surface border-2 border-primary rounded-lg p-sm relative overflow-hidden shadow-md"><div className="absolute left-0 top-0 bottom-0 w-[6px] bg-primary"></div><div className="pl-xs flex flex-col"><span className="font-label-md text-label-md text-on-surface font-bold">OPV 2</span><span className="font-caption text-caption text-on-surface-variant">Polio</span></div><div className="mt-sm md:mt-0 flex items-center justify-between md:justify-end gap-md w-full md:w-auto"><div className="flex flex-col text-left md:text-right"><span className="font-label-md text-label-md text-primary flex items-center gap-xs font-bold"><span className="material-symbols-outlined text-[16px]">schedule</span> Due Today
                                        </span></div><button className="bg-primary text-on-primary px-3 py-1 rounded font-label-md text-label-md hover:bg-surface-tint">Mark Done</button></div></div>
<div className="flex flex-col md:flex-row justify-between md:items-center bg-error-container border border-error rounded-lg p-sm relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-[4px] bg-error"></div><div className="pl-xs flex flex-col"><span className="font-label-md text-label-md text-on-error-container">Rotavirus 2</span><span className="font-caption text-caption text-on-error-container opacity-80">Rotavirus Diarrhea</span></div><div className="mt-sm md:mt-0 flex items-center justify-between md:justify-end gap-md w-full md:w-auto"><div className="flex flex-col text-left md:text-right"><span className="font-label-md text-label-md text-error flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">warning</span> Missed (Was due 20-Jul)
                                        </span></div><button className="border border-error text-error px-3 py-1 rounded font-label-md text-label-md hover:bg-surface-container-highest">Reschedule</button></div></div></div></div>
<div className="flex flex-col relative z-10 border-b border-outline-variant last:border-b-0 opacity-70"><div className="bg-surface-container-low px-md py-sm sticky top-[48px] z-20 border-y border-outline-variant flex items-center"><div className="w-[24px] h-[24px] rounded-full bg-surface-container-highest flex items-center justify-center mr-md hidden md:flex border-2 border-surface-container-lowest z-10"><span className="w-[8px] h-[8px] bg-outline rounded-full"></span></div><h3 className="font-label-md text-label-md text-on-surface-variant uppercase tracking-wider">14 Weeks</h3></div><div className="p-md md:pl-[68px] flex flex-col gap-sm">
<div className="flex flex-col md:flex-row justify-between md:items-center bg-surface border border-outline-variant border-dashed rounded-lg p-sm relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-[4px] bg-outline-variant"></div><div className="pl-xs flex flex-col"><span className="font-label-md text-label-md text-on-surface-variant">OPV 3</span></div><div className="mt-xs md:mt-0 flex items-center justify-between md:justify-end gap-md w-full md:w-auto"><span className="font-caption text-caption text-on-surface-variant">Due: 17-Aug-2023</span></div></div>
<div className="flex flex-col md:flex-row justify-between md:items-center bg-surface border border-outline-variant border-dashed rounded-lg p-sm relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-[4px] bg-outline-variant"></div><div className="pl-xs flex flex-col"><span className="font-label-md text-label-md text-on-surface-variant">Pentavalent 3</span></div><div className="mt-xs md:mt-0 flex items-center justify-between md:justify-end gap-md w-full md:w-auto"><span className="font-caption text-caption text-on-surface-variant">Due: 17-Aug-2023</span></div></div></div></div></div></div>
<div className="flex flex-col gap-md">
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm overflow-hidden"><div className="bg-tertiary-container p-sm flex items-center gap-sm"><span className="material-symbols-outlined text-on-tertiary-container">event</span><h3 className="font-label-md text-label-md text-on-tertiary-container">Next Appointment</h3></div><div className="p-md flex flex-col gap-sm"><div className="flex justify-between items-center"><span className="font-display-lg text-display-lg text-tertiary">23 Jul</span><span className="bg-tertiary-fixed text-on-tertiary-fixed px-2 py-1 rounded font-caption text-caption">10:00 AM</span></div><p className="font-body-md text-body-md text-on-surface-variant">Sub-Center Clinic, Ward 4</p><p className="font-caption text-caption text-outline">Purpose: 10 Week Immunization</p><button className="mt-sm w-full border border-tertiary text-tertiary py-2 rounded-lg font-label-md text-label-md hover:bg-tertiary-fixed transition-colors">Reschedule Visit</button></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm overflow-hidden flex-grow flex flex-col"><div className="bg-surface-container-low p-sm flex justify-between items-center border-b border-outline-variant"><div className="flex items-center gap-sm"><span className="material-symbols-outlined text-error">healing</span><h3 className="font-label-md text-label-md text-on-surface">Adverse Events Following Immunization (AEFI)</h3></div></div><div className="p-md flex flex-col gap-sm overflow-y-auto max-h-[300px]">
<div className="border-l-2 border-outline pl-sm pb-sm border-b border-outline-variant border-b-dashed mb-sm last:border-b-0 last:mb-0"><div className="flex justify-between items-start mb-1"><span className="font-label-md text-label-md text-on-surface">Mild Fever</span><span className="font-caption text-caption text-outline">26-Jun-2023</span></div><p className="font-caption text-caption text-on-surface-variant mb-1">Following Pentavalent 1 dose. Parents advised PCM syrup.</p><span className="inline-block bg-surface-container text-on-surface-variant px-2 py-0.5 rounded text-[10px] uppercase font-bold tracking-wide">Resolved</span></div>
<button className="mt-auto flex items-center justify-center gap-xs text-primary font-label-md text-label-md hover:bg-surface-container-high py-2 rounded transition-colors w-full border border-dashed border-primary"><span className="material-symbols-outlined text-[18px]">add_circle</span> Report New Reaction
                        </button></div></div>
<div className="relative rounded-xl overflow-hidden shadow-md border border-outline-variant p-md isolate">
<div className="absolute inset-0 bg-gradient-to-br from-surface-variant/50 to-surface-bright/80 backdrop-blur-md -z-10"></div><h3 className="font-label-md text-label-md text-on-surface mb-md flex items-center gap-sm"><span className="material-symbols-outlined text-primary">monitor_weight</span> Vitals Summary
                    </h3><div className="grid grid-cols-2 gap-sm"><div className="bg-surface-container-lowest/70 p-sm rounded-lg border border-outline-variant/50 text-center"><span className="block font-caption text-caption text-on-surface-variant mb-1">Weight</span><span className="block font-headline-md text-headline-md text-on-surface">4.2 <span className="text-label-md">kg</span></span><span className="text-[10px] text-secondary flex items-center justify-center gap-0.5 mt-1"><span className="material-symbols-outlined text-[12px]">arrow_upward</span> Normal</span></div><div className="bg-surface-container-lowest/70 p-sm rounded-lg border border-outline-variant/50 text-center"><span className="block font-caption text-caption text-on-surface-variant mb-1">Height</span><span className="block font-headline-md text-headline-md text-on-surface">58 <span className="text-label-md">cm</span></span><span className="text-[10px] text-outline flex items-center justify-center gap-0.5 mt-1">Recorded 6 Wks</span></div></div></div></div></div></main>
<nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-sm py-xs bg-surface dark:bg-on-background border-t border-outline-variant shadow-lg rounded-t-[1.5rem]"><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant p-2 rounded-lg" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="home">home</span><span className="font-label-md text-label-md text-[10px]">Home</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant p-2 rounded-lg" to="/phc/households"><span className="material-symbols-outlined" data-icon="cottage">cottage</span><span className="font-label-md text-label-md text-[10px]">Households</span></Link><Link className="flex flex-col items-center justify-center bg-primary-container dark:bg-primary text-on-primary-container dark:text-on-primary rounded-full px-4 py-1 scale-90 transition-transform duration-200" to="/phc/beneficiaries"><span className="material-symbols-outlined" data-icon="person_search" data-weight="fill">person_search</span><span className="font-label-md text-label-md text-[10px] font-bold">Patients</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant p-2 rounded-lg" to="/phc/alerts"><span className="material-symbols-outlined" data-icon="assignment_turned_in">assignment_turned_in</span><span className="font-label-md text-label-md text-[10px]">Tasks</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant p-2 rounded-lg" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="account_circle">account_circle</span><span className="font-label-md text-label-md text-[10px]">Profile</span></Link></nav>
    </>
  )
}
