import { Link } from 'react-router-dom'
export default function ChildrenDirectoryPhcAdmin() {
  return (
    <>
<header className="bg-surface border-b border-outline-variant shadow-sm fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target md:px-lg"><div className="flex items-center gap-md">
<button className="md:hidden text-on-surface-variant hover:bg-surface-container transition-colors rounded-full p-2"><span aria-hidden className="material-symbols-outlined">menu</span></button><div className="text-headline-md font-headline-md font-bold text-primary">
                ASHA Sathi
            </div></div><div className="flex items-center gap-md"><button aria-label="sync" className="text-on-surface-variant hover:bg-surface-container transition-colors rounded-full p-2"><span aria-hidden className="material-symbols-outlined">sync</span></button><button aria-label="notifications" className="text-on-surface-variant hover:bg-surface-container transition-colors rounded-full p-2"><span aria-hidden className="material-symbols-outlined">notifications</span></button><div className="w-8 h-8 rounded-full overflow-hidden border border-outline-variant"><img alt="User Profile" className="object-cover w-full h-full" data-alt="A close up professional headshot of an administrative user in a healthcare setting. Bright, clear lighting on a soft neutral background. High resolution, clear focus, suitable for a profile avatar in a light mode medical application." src="https://lh3.googleusercontent.com/aida-public/AB6AXuAYiL2jFzaWQg9VJjK7GbJ4dzWyaMigbpDInWtCx41W_pgPX8s7TP4LX5WRIxyWPWX1Js-8QrvDG31OvXaElQXgkmJoSy_zvWWpSYKl32p7SR8V_VnKJJiRaMc1p_mYoNypBM_Vb1S_ewhdRw80Vk_jcoA3JL46zObgea0A1TdCRy6eY8f8BfFPK1-7Rzn7_febJNCdCxsj6itAWSd6zJxjh7T_PEDx9mY6qb9FSwQBb6KIMU4SyhDoyA" /></div></div></header><div className="flex pt-[48px] h-screen">
<nav className="hidden md:flex flex-col h-full w-64 bg-surface-container-low border-r border-outline-variant p-md gap-sm flex-shrink-0"><div className="mb-lg"><h2 className="font-headline-md text-headline-md font-black text-primary">Admin Portal</h2><p className="font-caption text-caption text-on-surface-variant">District Health Office</p></div><Link className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" to="/phc/dashboard"><span aria-hidden className="material-symbols-outlined">dashboard</span>
                Dashboard
            </Link><Link className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" to="/phc/ashas"><span aria-hidden className="material-symbols-outlined">groups</span>
                Workers
            </Link><Link aria-current="page" className="flex items-center gap-md px-4 py-3 rounded-lg bg-secondary-container text-on-secondary-container font-bold transition-all scale-95 font-label-md text-label-md" to="/phc/beneficiaries"><span aria-hidden className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>person_celebrate</span>
                Beneficiaries
            </Link><Link className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" to="/phc/reports/maternal"><span aria-hidden className="material-symbols-outlined">analytics</span>
                Reports
            </Link><Link className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" to="/phc/vaccination"><span aria-hidden className="material-symbols-outlined">inventory_2</span>
                Inventory
            </Link><div className="mt-auto"><button className="w-full bg-primary-container text-on-primary-container hover:bg-surface-tint hover:text-white transition-colors rounded-lg py-2 font-label-md text-label-md flex items-center justify-center gap-sm mb-lg"><span className="material-symbols-outlined text-sm">add</span> Add New Worker
                </button><a className="flex items-center gap-md px-4 py-2 rounded-lg text-on-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" href="#"><span aria-hidden className="material-symbols-outlined">settings</span>
                    Settings
                </a><a className="flex items-center gap-md px-4 py-2 rounded-lg text-on-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" href="#"><span aria-hidden className="material-symbols-outlined">help</span>
                    Support
                </a></div></nav>
<main className="flex-1 overflow-y-auto bg-background p-md md:p-lg pb-[80px] md:pb-lg">
<div className="mb-lg"><h1 className="font-headline-lg-mobile text-headline-lg-mobile md:font-headline-lg md:text-headline-lg text-on-surface mb-2">Child Health Records</h1><p className="text-on-surface-variant">Manage and monitor health vitals and vaccination status for children under 5.</p></div>
<div className="grid grid-cols-1 md:grid-cols-3 gap-md mb-xl"><div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm relative overflow-hidden flex flex-col justify-between h-32"><div className="flex justify-between items-start"><span className="font-label-md text-label-md text-on-surface-variant">Total Children Enrolled</span><div className="bg-primary-container text-on-primary-container rounded-full p-1 flex items-center justify-center"><span className="material-symbols-outlined text-sm" style={{ fontVariationSettings: '\'FILL\' 1' }}>face</span></div></div><div><div className="font-display-lg text-display-lg text-on-surface">1,248</div><div className="font-caption text-caption text-secondary mt-1 flex items-center"><span className="material-symbols-outlined text-[14px] mr-1">trending_up</span> +12 this month
                        </div></div></div><div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm relative overflow-hidden flex flex-col justify-between h-32"><div className="flex justify-between items-start"><span className="font-label-md text-label-md text-on-surface-variant">Malnourished (Severe/Mod)</span><div className="bg-error-container text-on-error-container rounded-full p-1 flex items-center justify-center"><span className="material-symbols-outlined text-sm" style={{ fontVariationSettings: '\'FILL\' 1' }}>warning</span></div></div><div><div className="font-display-lg text-display-lg text-error">86</div><div className="font-caption text-caption text-on-surface-variant mt-1">
                            Requires immediate follow-up
                        </div></div>
<div className="absolute left-0 top-0 bottom-0 w-1 bg-error"></div></div><div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm relative overflow-hidden flex flex-col justify-between h-32"><div className="flex justify-between items-start"><span className="font-label-md text-label-md text-on-surface-variant">Upcoming Vaccinations</span><div className="bg-tertiary-container text-on-tertiary-container rounded-full p-1 flex items-center justify-center"><span className="material-symbols-outlined text-sm" style={{ fontVariationSettings: '\'FILL\' 1' }}>vaccines</span></div></div><div><div className="font-display-lg text-display-lg text-on-surface">342</div><div className="font-caption text-caption text-on-surface-variant mt-1">
                            Due in the next 14 days
                        </div></div></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-md mb-lg shadow-sm flex flex-col lg:flex-row gap-md items-center justify-between"><div className="relative w-full lg:w-1/3"><span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant">search</span><input className="w-full pl-10 pr-4 py-2 bg-surface border border-outline-variant rounded-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary min-h-[48px]" placeholder="Search by child name, ID, or mother&#x27;s name..." type="text" /></div><div className="flex flex-wrap items-center gap-sm w-full lg:w-auto"><select className="bg-surface border border-outline-variant rounded-md px-3 py-2 text-on-surface focus:outline-none focus:ring-2 focus:ring-primary min-h-[48px] font-label-md text-label-md flex-1 lg:flex-none"><option value="">All Villages</option><option value="v1">Shantipur</option><option value="v2">Anandpur</option><option value="v3">Ramnagar</option></select><select className="bg-surface border border-outline-variant rounded-md px-3 py-2 text-on-surface focus:outline-none focus:ring-2 focus:ring-primary min-h-[48px] font-label-md text-label-md flex-1 lg:flex-none"><option value="">Age Group</option><option value="0-6m">0 - 6 Months</option><option value="6-24m">6 - 24 Months</option><option value="2-5y">2 - 5 Years</option></select><select className="bg-surface border border-outline-variant rounded-md px-3 py-2 text-on-surface focus:outline-none focus:ring-2 focus:ring-primary min-h-[48px] font-label-md text-label-md flex-1 lg:flex-none"><option value="">Vaccination Status</option><option value="up-to-date">Up to Date</option><option value="due">Due Soon</option><option value="missed">Missed/Overdue</option></select></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg shadow-sm overflow-hidden">
<div className="hidden lg:block overflow-x-auto"><table className="w-full text-left border-collapse"><thead className="bg-surface-container-low border-b border-outline-variant"><tr><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant">Child Details</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant">Age</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant">Mother's Name</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant">Nutrition Status</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant">Vaccination</th><th className="py-3 px-4 font-label-md text-label-md text-on-surface-variant text-right">Actions</th></tr></thead><tbody className="divide-y divide-outline-variant">
<tr className="hover:bg-surface-container transition-colors h-[40px]"><td className="py-2 px-4 flex items-center gap-3"><div className="w-1 h-8 bg-secondary rounded-full"></div><div><div className="font-label-md text-label-md text-on-surface">Aarav Patel</div><div className="font-caption text-caption text-on-surface-variant">ID: CH-9082</div></div></td><td className="py-2 px-4 text-on-surface">14 Months</td><td className="py-2 px-4 text-on-surface">Meera Patel</td><td className="py-2 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-secondary-container text-on-secondary-container font-caption text-caption">Normal</span></td><td className="py-2 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-secondary-container text-on-secondary-container font-caption text-caption">Up to date</span></td><td className="py-2 px-4 text-right"><button className="text-primary hover:text-primary-container p-1 rounded"><span className="material-symbols-outlined text-[20px]">visibility</span></button></td></tr>
<tr className="hover:bg-surface-container transition-colors h-[40px] bg-surface-container-lowest"><td className="py-2 px-4 flex items-center gap-3"><div className="w-1 h-8 bg-[#f59e0b] rounded-full"></div>
<div><div className="font-label-md text-label-md text-on-surface">Saanvi Sharma</div><div className="font-caption text-caption text-on-surface-variant">ID: CH-9104</div></div></td><td className="py-2 px-4 text-on-surface">8 Months</td><td className="py-2 px-4 text-on-surface">Priya Sharma</td><td className="py-2 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-[#fef3c7] text-[#92400e] font-caption text-caption">Underweight</span></td><td className="py-2 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-tertiary-container text-on-tertiary-container font-caption text-caption">Due (Measles)</span></td><td className="py-2 px-4 text-right"><button className="text-primary hover:text-primary-container p-1 rounded"><span className="material-symbols-outlined text-[20px]">visibility</span></button></td></tr>
<tr className="hover:bg-surface-container transition-colors h-[40px]"><td className="py-2 px-4 flex items-center gap-3"><div className="w-1 h-8 bg-error rounded-full"></div><div><div className="font-label-md text-label-md text-on-surface">Rohan Das</div><div className="font-caption text-caption text-on-surface-variant">ID: CH-8841</div></div></td><td className="py-2 px-4 text-on-surface">2.5 Years</td><td className="py-2 px-4 text-on-surface">Anita Das</td><td className="py-2 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-error-container text-on-error-container font-caption text-caption">Stunted</span></td><td className="py-2 px-4"><span className="inline-flex items-center px-2 py-1 rounded-full bg-error-container text-on-error-container font-caption text-caption">Missed (DPT Booster)</span></td><td className="py-2 px-4 text-right"><button className="text-primary hover:text-primary-container p-1 rounded"><span className="material-symbols-outlined text-[20px]">visibility</span></button></td></tr></tbody></table></div>
<div className="lg:hidden flex flex-col divide-y divide-outline-variant">
<div className="p-4 relative"><div className="absolute left-0 top-0 bottom-0 w-1 bg-secondary"></div><div className="flex justify-between items-start mb-2 pl-2"><div><div className="font-headline-md text-headline-md text-on-surface">Aarav Patel</div><div className="font-caption text-caption text-on-surface-variant">ID: CH-9082 • 14 Months</div></div><button className="text-primary hover:bg-surface-container rounded p-1 min-h-[48px] min-w-[48px] flex items-center justify-center"><span className="material-symbols-outlined">chevron_right</span></button></div><div className="pl-2 mb-2"><span className="font-label-md text-label-md text-on-surface-variant">Mother:</span><span className="text-on-surface">Meera Patel</span></div><div className="flex gap-2 pl-2 flex-wrap"><span className="inline-flex items-center px-2 py-1 rounded-full bg-secondary-container text-on-secondary-container font-caption text-caption">Normal Nutrition</span><span className="inline-flex items-center px-2 py-1 rounded-full bg-secondary-container text-on-secondary-container font-caption text-caption">Vax: Up to date</span></div></div>
<div className="p-4 relative bg-surface-container-lowest"><div className="absolute left-0 top-0 bottom-0 w-1 bg-[#f59e0b]"></div><div className="flex justify-between items-start mb-2 pl-2"><div><div className="font-headline-md text-headline-md text-on-surface">Saanvi Sharma</div><div className="font-caption text-caption text-on-surface-variant">ID: CH-9104 • 8 Months</div></div><button className="text-primary hover:bg-surface-container rounded p-1 min-h-[48px] min-w-[48px] flex items-center justify-center"><span className="material-symbols-outlined">chevron_right</span></button></div><div className="pl-2 mb-2"><span className="font-label-md text-label-md text-on-surface-variant">Mother:</span><span className="text-on-surface">Priya Sharma</span></div><div className="flex gap-2 pl-2 flex-wrap"><span className="inline-flex items-center px-2 py-1 rounded-full bg-[#fef3c7] text-[#92400e] font-caption text-caption">Underweight</span><span className="inline-flex items-center px-2 py-1 rounded-full bg-tertiary-container text-on-tertiary-container font-caption text-caption">Vax: Due (Measles)</span></div></div></div>
<div className="bg-surface-container-low border-t border-outline-variant p-3 flex items-center justify-between"><span className="font-caption text-caption text-on-surface-variant">Showing 1 to 10 of 1,248</span><div className="flex gap-1"><button className="px-3 py-1 border border-outline-variant rounded bg-surface text-on-surface-variant disabled:opacity-50" disabled>Prev</button><button className="px-3 py-1 border border-outline-variant rounded bg-surface text-on-surface-variant hover:bg-surface-container">Next</button></div></div></div></main></div>
<nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-sm py-xs bg-surface border-t border-outline-variant rounded-t-full shadow-lg h-[64px]"><Link className="flex flex-col items-center justify-center text-on-surface-variant hover:bg-surface-container-highest transition-colors rounded-lg w-16 py-1" to="/phc/dashboard"><span aria-hidden className="material-symbols-outlined mb-1">home</span><span className="font-label-md text-[10px] leading-none">Home</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant hover:bg-surface-container-highest transition-colors rounded-lg w-16 py-1" to="/phc/households"><span aria-hidden className="material-symbols-outlined mb-1">cottage</span><span className="font-label-md text-[10px] leading-none">Households</span></Link><Link aria-current="page" className="flex flex-col items-center justify-center bg-primary-container text-on-primary-container rounded-full px-4 py-1 scale-90 transition-transform duration-200" to="/phc/beneficiaries"><span aria-hidden className="material-symbols-outlined mb-1" style={{ fontVariationSettings: '\'FILL\' 1' }}>person_search</span><span className="font-label-md text-[10px] leading-none font-bold">Patients</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant hover:bg-surface-container-highest transition-colors rounded-lg w-16 py-1" to="/phc/alerts"><span aria-hidden className="material-symbols-outlined mb-1">assignment_turned_in</span><span className="font-label-md text-[10px] leading-none">Tasks</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant hover:bg-surface-container-highest transition-colors rounded-lg w-16 py-1" to="/phc/dashboard"><span aria-hidden className="material-symbols-outlined mb-1">account_circle</span><span className="font-label-md text-[10px] leading-none">Profile</span></Link></nav>
    </>
  )
}
