import { Link } from 'react-router-dom'
import { LogoutButton } from '@/components/common/LogoutButton'
export default function CreateNewReferralPhcAdmin() {
  return (
    <>
<aside className="hidden md:flex flex-col h-screen w-64 fixed left-0 top-0 z-40 bg-surface-container-low border-r border-outline-variant py-md">
<div className="px-md mb-xl flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-primary-container flex items-center justify-center shrink-0"><span className="material-symbols-outlined text-on-primary-container" data-weight="fill">local_hospital</span></div><div><h1 className="font-headline-md text-headline-md font-extrabold text-primary truncate">PHC Admin</h1><p className="font-caption text-caption text-on-surface-variant truncate">District Health Center</p></div></div>
<nav className="flex-1 overflow-y-auto pr-sm"><ul className="flex flex-col gap-unit"><li><Link className="flex items-center gap-md px-md py-sm ml-sm text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 rounded-r-full group" to="/phc/dashboard"><span className="material-symbols-outlined text-outline group-hover:text-on-surface">dashboard</span><span className="font-label-md text-label-md">Dashboard</span></Link></li><li><Link className="flex items-center gap-md px-md py-sm ml-sm text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 rounded-r-full group" to="/phc/ashas"><span className="material-symbols-outlined text-outline group-hover:text-on-surface">group</span><span className="font-label-md text-label-md">Workers</span></Link></li><li><Link className="flex items-center gap-md px-md py-sm ml-sm text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 rounded-r-full group" to="/phc/beneficiaries"><span className="material-symbols-outlined text-outline group-hover:text-on-surface">person</span><span className="font-label-md text-label-md">Beneficiaries</span></Link></li><li><Link className="flex items-center gap-md px-md py-sm ml-sm text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 rounded-r-full group" to="/phc/households"><span className="material-symbols-outlined text-outline group-hover:text-on-surface">home</span><span className="font-label-md text-label-md">Households</span></Link></li><li><Link className="flex items-center gap-md px-md py-sm ml-sm text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 rounded-r-full group" to="/phc/maternal"><span className="material-symbols-outlined text-outline group-hover:text-on-surface">pregnant_woman</span><span className="font-label-md text-label-md">Maternal Health</span></Link></li><li><Link className="flex items-center gap-md px-md py-sm ml-sm text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 rounded-r-full group" to="/phc/children"><span className="material-symbols-outlined text-outline group-hover:text-on-surface">child_care</span><span className="font-label-md text-label-md">Child Health</span></Link></li>
<li><Link className="flex items-center gap-md px-md py-sm ml-sm bg-primary-container text-on-primary-container font-bold rounded-r-full active:scale-95 duration-150" to="/phc/referrals"><span className="material-symbols-outlined" data-weight="fill">swap_horiz</span><span className="font-label-md text-label-md">Referrals</span></Link></li></ul></nav>
<div className="mt-auto border-t border-outline-variant pt-sm pr-sm"><ul className="flex flex-col gap-unit"><li><a className="flex items-center gap-md px-md py-sm ml-sm text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 rounded-r-full group" href="#"><span className="material-symbols-outlined text-outline group-hover:text-on-surface">settings</span><span className="font-label-md text-label-md">Settings</span></a></li><li><LogoutButton className="className='flex items-center gap-md px-md py-sm ml-sm text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 rounded-r-full group'"><span className="material-symbols-outlined text-outline group-hover:text-on-surface">logout</span><span className="font-label-md text-label-md">Logout</span></LogoutButton></li></ul></div></aside>
<div className="flex-1 md:ml-64 flex flex-col min-h-screen">
<header className="w-full h-16 sticky top-0 z-50 bg-surface border-b border-outline-variant shadow-sm flex justify-between items-center px-lg max-w-[1440px] mx-auto">
<div className="flex md:hidden items-center gap-sm"><button className="p-sm text-on-surface-variant hover:bg-surface-container-low transition-colors rounded-full cursor-pointer active:opacity-80"><span className="material-symbols-outlined">menu</span></button><span className="font-headline-lg-mobile text-headline-lg-mobile font-bold text-primary">PHC Portal</span></div>
<div className="hidden md:flex items-center gap-sm"><Link className="flex items-center text-on-surface-variant hover:text-primary transition-colors" to="/phc/referrals"><span className="material-symbols-outlined">arrow_back</span></Link><span className="font-headline-md text-headline-md font-bold text-primary">New Referral</span></div>
<div className="flex items-center gap-md"><button className="p-sm text-on-surface-variant hover:bg-surface-container-low transition-colors rounded-full cursor-pointer active:opacity-80 relative"><span className="material-symbols-outlined">sync</span>
<span className="absolute top-1 right-1 w-2 h-2 bg-secondary rounded-full border border-surface"></span></button><button className="p-sm text-on-surface-variant hover:bg-surface-container-low transition-colors rounded-full cursor-pointer active:opacity-80"><span className="material-symbols-outlined">notifications</span></button><div className="w-8 h-8 rounded-full overflow-hidden border border-outline-variant cursor-pointer active:opacity-80 shrink-0"><img alt="Administrator Profile" className="w-full h-full object-cover" data-alt="A professional headshot of a healthcare administrator in a clean, modern clinic setting, bright lighting, light mode aesthetic, warm and approachable." src="https://lh3.googleusercontent.com/aida-public/AB6AXuCZ8CMgBbZMJ5L-ISZzVIahvrUiHpoMszPQMYkLrEojniKskilP82cIcl7VhM_Nzw1FHbXMekWs9kEmVi1A_h7oElV7E7M-zUAZZDCTvgG9CiB5f8Heq6pbBXUvWwbEWgZIBI5Bxd9k-Peh2TRyhFxZoGL7l5wkDhrJEEF11ufYU7Arj6JlqruBp_RyPbxIijv-EwUN-bZcp1xIUtksksNRZ7j76Rv82Z2Et38bPKg4hkggDs65NBdLTQ" /></div></div></header>
<main className="flex-1 p-4 md:p-lg lg:p-xl max-w-4xl mx-auto w-full"><div className="mb-lg"><h2 className="font-display-lg text-display-lg text-on-surface hidden md:block">Create New Referral</h2><p className="font-body-md text-body-md text-on-surface-variant mt-2">Transfer a patient to a specialized facility for advanced care.</p></div><form className="flex flex-col gap-lg">
<section className="bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm overflow-hidden"><div className="bg-surface-container-low px-md py-sm border-b border-outline-variant flex items-center gap-sm"><span className="material-symbols-outlined text-primary">person_search</span><h3 className="font-headline-md text-headline-md text-on-surface">1. Patient Selection</h3></div><div className="p-md lg:p-lg flex flex-col gap-form-gap">
<div className="relative w-full"><label className="sr-only" htmlFor="patientSearch">Search Beneficiaries</label><div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none"><span className="material-symbols-outlined text-outline">search</span></div><input className="w-full min-h-[48px] pl-10 pr-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-md text-body-md text-on-surface focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors" id="patientSearch" placeholder="Search by name, ID, or phone number..." type="text" value="Asha Devi" /></div>
<div className="relative flex items-center p-md bg-surface border border-outline-variant rounded-lg">
<div className="absolute left-0 top-0 bottom-0 w-2 bg-secondary-container rounded-l-lg"></div><div className="ml-4 flex-1"><div className="flex justify-between items-start"><div><h4 className="font-headline-md text-headline-md text-on-surface">Asha Devi</h4><p className="font-body-md text-body-md text-on-surface-variant">ID: PHC-2023-8912 • Age: 28 • Female</p></div>
<span className="px-3 py-1 bg-secondary-container text-on-secondary-container rounded-full font-label-md text-label-md text-xs">High Risk Pregnancy</span></div></div><button className="ml-4 p-2 text-outline hover:text-error transition-colors rounded-full hover:bg-error-container" type="button"><span className="material-symbols-outlined">close</span></button></div></div></section>
<section className="bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm overflow-hidden"><div className="bg-surface-container-low px-md py-sm border-b border-outline-variant flex items-center gap-sm"><span className="material-symbols-outlined text-primary">local_hospital</span><h3 className="font-headline-md text-headline-md text-on-surface">2. Clinical Details</h3></div><div className="p-md lg:p-lg flex flex-col gap-form-gap">
<div><label className="block font-label-md text-label-md text-on-surface mb-2" htmlFor="destination">Destination Facility *</label><div className="relative"><select className="w-full min-h-[48px] appearance-none rounded-lg border border-outline-variant bg-surface px-4 py-3 pr-10 font-body-md text-body-md text-on-surface focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors" id="destination"><option disabled selected value="">Select facility type...</option><option value="dh">District Hospital (DH)</option><option value="chc">Community Health Centre (CHC)</option><option value="spec">Specialist Maternal Clinic</option><option value="tertiary">Tertiary Care Center</option></select><div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none"><span className="material-symbols-outlined text-outline">expand_more</span></div></div></div>
<div><label className="block font-label-md text-label-md text-on-surface mb-2">Clinical Priority *</label><div className="grid grid-cols-1 md:grid-cols-3 gap-md">
<label className="relative cursor-pointer group"><input checked={false} className="peer sr-only radio-card-input" name="priority" type="radio" value="routine" /><div className="min-h-[48px] radio-card-body flex items-center justify-center p-3 rounded-lg border border-outline-variant bg-surface text-on-surface-variant peer-checked:border-primary peer-checked:bg-primary-container peer-checked:text-on-primary-container peer-checked:font-bold hover:bg-surface-container-low transition-all"><span className="material-symbols-outlined mr-2 text-[20px]">assignment</span><span className="font-body-md text-body-md group-hover:text-on-surface peer-checked:text-on-primary-container">Routine</span></div></label>
<label className="relative cursor-pointer group"><input className="peer sr-only radio-card-input" name="priority" type="radio" value="urgent" /><div className="min-h-[48px] radio-card-body flex items-center justify-center p-3 rounded-lg border border-outline-variant bg-surface text-on-surface-variant peer-checked:border-tertiary peer-checked:bg-tertiary-container peer-checked:text-on-tertiary-container peer-checked:font-bold hover:bg-surface-container-low transition-all"><span className="material-symbols-outlined mr-2 text-[20px]">timer</span><span className="font-body-md text-body-md group-hover:text-on-surface peer-checked:text-on-tertiary-container">Urgent</span></div></label>
<label className="relative cursor-pointer group"><input className="peer sr-only radio-card-input" name="priority" type="radio" value="emergency" /><div className="min-h-[48px] radio-card-body flex items-center justify-center p-3 rounded-lg border border-outline-variant bg-surface text-on-surface-variant peer-checked:border-error peer-checked:bg-error-container peer-checked:text-on-error-container peer-checked:font-bold hover:bg-surface-container-low transition-all"><span className="material-symbols-outlined mr-2 text-[20px]">emergency</span><span className="font-body-md text-body-md group-hover:text-on-surface peer-checked:text-on-error-container">Emergency</span></div></label></div></div>
<div><label className="block font-label-md text-label-md text-on-surface mb-2" htmlFor="reason">Reason for Referral & Clinical Notes *</label><textarea className="w-full rounded-lg border border-outline-variant bg-surface px-4 py-3 font-body-md text-body-md text-on-surface focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors resize-y" id="reason" placeholder="Enter symptoms, preliminary diagnosis, and reason for transfer..." rows={4}></textarea></div></div></section>
<section className="bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm overflow-hidden mb-xl"><div className="bg-surface-container-low px-md py-sm border-b border-outline-variant flex items-center gap-sm"><span className="material-symbols-outlined text-primary">directions_car</span><h3 className="font-headline-md text-headline-md text-on-surface">3. Logistics</h3></div><div className="p-md lg:p-lg flex flex-col gap-form-gap md:grid md:grid-cols-2">
<div className="md:col-span-2"><label className="block font-label-md text-label-md text-on-surface mb-2">Required Transport</label><div className="flex gap-md"><label className="flex items-center gap-2 cursor-pointer p-2 rounded hover:bg-surface-container-low"><input className="w-5 h-5 text-primary border-outline-variant focus:ring-primary accent-primary" name="transport" type="radio" value="ambulance" /><span className="font-body-md text-body-md text-on-surface">Ambulance</span></label><label className="flex items-center gap-2 cursor-pointer p-2 rounded hover:bg-surface-container-low"><input checked={false} className="w-5 h-5 text-primary border-outline-variant focus:ring-primary accent-primary" name="transport" type="radio" value="self" /><span className="font-body-md text-body-md text-on-surface">Self / Private</span></label></div></div>
<div><label className="block font-label-md text-label-md text-on-surface mb-2" htmlFor="staff">Accompanying Staff (Optional)</label><div className="relative"><div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none"><span className="material-symbols-outlined text-outline">badge</span></div><input className="w-full min-h-[48px] pl-10 pr-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-md text-body-md text-on-surface focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors" id="staff" placeholder="E.g., ASHA Worker Name" type="text" /></div></div>
<div><label className="block font-label-md text-label-md text-on-surface mb-2" htmlFor="departure">Estimated Departure Time</label><div className="relative"><div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none"><span className="material-symbols-outlined text-outline">schedule</span></div><input className="w-full min-h-[48px] pl-10 pr-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-md text-body-md text-on-surface focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors" id="departure" type="datetime-local" /></div></div></div></section>
<div className="fixed bottom-0 left-0 right-0 bg-surface border-t border-outline-variant p-4 flex justify-end gap-md md:static md:bg-transparent md:border-none md:p-0 z-10 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.05)] md:shadow-none"><button className="min-h-[48px] px-lg py-2 rounded-full font-label-md text-label-md text-primary border border-primary hover:bg-primary-container hover:text-on-primary-container transition-colors focus:ring-2 focus:ring-primary focus:ring-offset-2" type="button">
                        Cancel
                    </button><button className="min-h-[48px] px-xl py-2 rounded-full font-label-md text-label-md bg-primary text-on-primary hover:bg-on-primary-fixed-variant transition-colors shadow-sm focus:ring-2 focus:ring-primary focus:ring-offset-2 flex items-center gap-2" type="submit"><span>Send Referral</span><span className="material-symbols-outlined text-[20px]">send</span></button></div>
<div className="h-20 md:hidden block"></div></form></main></div>
    </>
  )
}
