import { PhcSidebar } from '@/components/layout/PhcSidebar'
export default function CriticalAlertsHighRiskMonitoringPhcAdmin() {
  return (
    <div className="flex h-screen overflow-hidden bg-surface">
<PhcSidebar />
<main className="flex-1 overflow-y-auto bg-surface p-lg md:p-xl flex flex-col gap-lg ml-0 md:ml-64 pb-24 md:pb-0">
<div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-md"><div><h1 className="font-display-lg text-display-lg text-on-background mb-xs">Active Alerts</h1><p className="font-body-md text-body-md text-on-surface-variant">Immediate administrative action required across division.</p></div><div className="flex gap-sm"><div className="bg-surface-container-highest px-md py-sm rounded-DEFAULT flex items-center gap-sm border border-outline-variant"><span className="w-2 h-2 rounded-full bg-error animate-pulse"></span><span className="font-label-md text-label-md text-on-surface">Live Sync Active</span></div></div></div>
<div className="grid grid-cols-1 lg:grid-cols-12 gap-lg h-full">
<div className="lg:col-span-8 flex flex-col gap-lg">
<div className="flex items-center gap-sm border-b border-outline-variant pb-sm"><span className="material-symbols-outlined text-error">personal_injury</span><h2 className="font-headline-md text-headline-md text-on-surface">Patient Emergencies</h2><span className="bg-error-container text-on-error-container px-sm py-[2px] rounded-full font-caption text-caption ml-auto">6 Critical</span></div><div className="flex flex-col gap-md overflow-y-auto pr-sm" style={{ maxHeight: 'calc(100vh - 300px)' }}>
<div className="bg-surface-container-lowest border border-error-container rounded-xl p-md flex gap-md shadow-sm relative overflow-hidden group hover:border-error transition-colors"><div className="absolute left-0 top-0 bottom-0 w-2 bg-error"></div><div className="w-12 h-12 bg-error-container rounded-full flex items-center justify-center shrink-0 mt-xs"><span className="material-symbols-outlined text-on-error-container" style={{ fontVariationSettings: '\'FILL\' 1' }}>pregnant_woman</span></div><div className="flex-1 flex flex-col"><div className="flex justify-between items-start mb-xs"><div><div className="flex items-center gap-sm"><h3 className="font-headline-md text-headline-md text-on-surface">Asha Devi, 26y</h3><span className="bg-error text-on-error px-xs py-[2px] rounded-DEFAULT font-caption text-caption uppercase tracking-wide">Critical</span></div><p className="font-body-md text-body-md text-on-surface-variant">Village: Rampur (ASHA: Sunita M.)</p></div><span className="font-caption text-caption text-error font-bold flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">schedule</span> 15m ago
                                    </span></div><div className="bg-surface-container-low p-sm rounded-DEFAULT mb-md"><p className="font-body-md text-body-md text-on-surface"><span className="font-bold text-error">High BP (180/110)</span> recorded during 3rd trimester checkup. Severe preeclampsia risk.</p></div><div className="flex gap-sm mt-auto"><button className="bg-error hover:bg-[#a30000] text-on-error font-label-md text-label-md px-md py-sm rounded-DEFAULT transition-colors flex items-center gap-xs"><span className="material-symbols-outlined text-[18px]">emergency_share</span> Direct Ambulance
                                    </button><button className="border border-outline-variant hover:bg-surface-container-highest text-on-surface font-label-md text-label-md px-md py-sm rounded-DEFAULT transition-colors">
                                        Contact ASHA
                                    </button></div></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md flex gap-md shadow-sm relative overflow-hidden hover:border-tertiary-container transition-colors"><div className="absolute left-0 top-0 bottom-0 w-2 bg-tertiary"></div><div className="w-12 h-12 bg-tertiary-container rounded-full flex items-center justify-center shrink-0 mt-xs"><span className="material-symbols-outlined text-on-tertiary-container" style={{ fontVariationSettings: '\'FILL\' 1' }}>child_care</span></div><div className="flex-1 flex flex-col"><div className="flex justify-between items-start mb-xs"><div><div className="flex items-center gap-sm"><h3 className="font-headline-md text-headline-md text-on-surface">Rahul K., 14mo</h3><span className="bg-tertiary text-on-tertiary px-xs py-[2px] rounded-DEFAULT font-caption text-caption uppercase tracking-wide">High Risk - SAM</span></div><p className="font-body-md text-body-md text-on-surface-variant">Village: Sitapur (ASHA: Meena G.)</p></div><span className="font-caption text-caption text-on-surface-variant flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">schedule</span> 1h ago
                                    </span></div><div className="bg-surface-container-low p-sm rounded-DEFAULT mb-md"><p className="font-body-md text-body-md text-on-surface"><span className="font-bold">MUAC reading red</span> ({'<'} 11.5cm). Continuous weight loss over 2 months. NRC admission required.</p></div><div className="flex gap-sm mt-auto"><button className="bg-primary hover:bg-primary-container text-on-primary font-label-md text-label-md px-md py-sm rounded-DEFAULT transition-colors flex items-center gap-xs"><span className="material-symbols-outlined text-[18px]">local_hospital</span> Initiate NRC Transfer
                                    </button></div></div></div></div></div>
<div className="lg:col-span-4 flex flex-col gap-lg">
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm flex flex-col h-1/2"><div className="p-md border-b border-outline-variant bg-surface-container-low flex justify-between items-center rounded-t-xl"><div className="flex items-center gap-sm"><span className="material-symbols-outlined text-primary">directions_car</span><h2 className="font-headline-md text-headline-md text-on-surface">Referral Status</h2></div><span className="bg-primary-container text-on-primary-container px-sm py-[2px] rounded-full font-caption text-caption">2 Pending</span></div><div className="flex-1 p-sm overflow-y-auto">
<div className="p-sm mb-sm bg-surface-container rounded-DEFAULT border border-primary-fixed-dim"><div className="flex justify-between mb-xs"><span className="font-label-md text-label-md text-primary">To District Hospital</span><span className="font-caption text-caption bg-secondary-container text-on-secondary-container px-xs rounded-DEFAULT">Awaiting Acceptance</span></div><p className="font-body-sm text-body-md text-on-surface mb-xs">Patient ID: #9928 (Complicated Labor)</p><button className="w-full border border-primary text-primary hover:bg-primary-container hover:text-on-primary-container font-label-md text-label-md py-xs rounded-DEFAULT transition-colors mt-xs">
                                    Follow Up Call
                                </button></div>
<div className="p-sm bg-surface-container rounded-DEFAULT border border-outline-variant"><div className="flex justify-between mb-xs"><span className="font-label-md text-label-md text-on-surface">Ambulance Dispatch</span><span className="font-caption text-caption bg-surface-variant text-on-surface-variant px-xs rounded-DEFAULT">ETA 25m</span></div><p className="font-body-sm text-body-md text-on-surface-variant">Village: Kherwadi</p></div></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm flex flex-col h-1/2"><div className="p-md border-b border-outline-variant flex justify-between items-center"><div className="flex items-center gap-sm"><span className="material-symbols-outlined text-on-surface-variant">check_circle</span><h2 className="font-headline-md text-headline-md text-on-surface">Resolution Log</h2></div><span className="font-caption text-caption text-on-surface-variant">Today</span></div><div className="flex-1 p-md overflow-y-auto"><ul className="relative border-l border-outline-variant ml-sm space-y-md"><li className="pl-md relative"><div className="absolute w-3 h-3 bg-secondary rounded-full -left-[6px] top-1"></div><p className="font-body-md text-body-md text-on-surface">Ambulance dispatched for <span className="font-bold">Manoj T.</span></p><p className="font-caption text-caption text-on-surface-variant">10:45 AM by Dr. Sharma</p></li><li className="pl-md relative"><div className="absolute w-3 h-3 bg-secondary rounded-full -left-[6px] top-1"></div><p className="font-body-md text-body-md text-on-surface">Missed TB follow-up contacted.</p><p className="font-caption text-caption text-on-surface-variant">09:15 AM by Admin A1</p></li><li className="pl-md relative"><div className="absolute w-3 h-3 bg-outline-variant rounded-full -left-[6px] top-1"></div><p className="font-body-md text-body-md text-on-surface-variant">Daily sync completed.</p><p className="font-caption text-caption text-on-surface-variant">08:00 AM System</p></li></ul></div></div></div></div></main>
    </div>
  )
}
