import { PhcSidebar } from '@/components/layout/PhcSidebar'
export default function HouseholdHealthSurveyPhcAdmin() {
  return (
    <div className="flex h-screen overflow-hidden bg-surface">
<PhcSidebar />
<main className="flex-1 ml-0 md:ml-64 pt-touch-target md:pt-0 p-sm md:p-lg overflow-y-auto flex flex-col pb-24 md:pb-0">
<header className="mb-lg flex flex-col md:flex-row md:items-end justify-between gap-md"><div><p className="font-caption text-caption text-on-surface-variant mb-xs flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">arrow_back</span>
                    Back to Households List
                </p><h1 className="font-display-lg text-display-lg md:text-[32px] text-on-background font-bold">Household Health Survey Report</h1><p className="font-body-md text-body-md text-outline">Household ID: HH-9843-K • Village: Rampur • Head: Ramesh Kumar</p></div><div className="flex gap-sm"><div className="bg-surface-container-high rounded-full px-md py-xs flex items-center gap-xs border border-outline-variant"><span className="material-symbols-outlined text-secondary text-[20px]">cloud_done</span><span className="font-label-md text-label-md text-on-surface">Synced: 10m ago</span></div></div></header>
<div className="grid grid-cols-1 md:grid-cols-4 gap-md mb-lg"><div className="bg-surface-container-lowest p-md rounded-xl border border-outline-variant shadow-sm border-l-4 border-l-secondary flex flex-col justify-between min-h-[100px]"><p className="font-label-md text-label-md text-on-surface-variant">Overall Health Risk</p><div className="flex items-center justify-between mt-sm"><span className="font-headline-lg text-headline-lg font-bold text-secondary">Low</span><span className="material-symbols-outlined text-secondary text-[32px]">health_and_safety</span></div></div><div className="bg-surface-container-lowest p-md rounded-xl border border-outline-variant shadow-sm border-l-4 border-l-[#FF9800] flex flex-col justify-between min-h-[100px]"><p className="font-label-md text-label-md text-on-surface-variant">Sanitation Score</p><div className="flex items-center justify-between mt-sm"><span className="font-headline-lg text-headline-lg font-bold text-[#FF9800]">65/100</span><span className="material-symbols-outlined text-[#FF9800] text-[32px]">water_drop</span></div></div><div className="bg-surface-container-lowest p-md rounded-xl border border-outline-variant shadow-sm border-l-4 border-l-secondary flex flex-col justify-between min-h-[100px]"><p className="font-label-md text-label-md text-on-surface-variant">Immunization</p><div className="flex items-center justify-between mt-sm"><span className="font-headline-lg text-headline-lg font-bold text-secondary">100%</span><span className="material-symbols-outlined text-secondary text-[32px]">vaccines</span></div></div><div className="bg-surface-container-lowest p-md rounded-xl border border-outline-variant shadow-sm border-l-4 border-l-[#D50000] flex flex-col justify-between min-h-[100px]"><p className="font-label-md text-label-md text-on-surface-variant">Chronic Disease</p><div className="flex items-center justify-between mt-sm"><span className="font-headline-lg text-headline-lg font-bold text-[#D50000]">High</span><span className="material-symbols-outlined text-[#D50000] text-[32px]">coronavirus</span></div></div></div>
<div className="grid grid-cols-1 md:grid-cols-12 gap-lg">
<div className="md:col-span-8 bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm p-lg"><h3 className="font-headline-md text-headline-md font-bold mb-md text-on-background flex items-center gap-xs"><span className="material-symbols-outlined text-primary">clean_hands</span>
                    Sanitation & Water
                </h3><div className="grid grid-cols-1 md:grid-cols-2 gap-form-gap"><div><p className="font-label-md text-label-md text-outline mb-xs">Primary Water Source</p><p className="font-body-lg text-body-lg text-on-surface font-semibold bg-surface-container-low p-sm rounded-lg border border-outline-variant/50">Hand Pump (Public)</p></div><div><p className="font-label-md text-label-md text-outline mb-xs">Distance to Source</p><p className="font-body-lg text-body-lg text-on-surface font-semibold bg-surface-container-low p-sm rounded-lg border border-outline-variant/50">{'<'} 500 meters</p></div><div><p className="font-label-md text-label-md text-outline mb-xs">Toilet Facility Type</p><p className="font-body-lg text-body-lg text-on-surface font-semibold bg-surface-container-low p-sm rounded-lg border border-outline-variant/50">Pit Latrine</p></div><div><p className="font-label-md text-label-md text-outline mb-xs">Waste Disposal</p><p className="font-body-lg text-body-lg text-on-surface font-semibold bg-surface-container-low p-sm rounded-lg border border-outline-variant/50">Open Dumping</p></div></div></div>
<div className="md:col-span-4 bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm p-lg"><h3 className="font-headline-md text-headline-md font-bold mb-md text-on-background flex items-center gap-xs"><span className="material-symbols-outlined text-secondary">immunology</span>
                    Immunization
                </h3><div className="flex flex-col gap-md"><div><div className="flex justify-between mb-xs"><span className="font-label-md text-label-md text-on-surface-variant">Children ({'<'} 5 yrs)</span><span className="font-label-md text-label-md font-bold text-secondary">100%</span></div><div className="w-full bg-surface-variant rounded-full h-2"><div className="bg-secondary h-2 rounded-full" style={{ width: '100%' }}></div></div></div><div><div className="flex justify-between mb-xs"><span className="font-label-md text-label-md text-on-surface-variant">Pregnant Women</span><span className="font-label-md text-label-md font-bold text-secondary">100%</span></div><div className="w-full bg-surface-variant rounded-full h-2"><div className="bg-secondary h-2 rounded-full" style={{ width: '100%' }}></div></div></div><div className="mt-sm p-sm bg-secondary-container/20 rounded-lg border border-secondary-container text-secondary flex items-start gap-xs"><span className="material-symbols-outlined text-[18px]">check_circle</span><p className="font-caption text-caption">All eligible members are fully vaccinated up to date.</p></div></div></div>
<div className="md:col-span-6 bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm p-lg"><h3 className="font-headline-md text-headline-md font-bold mb-md text-on-background flex items-center gap-xs"><span className="material-symbols-outlined text-[#FF9800]">restaurant</span>
                    Nutrition
                </h3><div className="space-y-md"><div className="flex justify-between items-center border-b border-outline-variant/30 pb-sm"><span className="font-body-md text-body-md text-on-surface-variant">Primary Diet</span><span className="font-label-md text-label-md text-on-surface">Vegetarian</span></div><div className="flex justify-between items-center border-b border-outline-variant/30 pb-sm"><span className="font-body-md text-body-md text-on-surface-variant">Salt Type Used</span><span className="font-label-md text-label-md text-on-surface">Iodized</span></div><div className="flex justify-between items-center border-b border-outline-variant/30 pb-sm"><span className="font-body-md text-body-md text-on-surface-variant">Meals per Day (Avg)</span><span className="font-label-md text-label-md text-on-surface">3</span></div><div className="flex justify-between items-center"><span className="font-body-md text-body-md text-on-surface-variant">Food Security Status</span><span className="font-label-md text-label-md px-sm py-[2px] bg-secondary-container/30 text-secondary rounded-full">Secure</span></div></div></div>
<div className="md:col-span-6 bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm p-lg"><h3 className="font-headline-md text-headline-md font-bold mb-md text-on-background flex items-center gap-xs"><span className="material-symbols-outlined text-error">coronavirus</span>
                    Chronic Diseases Prevalence
                </h3><div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-outline-variant"><th className="font-label-md text-label-md text-on-surface-variant py-sm px-xs">Condition</th><th className="font-label-md text-label-md text-on-surface-variant py-sm px-xs">Members Affected</th><th className="font-label-md text-label-md text-on-surface-variant py-sm px-xs">Status</th></tr></thead><tbody><tr className="border-b border-outline-variant/30 hover:bg-surface-container-low transition-colors"><td className="font-body-md text-body-md py-sm px-xs">Hypertension (BP)</td><td className="font-body-md text-body-md py-sm px-xs font-semibold">2</td><td className="py-sm px-xs"><span className="font-caption text-caption px-sm py-[2px] bg-error-container text-on-error-container rounded-full">Under Meds</span></td></tr><tr className="border-b border-outline-variant/30 hover:bg-surface-container-low transition-colors"><td className="font-body-md text-body-md py-sm px-xs">Diabetes (Sugar)</td><td className="font-body-md text-body-md py-sm px-xs font-semibold">1</td><td className="py-sm px-xs"><span className="font-caption text-caption px-sm py-[2px] bg-error-container text-on-error-container rounded-full">Under Meds</span></td></tr><tr className="hover:bg-surface-container-low transition-colors"><td className="font-body-md text-body-md py-sm px-xs">Asthma</td><td className="font-body-md text-body-md py-sm px-xs font-semibold">0</td><td className="py-sm px-xs"><span className="font-caption text-caption px-sm py-[2px] bg-surface-variant text-on-surface-variant rounded-full">None</span></td></tr></tbody></table></div></div></div></main>
    </div>
  )
}
