export default function HouseholdDetailsPhcAdmin() {
  return (
    <>
<header className="bg-surface-container-lowest border-b border-outline-variant px-lg h-[72px] flex items-center justify-between sticky top-0 z-50"><div className="flex items-center gap-md"><button aria-label="Back to Households" className="flex items-center gap-sm text-primary hover:bg-surface-container-low px-sm py-xs rounded-lg transition-colors"><span className="material-symbols-outlined text-[20px]">arrow_back</span><span className="font-label-md text-label-md hidden sm:inline">Back to Households</span></button><div className="h-6 w-px bg-outline-variant mx-sm"></div><div><h1 className="font-headline-lg-mobile md:font-headline-lg text-headline-lg-mobile md:text-headline-lg text-on-surface flex items-center gap-sm">
                    Household Details
                    <span className="bg-surface-container text-on-surface-variant font-label-md text-label-md px-sm py-[2px] rounded-full border border-outline-variant">HHID: 10452-A</span></h1></div></div><div className="flex items-center gap-md"><button className="flex items-center gap-sm border border-outline hover:bg-surface-container-low text-primary font-label-md text-label-md h-touch-target px-md rounded-xl transition-colors"><span className="material-symbols-outlined text-[20px]">edit</span><span className="hidden md:inline">Edit Details</span></button><button className="flex items-center gap-sm bg-primary text-on-primary hover:opacity-90 font-label-md text-label-md h-touch-target px-md rounded-xl transition-colors shadow-sm"><span className="material-symbols-outlined text-[20px]">add_box</span><span>Log Visit</span></button></div></header>
<main className="flex-1 w-full max-w-[1440px] mx-auto p-lg md:p-xl space-y-xl">
<section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-md">
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md flex flex-col gap-sm shadow-[0_2px_4px_rgba(0,0,0,0.02)]"><div className="flex items-center gap-sm text-on-surface-variant"><span className="material-symbols-outlined text-[20px] text-tertiary">home</span><h2 className="font-label-md text-label-md uppercase tracking-wider">Address Location</h2></div><div className="font-body-lg text-body-lg text-on-surface mt-auto">
                    Village Rampur, Ward 3<br />
                    House 42, Block C
                </div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md flex flex-col gap-sm shadow-[0_2px_4px_rgba(0,0,0,0.02)]"><div className="flex items-center gap-sm text-on-surface-variant"><span className="material-symbols-outlined text-[20px] text-primary">group</span><h2 className="font-label-md text-label-md uppercase tracking-wider">Total Members</h2></div><div className="flex items-baseline gap-sm mt-auto"><span className="font-display-lg text-display-lg text-on-surface">6</span><span className="font-caption text-caption text-on-surface-variant">Registered</span></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md flex flex-col gap-sm shadow-[0_2px_4px_rgba(0,0,0,0.02)]"><div className="flex items-center gap-sm text-on-surface-variant"><span className="material-symbols-outlined text-[20px] text-secondary">payments</span><h2 className="font-label-md text-label-md uppercase tracking-wider">Primary Income</h2></div><div className="font-body-lg text-body-lg text-on-surface mt-auto">
                    Agriculture / Farming
                </div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md flex flex-col gap-sm shadow-[0_2px_4px_rgba(0,0,0,0.02)] relative overflow-hidden"><div className="absolute right-0 top-0 w-16 h-16 bg-primary-container/10 rounded-bl-full z-0"></div><div className="flex items-center gap-sm text-on-surface-variant relative z-10"><span className="material-symbols-outlined text-[20px] text-primary">medical_services</span><h2 className="font-label-md text-label-md uppercase tracking-wider">Assigned ASHA</h2></div><div className="flex items-center gap-md mt-auto relative z-10"><div className="w-10 h-10 rounded-full bg-primary-fixed flex items-center justify-center text-on-primary-fixed font-headline-md text-headline-md">
                        SD
                    </div><div><div className="font-body-md text-body-md font-semibold">Sunita Devi</div><div className="font-caption text-caption text-on-surface-variant">ID: AW-4092</div></div></div></div></section>
<section className="border-b border-outline-variant"><nav aria-label="Tabs" className="flex gap-lg overflow-x-auto custom-scrollbar"><button className="tab-button font-label-md text-label-md text-primary border-b-2 border-primary pb-sm whitespace-nowrap" data-target="tab-members">
                    Members (6)
                </button><button className="tab-button font-label-md text-label-md text-on-surface-variant hover:text-on-surface border-b-2 border-transparent hover:border-outline-variant pb-sm whitespace-nowrap transition-colors" data-target="tab-visits">
                    Visit History
                </button><button className="tab-button font-label-md text-label-md text-on-surface-variant hover:text-on-surface border-b-2 border-transparent hover:border-outline-variant pb-sm whitespace-nowrap transition-colors flex items-center gap-xs" data-target="tab-followups">
                    Pending Follow-ups
                    <span className="bg-error-container text-on-error-container text-[10px] font-bold px-xs rounded-sm">2</span></button><button className="tab-button font-label-md text-label-md text-on-surface-variant hover:text-on-surface border-b-2 border-transparent hover:border-outline-variant pb-sm whitespace-nowrap transition-colors" data-target="tab-survey">
                    Health Survey Summary
                </button></nav></section>
<section className="bg-surface-container-lowest border border-outline-variant rounded-xl shadow-[0_2px_4px_rgba(0,0,0,0.02)] overflow-hidden min-h-[400px]">
<div className="tab-content active w-full overflow-x-auto custom-scrollbar" id="tab-members"><table className="w-full text-left border-collapse"><thead className="bg-surface-container-low border-b border-outline-variant"><tr><th className="py-sm px-md font-label-md text-label-md text-on-surface-variant font-medium">Name</th><th className="py-sm px-md font-label-md text-label-md text-on-surface-variant font-medium">Age</th><th className="py-sm px-md font-label-md text-label-md text-on-surface-variant font-medium">Gender</th><th className="py-sm px-md font-label-md text-label-md text-on-surface-variant font-medium">Health Status</th><th className="py-sm px-md font-label-md text-label-md text-on-surface-variant font-medium text-right">Actions</th></tr></thead><tbody className="divide-y divide-outline-variant">
<tr className="hover:bg-surface-container-lowest transition-colors group relative">
<td className="absolute left-0 top-0 bottom-0 w-1 bg-error"></td><td className="py-sm px-md h-[48px]"><div className="font-body-md text-body-md text-on-surface font-medium pl-xs">Ram Prasad</div><div className="font-caption text-caption text-on-surface-variant pl-xs">Head of Household</div></td><td className="py-sm px-md font-body-md text-body-md">65</td><td className="py-sm px-md font-body-md text-body-md">Male</td><td className="py-sm px-md"><span className="inline-flex items-center gap-xs px-sm py-[2px] rounded-full bg-error-container text-on-error-container font-caption text-caption font-semibold"><span className="material-symbols-outlined text-[14px]">warning</span>
                                    Hypertension
                                </span></td><td className="py-sm px-md text-right"><button aria-label="View Details" className="text-primary hover:text-primary-container p-xs rounded hover:bg-surface-container-low transition-colors"><span className="material-symbols-outlined text-[20px]">chevron_right</span></button></td></tr>
<tr className="hover:bg-surface-container-lowest transition-colors relative"><td className="absolute left-0 top-0 bottom-0 w-1 bg-secondary"></td><td className="py-sm px-md h-[48px]"><div className="font-body-md text-body-md text-on-surface font-medium pl-xs">Sita Devi</div><div className="font-caption text-caption text-on-surface-variant pl-xs">Spouse</div></td><td className="py-sm px-md font-body-md text-body-md">60</td><td className="py-sm px-md font-body-md text-body-md">Female</td><td className="py-sm px-md"><span className="inline-flex items-center gap-xs px-sm py-[2px] rounded-full bg-secondary-container text-on-secondary-container font-caption text-caption font-semibold"><span className="material-symbols-outlined text-[14px]">check_circle</span>
                                    Healthy
                                </span></td><td className="py-sm px-md text-right"><button aria-label="View Details" className="text-primary hover:text-primary-container p-xs rounded hover:bg-surface-container-low transition-colors"><span className="material-symbols-outlined text-[20px]">chevron_right</span></button></td></tr>
<tr className="hover:bg-surface-container-lowest transition-colors relative"><td className="absolute left-0 top-0 bottom-0 w-1 bg-tertiary"></td><td className="py-sm px-md h-[48px]"><div className="font-body-md text-body-md text-on-surface font-medium pl-xs">Priya Kumari</div><div className="font-caption text-caption text-on-surface-variant pl-xs">Daughter-in-law</div></td><td className="py-sm px-md font-body-md text-body-md">24</td><td className="py-sm px-md font-body-md text-body-md">Female</td><td className="py-sm px-md"><span className="inline-flex items-center gap-xs px-sm py-[2px] rounded-full bg-tertiary-container text-on-tertiary-container font-caption text-caption font-semibold"><span className="material-symbols-outlined text-[14px]">pregnant_woman</span>
                                    ANC - Trimester 2
                                </span></td><td className="py-sm px-md text-right"><button aria-label="View Details" className="text-primary hover:text-primary-container p-xs rounded hover:bg-surface-container-low transition-colors"><span className="material-symbols-outlined text-[20px]">chevron_right</span></button></td></tr></tbody></table></div>
<div className="tab-content p-lg" id="tab-visits"><div className="text-center py-xl text-on-surface-variant"><span className="material-symbols-outlined text-[48px] opacity-50 mb-sm">history</span><p className="font-body-lg text-body-lg">Visit history timeline will appear here.</p></div></div>
<div className="tab-content p-lg" id="tab-followups"><div className="text-center py-xl text-on-surface-variant"><span className="material-symbols-outlined text-[48px] opacity-50 mb-sm">event_upcoming</span><p className="font-body-lg text-body-lg">Pending tasks and referrals will appear here.</p></div></div>
<div className="tab-content p-lg" id="tab-survey"><div className="text-center py-xl text-on-surface-variant"><span className="material-symbols-outlined text-[48px] opacity-50 mb-sm">fact_check</span><p className="font-body-lg text-body-lg">Survey data visualizations will appear here.</p></div></div></section></main>
    </>
  )
}
