import { Link } from 'react-router-dom'
import { LogoutButton } from '@/components/common/LogoutButton'
export default function NewHealthCheckUpPhcAdmin() {
  return (
    <>
<nav className="bg-surface-container-lowest dark:bg-inverse-surface shadow-sm w-full top-0 sticky flex justify-between items-center px-lg py-sm z-40 fixed md:hidden"><div className="flex items-center gap-md"><span className="font-headline-md text-headline-md font-bold text-primary dark:text-primary-fixed">PHC Admin Portal</span></div><div className="flex items-center gap-sm"><span className="material-symbols-outlined text-primary dark:text-primary-fixed cursor-pointer active:opacity-80 hover:bg-surface-container dark:hover:bg-surface-variant transition-colors p-sm rounded-full" data-icon="sync">sync</span><span className="material-symbols-outlined text-primary dark:text-primary-fixed cursor-pointer active:opacity-80 hover:bg-surface-container dark:hover:bg-surface-variant transition-colors p-sm rounded-full" data-icon="notifications">notifications</span><span className="material-symbols-outlined text-primary dark:text-primary-fixed cursor-pointer active:opacity-80 hover:bg-surface-container dark:hover:bg-surface-variant transition-colors p-sm rounded-full" data-icon="help">help</span><img className="w-8 h-8 rounded-full ml-sm object-cover bg-surface-variant" data-alt="A small circular profile picture placeholder for an administrator in a healthcare portal setting." src="https://lh3.googleusercontent.com/aida-public/AB6AXuB7IkMmdTZz2HsN_2Eqh8TGnllV1nOx9NAVsp82ZVE1ea6rc6hMmhVSIvPPW_OdA1lfAzole9BiytfufmE2_yDknaea6TETfIXC6-mRCshmyADwGW4_0gw6NwS8K5cyPDkNZcdlYv1dcG9rsX_hxSMeMML84c40--fqSk0mut5O9bUMqFkePq22YpEU3639CQWKWRLEJgvE955b9yhR0S6yOvDc6LDCwBnlrluPTxn4MBbMZQctUTM4aQ" /></div></nav>
<aside className="hidden md:flex flex-col h-full border-r border-outline-variant dark:border-outline bg-surface-container-low dark:bg-surface-dim w-64 fixed left-0 top-0 z-30"><div className="p-lg flex items-center gap-md border-b border-outline-variant/30"><img className="w-10 h-10 rounded-DEFAULT object-cover bg-surface-variant" data-alt="PHC Logo placeholder, a clean minimalist icon representing a rural health network." src="https://lh3.googleusercontent.com/aida-public/AB6AXuDDfJBnZoJCsm35oIdVWaM0N5E0_VyLjrnNUW58p3Kracy0JSDuo0ozr4qFDsR0CmJBjopp1ub_UCPKP6ca8G71NlAoCX4Rlhs-wuqM82ELUL_ygphAEu4Slu9480TmWCLjmxjFhYsE9oJMG6iqVCLCMvYo_oK7oPyC406eOM-uTaWJvmWgL0D4NoWkmlgnyGtokI0WNYRJDM5sL7WcztLGh6wUWGM0O-ll0YulD0xAWbFyxz9PCF_eTw" /><div><h1 className="font-headline-md text-headline-md font-extrabold text-primary dark:text-primary-fixed leading-tight">PHC Administration</h1><p className="font-caption text-caption text-on-surface-variant">Rural Health Network</p></div></div><nav className="flex-1 overflow-y-auto py-md space-y-xs px-sm"><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="dashboard">dashboard</span>
                Dashboard
            </Link><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/ashas"><span className="material-symbols-outlined" data-icon="groups">groups</span>
                Workers
            </Link><Link className="flex items-center gap-md px-md py-sm rounded-lg text-primary dark:text-primary-fixed font-bold border-r-4 border-primary dark:border-primary-fixed bg-surface-container-high dark:bg-surface-container-highest transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/beneficiaries"><span className="material-symbols-outlined" data-icon="person">person</span>
                Beneficiaries
            </Link><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/households"><span className="material-symbols-outlined" data-icon="home_health">home_health</span>
                Households
            </Link><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/maternal"><span className="material-symbols-outlined" data-icon="pregnant_woman">pregnant_woman</span>
                Maternal Health
            </Link><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/children"><span className="material-symbols-outlined" data-icon="child_care">child_care</span>
                Child Health
            </Link><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/vaccination"><span className="material-symbols-outlined" data-icon="inventory_2">inventory_2</span>
                Inventory
            </Link></nav><div className="p-md border-t border-outline-variant/30 space-y-sm"><button className="w-full bg-primary-container text-on-primary font-label-md text-label-md py-sm rounded-full flex items-center justify-center gap-sm hover:opacity-90 transition-opacity"><span className="material-symbols-outlined text-[18px]">add</span> Generate Report
            </button><div className="flex justify-between px-xs pt-sm"><a className="text-on-surface-variant hover:text-primary transition-colors flex flex-col items-center gap-xs" href="#"><span className="material-symbols-outlined" data-icon="settings">settings</span><span className="font-caption text-caption">Settings</span></a><LogoutButton className="className='text-on-surface-variant hover:text-primary transition-colors flex flex-col items-center gap-xs'"><span className="material-symbols-outlined" data-icon="logout">logout</span><span className="font-caption text-caption">Logout</span></LogoutButton></div></div></aside>
<main className="flex-1 md:ml-64 mt-[64px] md:mt-0 overflow-y-auto bg-background p-lg lg:p-xl flex flex-col gap-lg"><header className="flex justify-between items-end border-b border-outline-variant pb-md"><div><h2 className="font-headline-lg text-headline-lg text-on-background">New Health Check-up</h2><p className="font-body-md text-body-md text-on-surface-variant mt-xs">Record clinical visit details for existing beneficiary.</p></div><div className="hidden sm:flex items-center gap-sm bg-surface-container-low px-md py-xs rounded-full border border-outline-variant"><div className="w-2 h-2 rounded-full bg-secondary-fixed"></div><span className="font-label-md text-label-md text-on-surface-variant">System Online</span></div></header><form className="space-y-xl max-w-4xl w-full">
<section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg shadow-sm flex flex-col sm:flex-row gap-lg items-start relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-2 bg-secondary-fixed"></div>
<div className="flex-shrink-0"><img className="w-24 h-24 rounded-full object-cover border border-outline-variant bg-surface-variant" data-alt="A portrait placeholder for a patient profile in a healthcare system, neutral gray background." src="https://lh3.googleusercontent.com/aida-public/AB6AXuCP87J656SJvoWmOLrRR5ihcSQU2yFwWBH3QbZx2BE0L_-tPNTGQGZYWHg9u1k_7Mx9VaJ6JjrKxCeGSBqAhAmm0INeVMp1KHAIR9-UZJoRCZy9xLP4_v5lwtOn3yEgXiNevz0AppMg0cE-zUr2AuIQEkPyPxHvWMbYOwEGcO2SzUDIzmMMByZMXKqeTWFXwOyYecAnZB_TapgH1-bKW89_Nfrksou7zwGUWKU9sXZuqb6wz9QeOf9IvQ" /></div><div className="flex-1 grid grid-cols-1 sm:grid-cols-2 gap-form-gap w-full"><div><label className="font-caption text-caption text-on-surface-variant uppercase tracking-wider block mb-xs">Patient Name</label><div className="font-body-md text-body-md font-semibold text-on-surface">Sunita Devi</div></div><div><label className="font-caption text-caption text-on-surface-variant uppercase tracking-wider block mb-xs">Beneficiary ID</label><div className="font-body-md text-body-md text-on-surface">BEN-8924-M</div></div><div><label className="font-caption text-caption text-on-surface-variant uppercase tracking-wider block mb-xs">Age / Gender</label><div className="font-body-md text-body-md text-on-surface">34 Y / Female</div></div><div><label className="font-caption text-caption text-on-surface-variant uppercase tracking-wider block mb-xs">Village</label><div className="font-body-md text-body-md text-on-surface">Rampur, Block A</div></div></div></section>
<div className="grid grid-cols-1 lg:grid-cols-2 gap-lg">
<section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg shadow-sm"><h3 className="font-headline-md text-headline-md text-primary mb-md border-b border-outline-variant pb-sm flex items-center gap-sm"><span className="material-symbols-outlined">monitor_heart</span> Vitals
                    </h3><div className="grid grid-cols-2 gap-form-gap"><div className="space-y-sm"><label className="font-label-md text-label-md text-on-surface-variant block">Blood Pressure</label><div className="flex items-center border border-outline-variant rounded-DEFAULT focus-within:border-primary overflow-hidden h-[48px]"><input className="w-full border-none focus:ring-0 px-md py-sm font-body-md text-body-md bg-transparent" placeholder="120/80" type="text" /><span className="px-md bg-surface-container text-on-surface-variant font-caption text-caption border-l border-outline-variant h-full flex items-center">mmHg</span></div></div><div className="space-y-sm"><label className="font-label-md text-label-md text-on-surface-variant block">Pulse</label><div className="flex items-center border border-outline-variant rounded-DEFAULT focus-within:border-primary overflow-hidden h-[48px]"><input className="w-full border-none focus:ring-0 px-md py-sm font-body-md text-body-md bg-transparent" placeholder="72" type="number" /><span className="px-md bg-surface-container text-on-surface-variant font-caption text-caption border-l border-outline-variant h-full flex items-center">bpm</span></div></div><div className="space-y-sm"><label className="font-label-md text-label-md text-on-surface-variant block">Temperature</label><div className="flex items-center border border-outline-variant rounded-DEFAULT focus-within:border-primary overflow-hidden h-[48px]"><input className="w-full border-none focus:ring-0 px-md py-sm font-body-md text-body-md bg-transparent" placeholder="98.6" step="0.1" type="number" /><span className="px-md bg-surface-container text-on-surface-variant font-caption text-caption border-l border-outline-variant h-full flex items-center">°F</span></div></div><div className="space-y-sm"><label className="font-label-md text-label-md text-on-surface-variant block">SpO2</label><div className="flex items-center border border-outline-variant rounded-DEFAULT focus-within:border-primary overflow-hidden h-[48px]"><input className="w-full border-none focus:ring-0 px-md py-sm font-body-md text-body-md bg-transparent" placeholder="98" type="number" /><span className="px-md bg-surface-container text-on-surface-variant font-caption text-caption border-l border-outline-variant h-full flex items-center">%</span></div></div><div className="space-y-sm col-span-2 sm:col-span-1"><label className="font-label-md text-label-md text-on-surface-variant block">Weight</label><div className="flex items-center border border-outline-variant rounded-DEFAULT focus-within:border-primary overflow-hidden h-[48px]"><input className="w-full border-none focus:ring-0 px-md py-sm font-body-md text-body-md bg-transparent" placeholder="65.5" step="0.1" type="number" /><span className="px-md bg-surface-container text-on-surface-variant font-caption text-caption border-l border-outline-variant h-full flex items-center">kg</span></div></div></div></section>
<section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg shadow-sm flex flex-col gap-md justify-between"><div><h3 className="font-headline-md text-headline-md text-primary mb-md border-b border-outline-variant pb-sm flex items-center gap-sm"><span className="material-symbols-outlined">assignment_turned_in</span> Assessment
                        </h3><div className="space-y-md"><div className="space-y-sm"><label className="font-label-md text-label-md text-on-surface-variant block">Risk Status</label><select className="w-full border border-outline-variant rounded-DEFAULT focus:ring-primary focus:border-primary px-md py-sm font-body-md text-body-md bg-transparent h-[48px]"><option disabled selected value="">Select Risk Level...</option><option value="low">Low (Routine)</option><option value="medium">Medium (Monitor)</option><option value="high">High (Action Required)</option><option value="urgent">Urgent (Refer immediately)</option></select></div><div className="space-y-sm"><label className="font-label-md text-label-md text-on-surface-variant block">Recommended Action</label><select className="w-full border border-outline-variant rounded-DEFAULT focus:ring-primary focus:border-primary px-md py-sm font-body-md text-body-md bg-transparent h-[48px]"><option disabled selected value="">Select Action...</option><option value="home_care">Home Care / Advice Given</option><option value="prescribe">Prescribe Medicine</option><option value="refer">Refer to Specialist / District Hospital</option><option value="investigate">Order Lab Tests</option></select></div></div></div></section></div>
<section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg shadow-sm"><h3 className="font-headline-md text-headline-md text-primary mb-md border-b border-outline-variant pb-sm flex items-center gap-sm"><span className="material-symbols-outlined">stethoscope</span> Symptoms & Observations
                </h3><div className="space-y-lg"><div><label className="font-label-md text-label-md text-on-surface-variant block mb-sm">Reported Symptoms</label><div className="flex flex-wrap gap-sm"><label className="inline-flex items-center gap-sm px-md py-sm border border-outline-variant rounded-full cursor-pointer hover:bg-surface-container transition-colors has-[:checked]:bg-primary-container has-[:checked]:text-on-primary has-[:checked]:border-primary-container"><input className="sr-only" type="checkbox" /><span className="font-body-md text-body-md">Fever</span></label><label className="inline-flex items-center gap-sm px-md py-sm border border-outline-variant rounded-full cursor-pointer hover:bg-surface-container transition-colors has-[:checked]:bg-primary-container has-[:checked]:text-on-primary has-[:checked]:border-primary-container"><input className="sr-only" type="checkbox" /><span className="font-body-md text-body-md">Cough</span></label><label className="inline-flex items-center gap-sm px-md py-sm border border-outline-variant rounded-full cursor-pointer hover:bg-surface-container transition-colors has-[:checked]:bg-primary-container has-[:checked]:text-on-primary has-[:checked]:border-primary-container"><input className="sr-only" type="checkbox" /><span className="font-body-md text-body-md">Headache</span></label><label className="inline-flex items-center gap-sm px-md py-sm border border-outline-variant rounded-full cursor-pointer hover:bg-surface-container transition-colors has-[:checked]:bg-primary-container has-[:checked]:text-on-primary has-[:checked]:border-primary-container"><input className="sr-only" type="checkbox" /><span className="font-body-md text-body-md">Body Ache</span></label><label className="inline-flex items-center gap-sm px-md py-sm border border-outline-variant rounded-full cursor-pointer hover:bg-surface-container transition-colors has-[:checked]:bg-primary-container has-[:checked]:text-on-primary has-[:checked]:border-primary-container"><input className="sr-only" type="checkbox" /><span className="font-body-md text-body-md">Nausea</span></label><label className="inline-flex items-center gap-sm px-md py-sm border border-outline-variant rounded-full cursor-pointer hover:bg-surface-container transition-colors has-[:checked]:bg-primary-container has-[:checked]:text-on-primary has-[:checked]:border-primary-container"><input className="sr-only" type="checkbox" /><span className="font-body-md text-body-md">Weakness</span></label></div></div><div className="space-y-sm"><label className="font-label-md text-label-md text-on-surface-variant block">Clinical Observations (Free Text)</label><textarea className="w-full border border-outline-variant rounded-DEFAULT focus:ring-primary focus:border-primary px-md py-sm font-body-md text-body-md bg-transparent resize-y" placeholder="Enter detailed clinical notes here..." rows={4}></textarea></div></div></section>
<section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg shadow-sm"><h3 className="font-headline-md text-headline-md text-primary mb-md border-b border-outline-variant pb-sm flex items-center gap-sm"><span className="material-symbols-outlined">event_upcoming</span> Next Steps
                </h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-form-gap"><div className="space-y-sm"><label className="font-label-md text-label-md text-on-surface-variant block">Follow-up Date</label><input className="w-full border border-outline-variant rounded-DEFAULT focus:ring-primary focus:border-primary px-md py-sm font-body-md text-body-md bg-transparent h-[48px] text-on-surface" type="date" /></div><div className="space-y-sm"><label className="font-label-md text-label-md text-on-surface-variant block">Next Check-up Purpose</label><input className="w-full border border-outline-variant rounded-DEFAULT focus:ring-primary focus:border-primary px-md py-sm font-body-md text-body-md bg-transparent h-[48px]" placeholder="e.g., Routine review, check test results..." type="text" /></div></div></section>
<div className="flex flex-col-reverse sm:flex-row justify-end gap-md pt-md pb-xl"><button className="px-xl py-sm min-h-[48px] border border-primary text-primary font-label-md text-label-md rounded-full hover:bg-surface-container transition-colors" type="button">
                    Cancel
                </button><button className="px-xl py-sm min-h-[48px] bg-primary-container text-on-primary font-label-md text-label-md rounded-full hover:opacity-90 transition-opacity flex items-center justify-center gap-sm shadow-sm" type="submit"><span className="material-symbols-outlined">save</span> Save Record
                </button></div></form></main>
    </>
  )
}
