import { Link } from 'react-router-dom'
import { LogoutButton } from '@/components/common/LogoutButton'
export default function PregnancyDetailsPhcAdmin() {
  return (
    <>
<nav className="hidden md:flex flex-col h-screen w-64 left-0 top-0 border-r border-outline-variant p-md bg-surface-container-low dark:bg-inverse-surface z-50 fixed"><div className="flex items-center mb-xl"><span className="font-headline-sm text-headline-sm font-bold text-on-surface">PHC Admin Portal</span><p className="text-caption font-caption text-on-surface-variant block w-full mt-1">Regional Health Center</p></div><ul className="flex flex-col gap-sm flex-1"><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-variant dark:hover:bg-on-surface-variant/10 transition-all duration-200 ease-in-out font-label-md text-label-md h-[48px]" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="dashboard">dashboard</span>
                    Overview
                </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg bg-primary-container dark:bg-primary text-on-primary-container dark:text-on-primary transition-all duration-200 ease-in-out font-label-md text-label-md h-[48px]" to="/phc/maternal/pregnant"><span className="material-symbols-outlined" data-icon="groups">groups</span>
                    Women Directory
                </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-variant dark:hover:bg-on-surface-variant/10 transition-all duration-200 ease-in-out font-label-md text-label-md h-[48px]" to="/phc/alerts/critical"><span className="material-symbols-outlined" data-icon="error">error</span>
                    High Risk Cases
                </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-variant dark:hover:bg-on-surface-variant/10 transition-all duration-200 ease-in-out font-label-md text-label-md h-[48px]" to="/phc/referrals"><span className="material-symbols-outlined" data-icon="moving">moving</span>
                    Referrals
                </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-variant dark:hover:bg-on-surface-variant/10 transition-all duration-200 ease-in-out font-label-md text-label-md h-[48px]" to="/phc/reports/maternal"><span className="material-symbols-outlined" data-icon="assessment">assessment</span>
                    Reports
                </Link></li></ul><div className="mt-auto pt-lg border-t border-outline-variant"><button className="w-full flex items-center justify-center gap-sm bg-error text-on-error py-sm rounded-full font-label-md text-label-md hover:opacity-90 transition-opacity h-[48px] mb-lg"><span className="material-symbols-outlined" data-icon="warning">warning</span>
                Emergency Referral
            </button><ul className="flex flex-col gap-sm"><li><a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-variant dark:hover:bg-on-surface-variant/10 transition-all duration-200 ease-in-out font-label-md text-label-md h-[48px]" href="#"><span className="material-symbols-outlined" data-icon="help">help</span>
                        Help Center
                    </a></li><li><LogoutButton className="className='flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant dark:text-outline-variant hover:bg-surface-variant dark:hover:bg-on-surface-variant/10 transition-all duration-200 ease-in-out font-label-md text-label-md h-[48px]'"><span className="material-symbols-outlined" data-icon="logout">logout</span>
                        Logout
                    </LogoutButton></li></ul></div></nav>
<main className="flex-1 md:ml-64 bg-background min-h-screen">
<header className="md:hidden flex justify-between items-center w-full px-lg py-sm max-w-[1440px] mx-auto bg-surface dark:bg-inverse-surface shadow-sm sticky top-0 z-40 bg-surface-container-low dark:bg-inverse-surface"><span className="text-headline-md font-headline-md font-bold text-primary dark:text-primary-fixed-dim">MaternalCare PHC</span><div className="flex items-center gap-sm"><span className="material-symbols-outlined cursor-pointer active:opacity-80 text-on-surface-variant dark:text-outline-variant" data-icon="menu">menu</span></div></header><div className="max-w-[1440px] mx-auto p-lg md:p-xl space-y-xl">
<div className="flex items-center gap-sm text-on-surface-variant"><span className="material-symbols-outlined cursor-pointer hover:text-primary transition-colors" data-icon="arrow_back">arrow_back</span><span className="font-label-md text-label-md">Back to Directory</span></div>
<div className="bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm p-lg flex flex-col md:flex-row justify-between items-start md:items-center gap-lg"><div className="flex items-center gap-lg"><div className="w-24 h-24 rounded-full bg-surface-variant flex items-center justify-center overflow-hidden border border-outline-variant"><img className="object-cover w-full h-full" data-alt="A professional portrait of a young Indian woman in a rural setting, looking calm and expectant. Natural soft lighting, high-contrast crisp photography suitable for a medical profile picture. Modern light-mode aesthetic." src="https://lh3.googleusercontent.com/aida-public/AB6AXuCBmyXcrJc8fA4pOfphOVKbklZI9yCLn_LiPWWCpvuS5zSaosEIeVL3G3xPdvNhmFj15vd5XopIk2jblvrvaNj4gou68hQoqOE0IEiXj0xyRVXFTTo7CZmfr3503tA2QPxzCjdpSSrsdgp5FXM5XUKM7NBJUFIWEMZclx5UtrLpnx56UJeVvOJHbjJJN6msv1YSivJrw05gggz_tfHFqnZbA-vagSVjQ1L_jZc1qqG-JsB32Xklx6ZU-A" /></div><div><div className="flex items-center gap-md"><h1 className="font-display-lg text-display-lg text-on-surface">Amina Patel</h1><span className="bg-error-container text-on-error-container px-3 py-1 rounded-full font-label-md text-label-md flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]" data-icon="warning">warning</span>
                                High Risk
                            </span></div><div className="flex flex-wrap gap-md mt-sm text-on-surface-variant font-body-md text-body-md"><span className="flex items-center gap-xs"><span className="material-symbols-outlined text-[18px]">id_card</span> ID: P-49201</span><span className="flex items-center gap-xs"><span className="material-symbols-outlined text-[18px]">cake</span> 26 Years</span><span className="flex items-center gap-xs"><span className="material-symbols-outlined text-[18px]">home</span> HH ID: H-9021</span></div></div></div><div className="flex flex-col sm:flex-row gap-md w-full md:w-auto"><button className="border border-primary text-primary px-lg py-sm rounded-full font-label-md text-label-md hover:bg-primary hover:text-on-primary transition-colors h-[48px] flex items-center justify-center gap-xs w-full sm:w-auto"><span className="material-symbols-outlined" data-icon="edit">edit</span>
                        Edit Profile
                    </button><button className="bg-error text-on-error px-lg py-sm rounded-full font-label-md text-label-md hover:opacity-90 transition-opacity h-[48px] flex items-center justify-center gap-xs w-full sm:w-auto shadow-sm"><span className="material-symbols-outlined" data-icon="local_hospital">local_hospital</span>
                        Refer Patient
                    </button></div></div>
<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-md"><div className="bg-surface-container-lowest p-md rounded-lg border border-outline-variant shadow-sm border-l-4 border-l-primary flex flex-col justify-center"><p className="text-caption font-caption text-on-surface-variant mb-xs">Expected Delivery (EDD)</p><p className="font-headline-lg text-headline-lg text-on-surface flex items-center gap-xs"><span className="material-symbols-outlined text-primary" data-icon="calendar_month">calendar_month</span>
                        14 Nov 2024
                    </p></div><div className="bg-surface-container-lowest p-md rounded-lg border border-outline-variant shadow-sm border-l-4 border-l-error flex flex-col justify-center"><p className="text-caption font-caption text-on-surface-variant mb-xs">Gestational Age</p><p className="font-headline-lg text-headline-lg text-error flex items-center gap-xs"><span className="material-symbols-outlined" data-icon="pregnant_woman">pregnant_woman</span>
                        28 Weeks
                    </p></div><div className="bg-surface-container-lowest p-md rounded-lg border border-outline-variant shadow-sm flex flex-col justify-center"><p className="text-caption font-caption text-on-surface-variant mb-xs">Blood Group</p><p className="font-headline-lg text-headline-lg text-on-surface flex items-center gap-xs"><span className="material-symbols-outlined text-tertiary" data-icon="bloodtype">bloodtype</span>
                        O Positive
                    </p></div><div className="bg-surface-container-lowest p-md rounded-lg border border-outline-variant shadow-sm flex flex-col justify-center"><p className="text-caption font-caption text-on-surface-variant mb-xs">Gravida / Para</p><p className="font-headline-lg text-headline-lg text-on-surface flex items-center gap-xs"><span className="material-symbols-outlined text-secondary" data-icon="family_restroom">family_restroom</span>
                        G3 P1 L1 A1
                    </p></div></div>
<div className="bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm overflow-hidden flex flex-col min-h-[500px]">
<div className="flex overflow-x-auto border-b border-outline-variant bg-surface-container-low hide-scrollbar"><button className="px-lg py-md font-label-md text-label-md text-primary border-b-2 border-primary whitespace-nowrap h-[48px] flex items-center gap-xs bg-surface-container-lowest"><span className="material-symbols-outlined text-[18px]" data-icon="vital_signs">vital_signs</span>
                        ANC Check-ups
                    </button><button className="px-lg py-md font-label-md text-label-md text-on-surface-variant hover:bg-surface-variant transition-colors whitespace-nowrap h-[48px] flex items-center gap-xs border-b-2 border-transparent"><span className="material-symbols-outlined text-[18px]" data-icon="warning">warning</span>
                        Risk Factors
                    </button><button className="px-lg py-md font-label-md text-label-md text-on-surface-variant hover:bg-surface-variant transition-colors whitespace-nowrap h-[48px] flex items-center gap-xs border-b-2 border-transparent"><span className="material-symbols-outlined text-[18px]" data-icon="history">history</span>
                        History
                    </button><button className="px-lg py-md font-label-md text-label-md text-on-surface-variant hover:bg-surface-variant transition-colors whitespace-nowrap h-[48px] flex items-center gap-xs border-b-2 border-transparent"><span className="material-symbols-outlined text-[18px]" data-icon="ambulance">ambulance</span>
                        Referrals & Follow-ups
                    </button></div>
<div className="p-lg md:p-xl flex-1 flex flex-col gap-lg bg-surface-container-lowest"><div className="flex justify-between items-center"><h2 className="font-headline-md text-headline-md text-on-surface">Antenatal Care Schedule</h2><button className="text-primary font-label-md text-label-md flex items-center gap-xs hover:opacity-80"><span className="material-symbols-outlined" data-icon="add_circle">add_circle</span>
                            Log New Visit
                        </button></div><div className="relative border-l-2 border-surface-variant ml-sm space-y-xl pb-lg">
<div className="relative pl-lg"><span className="absolute -left-[11px] top-1 w-5 h-5 rounded-full bg-secondary text-on-secondary flex items-center justify-center border-4 border-surface-container-lowest"><span className="material-symbols-outlined text-[12px]" data-icon="check">check</span></span><div className="bg-surface rounded-lg p-md border border-outline-variant"><div className="flex justify-between items-start mb-sm"><div><h3 className="font-label-md text-label-md text-on-surface">ANC 3 - 28 Weeks</h3><p className="text-caption font-caption text-on-surface-variant">12 Aug 2024 • Sub-center Clinic</p></div><span className="bg-secondary-container text-on-secondary-container px-2 py-1 rounded text-caption font-caption">Completed</span></div><div className="grid grid-cols-2 md:grid-cols-4 gap-md mt-md"><div><p className="text-caption text-outline">Blood Pressure</p><p className="font-body-md text-error font-semibold">140/90 <span className="text-caption font-normal">mmHg</span></p></div><div><p className="text-caption text-outline">Weight</p><p className="font-body-md text-on-surface">62 <span className="text-caption">kg</span></p></div><div><p className="text-caption text-outline">Hb Level</p><p className="font-body-md text-error font-semibold">9.5 <span className="text-caption font-normal">g/dL</span></p></div><div><p className="text-caption text-outline">FHR</p><p className="font-body-md text-on-surface">142 <span className="text-caption">bpm</span></p></div></div><div className="mt-md bg-error-container/30 p-sm rounded border border-error-container text-body-md font-body-md"><span className="font-semibold text-on-surface">Notes:</span> Patient complaining of mild headaches. Mild anemia detected. IFA tablets provided. Monitored for PIH.
                                </div></div></div>
<div className="relative pl-lg"><span className="absolute -left-[11px] top-1 w-5 h-5 rounded-full bg-secondary text-on-secondary flex items-center justify-center border-4 border-surface-container-lowest"><span className="material-symbols-outlined text-[12px]" data-icon="check">check</span></span><div className="bg-surface rounded-lg p-md border border-outline-variant opacity-75"><div className="flex justify-between items-start mb-sm"><div><h3 className="font-label-md text-label-md text-on-surface">ANC 2 - 20 Weeks</h3><p className="text-caption font-caption text-on-surface-variant">15 Jun 2024 • Sub-center Clinic</p></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-md mt-sm"><div><p className="text-caption text-outline">Blood Pressure</p><p className="font-body-md text-on-surface">120/80 <span className="text-caption">mmHg</span></p></div><div><p className="text-caption text-outline">Weight</p><p className="font-body-md text-on-surface">58 <span className="text-caption">kg</span></p></div></div></div></div>
<div className="relative pl-lg"><span className="absolute -left-[9px] top-1 w-4 h-4 rounded-full bg-surface-variant border-2 border-outline-variant flex items-center justify-center"></span><div className="bg-surface-container-low rounded-lg p-md border border-dashed border-outline-variant"><div className="flex justify-between items-start"><div><h3 className="font-label-md text-label-md text-on-surface-variant">ANC 4 - 36 Weeks</h3><p className="text-caption font-caption text-on-surface-variant">Scheduled: 10 Oct 2024</p></div><button className="text-primary font-label-md text-label-md flex items-center gap-xs">
                                        Remind ASHA
                                    </button></div></div></div></div></div></div></div></main>
    </>
  )
}
