import { Link } from 'react-router-dom'
import { LogoutButton } from '@/components/common/LogoutButton'
export default function ReferralDirectoryPhcAdmin() {
  return (
    <>
<nav className="hidden md:flex flex-col h-screen w-64 fixed left-0 top-0 z-40 bg-surface-container-low dark:bg-on-background border-r border-outline-variant py-md">
<div className="px-md mb-xl flex items-center gap-sm"><div className="w-10 h-10 rounded-full bg-primary-container flex items-center justify-center shrink-0 overflow-hidden"><img className="w-full h-full object-cover" data-alt="A clean, modern, minimalist vector logo design for a rural healthcare facility, featuring subtle medical cross elements interwoven with leaf motifs, utilizing deep primary blue and vibrant secondary green colors, set against a pristine white background. Professional, trustworthy, and easily identifiable." src="https://lh3.googleusercontent.com/aida-public/AB6AXuAUcbnVX3vnE-KIyftVX_l10LU1GQ1_IUFA5CBJUiEoObQKixFZrnJj900zRkzS5CxWVlJMvd7E5YUlZbahUu7KSRCmftDeCaDrm3LSJ1PqmWJNQhKJ8u_ud-OXun061lU4oa3Fe-I6Yj1cjykzn75KMu7YcHETVyDkV4YuuXDJqkS-tI82ToNv2-RmXqr79kOyoI4vcgUYyjIBcint-A4rXZvFCzZP_6Zds_fGYEeG75vk0Nu0ig46KA" /></div><div><h1 className="font-headline-md text-headline-md font-extrabold text-primary truncate">PHC Admin</h1><p className="font-caption text-caption text-on-surface-variant truncate">District Health Center</p></div></div>
<div className="flex-1 overflow-y-auto flex flex-col gap-xs pr-md">
<Link className="flex items-center gap-md px-md py-sm rounded-r-full text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 group" to="/phc/dashboard"><span className="material-symbols-outlined text-[20px] group-hover:text-primary transition-colors">dashboard</span><span className="font-label-md text-label-md">Dashboard</span></Link>
<Link className="flex items-center gap-md px-md py-sm rounded-r-full text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 group" to="/phc/ashas"><span className="material-symbols-outlined text-[20px] group-hover:text-primary transition-colors">group</span><span className="font-label-md text-label-md">Workers</span></Link>
<Link className="flex items-center gap-md px-md py-sm rounded-r-full text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 group" to="/phc/beneficiaries"><span className="material-symbols-outlined text-[20px] group-hover:text-primary transition-colors">person</span><span className="font-label-md text-label-md">Beneficiaries</span></Link>
<Link className="flex items-center gap-md px-md py-sm rounded-r-full text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 group" to="/phc/households"><span className="material-symbols-outlined text-[20px] group-hover:text-primary transition-colors">home</span><span className="font-label-md text-label-md">Households</span></Link>
<Link className="flex items-center gap-md px-md py-sm rounded-r-full text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 group" to="/phc/maternal"><span className="material-symbols-outlined text-[20px] group-hover:text-primary transition-colors">pregnant_woman</span><span className="font-label-md text-label-md">Maternal Health</span></Link>
<Link className="flex items-center gap-md px-md py-sm rounded-r-full text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 group" to="/phc/children"><span className="material-symbols-outlined text-[20px] group-hover:text-primary transition-colors">child_care</span><span className="font-label-md text-label-md">Child Health</span></Link>
<Link className="flex items-center gap-md px-md py-sm rounded-r-full bg-primary-container text-on-primary-container font-bold active:scale-95 duration-150" to="/phc/referrals"><span className="material-symbols-outlined text-[20px] icon-filled">swap_horiz</span><span className="font-label-md text-label-md">Referrals</span></Link></div>
<div className="mt-auto pt-md border-t border-outline-variant/50 pr-md flex flex-col gap-xs"><a className="flex items-center gap-md px-md py-sm rounded-r-full text-on-surface-variant hover:bg-surface-container-high transition-all active:scale-95 duration-150 group" href="#"><span className="material-symbols-outlined text-[20px] group-hover:text-primary transition-colors">settings</span><span className="font-label-md text-label-md">Settings</span></a><LogoutButton className="className='flex items-center gap-md px-md py-sm rounded-r-full text-on-surface-variant hover:bg-error-container hover:text-on-error-container transition-all active:scale-95 duration-150 group'"><span className="material-symbols-outlined text-[20px]">logout</span><span className="font-label-md text-label-md">Logout</span></LogoutButton></div></nav>
<main className="flex-1 ml-0 md:ml-64 flex flex-col h-screen overflow-hidden bg-background">
<header className="h-16 shrink-0 bg-surface border-b border-outline-variant px-lg flex justify-between items-center z-10 shadow-sm"><div className="flex items-center gap-sm text-on-surface-variant"><span className="material-symbols-outlined text-[18px]">cloud_done</span><span className="font-caption text-caption">All systems operational. Last synced: Just now.</span></div><div className="flex items-center gap-md"><button className="w-10 h-10 rounded-full hover:bg-surface-container-high flex items-center justify-center text-on-surface-variant transition-colors"><span className="material-symbols-outlined">notifications</span></button></div></header>
<div className="flex-1 overflow-y-auto p-md md:p-xl space-y-xl">
<div className="flex flex-col md:flex-row md:items-end justify-between gap-md"><div><h2 className="font-display-lg text-display-lg text-on-surface">Referral Directory</h2><p className="font-body-md text-body-md text-on-surface-variant mt-xs">Manage and track patient transfers across the network.</p></div><button className="h-12 px-lg bg-primary text-on-primary font-label-md text-label-md rounded-full flex items-center justify-center gap-sm hover:bg-primary/90 transition-colors shadow-sm w-full md:w-auto"><span className="material-symbols-outlined text-[20px]">add</span>
                    New Referral
                </button></div>
<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-md">
<div className="bg-surface rounded-xl border border-outline-variant p-md flex flex-col shadow-sm relative overflow-hidden group hover:border-primary/30 transition-colors"><div className="absolute top-0 right-0 w-24 h-24 bg-primary-container rounded-bl-full -mr-8 -mt-8 opacity-20 pointer-events-none"></div><div className="flex justify-between items-start mb-lg"><span className="font-label-md text-label-md text-on-surface-variant">Total Active Referrals</span><div className="w-8 h-8 rounded-full bg-primary-container text-on-primary-container flex items-center justify-center"><span className="material-symbols-outlined text-[18px]">folder_shared</span></div></div><div className="mt-auto"><span className="font-headline-lg text-headline-lg text-on-surface">142</span><span className="font-caption text-caption text-secondary flex items-center gap-xs mt-xs"><span className="material-symbols-outlined text-[14px]">trending_up</span> +12 this week
                        </span></div></div>
<div className="bg-error-container rounded-xl border border-error/20 p-md flex flex-col shadow-sm relative overflow-hidden"><div className="absolute top-0 right-0 w-24 h-24 bg-error rounded-bl-full -mr-8 -mt-8 opacity-10 pointer-events-none"></div><div className="flex justify-between items-start mb-lg"><span className="font-label-md text-label-md text-on-error-container">Emergency Cases</span><div className="w-8 h-8 rounded-full bg-error text-on-error flex items-center justify-center"><span className="material-symbols-outlined text-[18px]">warning</span></div></div><div className="mt-auto"><span className="font-headline-lg text-headline-lg text-on-error-container">14</span><span className="font-caption text-caption text-on-error-container/80 flex items-center gap-xs mt-xs">
                            Requires immediate action
                        </span></div></div>
<div className="bg-surface rounded-xl border border-outline-variant p-md flex flex-col shadow-sm relative overflow-hidden hover:border-tertiary/30 transition-colors"><div className="absolute top-0 right-0 w-24 h-24 bg-tertiary-container rounded-bl-full -mr-8 -mt-8 opacity-10 pointer-events-none"></div><div className="flex justify-between items-start mb-lg"><span className="font-label-md text-label-md text-on-surface-variant">Pending Acceptance</span><div className="w-8 h-8 rounded-full bg-tertiary-container text-on-tertiary-container flex items-center justify-center"><span className="material-symbols-outlined text-[18px]">hourglass_top</span></div></div><div className="mt-auto"><span className="font-headline-lg text-headline-lg text-on-surface">38</span><span className="font-caption text-caption text-on-surface-variant flex items-center gap-xs mt-xs">
                            Awaiting receiving facility
                        </span></div></div>
<div className="bg-secondary-container/30 rounded-xl border border-secondary/20 p-md flex flex-col shadow-sm relative overflow-hidden"><div className="absolute top-0 right-0 w-24 h-24 bg-secondary rounded-bl-full -mr-8 -mt-8 opacity-10 pointer-events-none"></div><div className="flex justify-between items-start mb-lg"><span className="font-label-md text-label-md text-on-secondary-container">Completed Today</span><div className="w-8 h-8 rounded-full bg-secondary-container text-on-secondary-container flex items-center justify-center"><span className="material-symbols-outlined text-[18px]">check_circle</span></div></div><div className="mt-auto"><span className="font-headline-lg text-headline-lg text-on-surface">24</span><span className="font-caption text-caption text-secondary flex items-center gap-xs mt-xs">
                            Successfully closed loop
                        </span></div></div></div>
<div className="flex flex-col gap-md">
<div className="flex flex-col md:flex-row items-center justify-between gap-md bg-surface p-sm rounded-xl border border-outline-variant shadow-sm"><div className="flex flex-wrap items-center gap-sm w-full md:w-auto">
<div className="relative flex-1 md:w-64 min-w-[200px]"><span className="material-symbols-outlined absolute left-sm top-1/2 -translate-y-1/2 text-on-surface-variant text-[20px]">search</span><input className="w-full h-10 pl-10 pr-sm bg-surface-container-low border-none rounded-lg font-body-md text-body-md text-on-surface focus:ring-2 focus:ring-primary placeholder:text-on-surface-variant/60" placeholder="Search patient or ID..." type="text" /></div>
<div className="relative min-w-[140px]"><select className="w-full h-10 pl-sm pr-lg bg-surface-container-low border-none rounded-lg font-label-md text-label-md text-on-surface appearance-none focus:ring-2 focus:ring-primary cursor-pointer"><option value="">All Statuses</option><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="progress">In Progress</option><option value="completed">Completed</option></select><span className="material-symbols-outlined absolute right-sm top-1/2 -translate-y-1/2 text-on-surface-variant pointer-events-none text-[20px]">arrow_drop_down</span></div>
<div className="relative min-w-[140px]"><select className="w-full h-10 pl-sm pr-lg bg-surface-container-low border-none rounded-lg font-label-md text-label-md text-on-surface appearance-none focus:ring-2 focus:ring-primary cursor-pointer"><option value="">All Priorities</option><option value="emergency">Emergency</option><option value="urgent">Urgent</option><option value="routine">Routine</option></select><span className="material-symbols-outlined absolute right-sm top-1/2 -translate-y-1/2 text-on-surface-variant pointer-events-none text-[20px]">arrow_drop_down</span></div></div><div className="flex items-center gap-sm w-full md:w-auto"><button className="h-10 px-md bg-surface-container-high hover:bg-surface-variant rounded-lg font-label-md text-label-md text-on-surface flex items-center gap-xs transition-colors w-full md:w-auto justify-center"><span className="material-symbols-outlined text-[18px]">calendar_today</span>
                            Date Range
                        </button><button className="h-10 w-10 bg-surface-container-high hover:bg-surface-variant rounded-lg text-on-surface flex items-center justify-center transition-colors shrink-0"><span className="material-symbols-outlined text-[20px]">filter_list</span></button></div></div>
<div className="bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden flex flex-col relative"><div className="overflow-x-auto table-scroll w-full"><table className="w-full text-left border-collapse whitespace-nowrap min-w-[1000px]"><thead><tr className="bg-surface-container-lowest border-b border-outline-variant h-10"><th className="px-md py-sm font-label-md text-label-md text-on-surface-variant sticky top-0 bg-surface-container-lowest z-10 w-1"></th>
<th className="px-md py-sm font-label-md text-label-md text-on-surface-variant sticky top-0 bg-surface-container-lowest z-10">Patient Details</th><th className="px-md py-sm font-label-md text-label-md text-on-surface-variant sticky top-0 bg-surface-container-lowest z-10">Referred From</th><th className="px-md py-sm font-label-md text-label-md text-on-surface-variant sticky top-0 bg-surface-container-lowest z-10">Referred To</th><th className="px-md py-sm font-label-md text-label-md text-on-surface-variant sticky top-0 bg-surface-container-lowest z-10">Reason</th><th className="px-md py-sm font-label-md text-label-md text-on-surface-variant sticky top-0 bg-surface-container-lowest z-10">Date</th><th className="px-md py-sm font-label-md text-label-md text-on-surface-variant sticky top-0 bg-surface-container-lowest z-10 text-right">Status</th></tr></thead><tbody className="font-body-md text-body-md text-on-surface">
<tr className="border-b border-outline-variant/50 hover:bg-surface-container-low transition-colors group h-12 cursor-pointer"><td className="px-0 py-0 relative"><div className="absolute left-0 top-0 bottom-0 w-1 bg-error rounded-r-sm"></div></td><td className="px-md py-sm"><div className="flex flex-col"><span className="font-headline-md text-[14px] leading-tight text-on-surface group-hover:text-primary transition-colors">Aarav Sharma</span><span className="font-caption text-caption text-on-surface-variant">ID: PT-8923-M</span></div></td><td className="px-md py-sm">Sub-Center Alpha (ASHA Meena)</td><td className="px-md py-sm font-label-md text-on-surface">District Hospital BLK</td><td className="px-md py-sm truncate max-w-[150px]" title="Severe respiratory distress, suspected pneumonia">Severe respiratory distress...</td><td className="px-md py-sm text-on-surface-variant">Oct 24, 09:15 AM</td><td className="px-md py-sm text-right"><span className="inline-flex items-center justify-center px-2 py-1 rounded-full bg-surface-variant text-on-surface-variant font-label-md text-[12px] uppercase tracking-wide gap-1"><span className="w-1.5 h-1.5 rounded-full bg-outline"></span> Pending
                                        </span></td></tr>
<tr className="border-b border-outline-variant/50 bg-surface-container-lowest hover:bg-surface-container-low transition-colors group h-12 cursor-pointer"><td className="px-0 py-0 relative"><div className="absolute left-0 top-0 bottom-0 w-1 bg-tertiary-container rounded-r-sm"></div></td><td className="px-md py-sm"><div className="flex flex-col"><span className="font-headline-md text-[14px] leading-tight text-on-surface group-hover:text-primary transition-colors">Priya Patel</span><span className="font-caption text-caption text-on-surface-variant">ID: PT-1044-F</span></div></td><td className="px-md py-sm">PHC Sector 4</td><td className="px-md py-sm font-label-md text-on-surface">Maternity Ward, DH</td><td className="px-md py-sm truncate max-w-[150px]" title="High blood pressure, late term pregnancy complications">High blood pressure, late te...</td><td className="px-md py-sm text-on-surface-variant">Oct 24, 08:30 AM</td><td className="px-md py-sm text-right"><span className="inline-flex items-center justify-center px-2 py-1 rounded-full bg-secondary-container text-on-secondary-container font-label-md text-[12px] uppercase tracking-wide gap-1"><span className="w-1.5 h-1.5 rounded-full bg-secondary"></span> Accepted
                                        </span></td></tr>
<tr className="border-b border-outline-variant/50 hover:bg-surface-container-low transition-colors group h-12 cursor-pointer"><td className="px-0 py-0 relative"><div className="absolute left-0 top-0 bottom-0 w-1 bg-secondary rounded-r-sm"></div></td><td className="px-md py-sm"><div className="flex flex-col"><span className="font-headline-md text-[14px] leading-tight text-on-surface group-hover:text-primary transition-colors">Rajesh Kumar</span><span className="font-caption text-caption text-on-surface-variant">ID: PT-5521-M</span></div></td><td className="px-md py-sm">Village Clinic B (ASHA Sunita)</td><td className="px-md py-sm font-label-md text-on-surface">Community Health Center</td><td className="px-md py-sm truncate max-w-[150px]">Diagnostic X-Ray (Chest)</td><td className="px-md py-sm text-on-surface-variant">Oct 23, 14:20 PM</td><td className="px-md py-sm text-right"><span className="inline-flex items-center justify-center px-2 py-1 rounded-full bg-primary-fixed text-on-primary-fixed-variant font-label-md text-[12px] uppercase tracking-wide gap-1"><span className="w-1.5 h-1.5 rounded-full bg-primary"></span> In Progress
                                        </span></td></tr>
<tr className="border-b border-outline-variant/50 bg-surface-container-lowest hover:bg-surface-container-low transition-colors group h-12 cursor-pointer opacity-75"><td className="px-0 py-0 relative"><div className="absolute left-0 top-0 bottom-0 w-1 bg-outline-variant rounded-r-sm"></div></td><td className="px-md py-sm"><div className="flex flex-col"><span className="font-headline-md text-[14px] leading-tight text-on-surface group-hover:text-primary transition-colors">Ananya Singh</span><span className="font-caption text-caption text-on-surface-variant">ID: PT-2289-F</span></div></td><td className="px-md py-sm">Mobile Health Van</td><td className="px-md py-sm font-label-md text-on-surface">PHC Dental Clinic</td><td className="px-md py-sm truncate max-w-[150px]">Routine checkup, tooth extraction</td><td className="px-md py-sm text-on-surface-variant">Oct 23, 10:00 AM</td><td className="px-md py-sm text-right"><span className="inline-flex items-center justify-center px-2 py-1 rounded-full bg-outline-variant/30 text-on-surface-variant font-label-md text-[12px] uppercase tracking-wide gap-1"><span className="material-symbols-outlined text-[14px]">check</span> Completed
                                        </span></td></tr>
<tr className="border-b border-outline-variant/50 hover:bg-surface-container-low transition-colors group h-12 cursor-pointer"><td className="px-0 py-0 relative"><div className="absolute left-0 top-0 bottom-0 w-1 bg-error rounded-r-sm"></div></td><td className="px-md py-sm"><div className="flex flex-col"><span className="font-headline-md text-[14px] leading-tight text-on-surface group-hover:text-primary transition-colors">Vikram Dass</span><span className="font-caption text-caption text-on-surface-variant">ID: PT-9901-M</span></div></td><td className="px-md py-sm">Sub-Center Gamma</td><td className="px-md py-sm font-label-md text-on-surface">Specialty Trauma Center</td><td className="px-md py-sm truncate max-w-[150px]">Blunt force trauma, suspected fracture</td><td className="px-md py-sm text-on-surface-variant">Oct 24, 11:45 AM</td><td className="px-md py-sm text-right"><span className="inline-flex items-center justify-center px-2 py-1 rounded-full bg-secondary-container text-on-secondary-container font-label-md text-[12px] uppercase tracking-wide gap-1"><span className="w-1.5 h-1.5 rounded-full bg-secondary"></span> Accepted
                                        </span></td></tr></tbody></table></div>
<div className="bg-surface-container-lowest border-t border-outline-variant p-sm flex items-center justify-between text-on-surface-variant"><span className="font-caption text-caption pl-sm">Showing 1-5 of 142 records</span><div className="flex items-center gap-xs pr-sm"><button className="w-8 h-8 rounded-full hover:bg-surface-container-high flex items-center justify-center disabled:opacity-50" disabled><span className="material-symbols-outlined text-[18px]">chevron_left</span></button><button className="w-8 h-8 rounded-full bg-primary-container text-on-primary-container font-label-md text-[14px] flex items-center justify-center">1</button><button className="w-8 h-8 rounded-full hover:bg-surface-container-high font-label-md text-[14px] flex items-center justify-center">2</button><button className="w-8 h-8 rounded-full hover:bg-surface-container-high font-label-md text-[14px] flex items-center justify-center">3</button><span className="px-1">...</span><button className="w-8 h-8 rounded-full hover:bg-surface-container-high flex items-center justify-center"><span className="material-symbols-outlined text-[18px]">chevron_right</span></button></div></div></div></div>
<div className="h-xl"></div></div></main>
    </>
  )
}
