import { Link } from 'react-router-dom'
import { LogoutButton } from '@/components/common/LogoutButton'
export default function RiskAnalysisPhcAdmin() {
  return (
    <>
<nav aria-label="Sidebar Navigation" className="hidden md:flex flex-col h-screen w-64 fixed left-0 top-0 border-r border-outline-variant bg-surface-container-low"><div className="p-lg border-b border-outline-variant/30 flex items-center gap-md"><div aria-hidden className="w-10 h-10 rounded-full bg-primary-container text-on-primary-container flex items-center justify-center font-headline-md font-extrabold"><span className="material-symbols-outlined icon-fill">medical_services</span></div><div><div className="font-headline-md text-headline-md font-extrabold text-primary">PHC Administration</div><div className="font-caption text-caption text-on-surface-variant">Rural Health Network</div></div></div><div className="flex-1 overflow-y-auto py-md"><ul className="space-y-unit px-sm"><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="dashboard">dashboard</span>
                        Dashboard
                    </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/ashas"><span className="material-symbols-outlined" data-icon="groups">groups</span>
                        Workers
                    </Link></li><li><Link aria-current="page" className="flex items-center gap-md px-md py-sm rounded-lg text-primary font-bold border-r-4 border-primary bg-surface-container-high transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/beneficiaries"><span className="material-symbols-outlined icon-fill" data-icon="person">person</span>
                        Beneficiaries
                    </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/households"><span className="material-symbols-outlined" data-icon="home_health">home_health</span>
                        Households
                    </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/maternal"><span className="material-symbols-outlined" data-icon="pregnant_woman">pregnant_woman</span>
                        Maternal Health
                    </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/children"><span className="material-symbols-outlined" data-icon="child_care">child_care</span>
                        Child Health
                    </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/vaccination"><span className="material-symbols-outlined" data-icon="inventory_2">inventory_2</span>
                        Inventory
                    </Link></li></ul></div><div className="p-md border-t border-outline-variant/30"><button className="w-full bg-primary-container text-on-primary-container font-label-md text-label-md rounded-full py-md hover:opacity-90 transition-opacity flex items-center justify-center gap-sm min-h-[48px]"><span className="material-symbols-outlined">summarize</span>
                Generate Report
            </button><ul className="mt-md space-y-unit"><li><a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container transition-all duration-200 ease-in-out font-label-md text-label-md" href="#"><span className="material-symbols-outlined" data-icon="settings">settings</span>
                        Settings
                    </a></li><li><LogoutButton className="className='flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container transition-all duration-200 ease-in-out font-label-md text-label-md'"><span className="material-symbols-outlined" data-icon="logout">logout</span>
                        Logout
                    </LogoutButton></li></ul></div></nav>
<main className="flex-1 md:ml-64 flex flex-col min-h-screen">
<header className="w-full top-0 sticky bg-surface-container-lowest shadow-sm z-40 flex justify-between items-center px-lg py-sm h-16 border-b border-outline-variant/20 hidden md:flex"><div className="flex items-center gap-md">
<div className="relative hidden lg:block"><span className="material-symbols-outlined absolute left-sm top-1/2 -translate-y-1/2 text-on-surface-variant">search</span><input className="pl-xl pr-md py-sm rounded-full bg-surface-container-low border-none focus:ring-2 focus:ring-primary text-body-md font-body-md w-64 h-10" placeholder="Search beneficiaries..." type="text" /></div></div><div className="flex items-center gap-md text-primary"><button aria-label="Sync" className="w-10 h-10 rounded-full hover:bg-surface-container flex items-center justify-center transition-colors text-on-surface-variant"><span className="material-symbols-outlined" data-icon="sync">sync</span></button><button aria-label="Notifications" className="w-10 h-10 rounded-full hover:bg-surface-container flex items-center justify-center transition-colors text-on-surface-variant relative"><span className="material-symbols-outlined" data-icon="notifications">notifications</span><span className="absolute top-2 right-2 w-2 h-2 bg-error rounded-full"></span></button><button aria-label="Help" className="w-10 h-10 rounded-full hover:bg-surface-container flex items-center justify-center transition-colors text-on-surface-variant"><span className="material-symbols-outlined" data-icon="help">help</span></button><div className="w-8 h-8 rounded-full bg-primary-container text-on-primary overflow-hidden ml-sm"><img alt="Administrator Profile" className="w-full h-full object-cover" data-alt="A small, professional headshot of an administrative healthcare worker. The lighting is bright and clean, characteristic of a modern office environment. The color palette is neutral with soft white tones, reflecting a high-quality, reliable medical administrative profile picture." src="https://lh3.googleusercontent.com/aida-public/AB6AXuBCQ3kSxFqeCuvvrMJR-WJqXx-J2sOPPX_f5nRsgSJBEKLUn8PocFeLa8TJ4nsiYTLja213S63vviYVx5MGL5lLbOAtNI3x4m5nEmxLa5UMG2DlPvldqHbq9tBiZq-Rdx7tsZgyTysHqme--qxwSif-aITKvzg1mWYg_LDVOVNUT7fIBCKIXy59bvybVeG-0SoNbRTAG46B2guhtQRaD5EurNGBzjs9ruiHBb4FlQUC8AzWBvq4jq78Bw" /></div></div></header>
<div className="flex-1 p-lg bg-surface">
<div className="mb-lg"><div className="flex items-center gap-xs text-on-surface-variant font-caption text-caption mb-sm"><span>Beneficiaries</span><span className="material-symbols-outlined text-[16px]">chevron_right</span><span className="text-primary font-semibold">Sunita Devi</span></div><div className="flex items-center justify-between"><div><h1 className="font-display-lg text-display-lg text-on-surface flex items-center gap-md">
                            Sunita Devi
                            <span className="inline-flex items-center gap-xs px-sm py-xs rounded-full bg-error-container text-on-error-container font-label-md text-label-md border border-error/20"><span className="material-symbols-outlined text-[18px]">warning</span>
                                Risk Indicator: High
                            </span></h1><p className="font-body-md text-body-md text-on-surface-variant mt-xs">ID: PHC-9942-B • Age 36 • 32 Weeks Pregnant</p></div><div className="flex gap-md"><button className="px-md py-sm border border-primary text-primary rounded-lg font-label-md text-label-md hover:bg-primary-container hover:text-on-primary-container transition-colors min-h-[48px]">
                            View Full Record
                        </button><button className="px-md py-sm bg-error text-on-error rounded-lg font-label-md text-label-md hover:opacity-90 transition-opacity shadow-sm flex items-center gap-sm min-h-[48px]"><span className="material-symbols-outlined icon-fill">ambulance</span>
                            Initiate Referral
                        </button></div></div></div>
<div className="grid grid-cols-1 lg:grid-cols-12 gap-lg">
<div className="lg:col-span-8 bg-surface-container-lowest rounded-xl border-l-4 border-l-error border-y border-r border-outline-variant/30 shadow-[0px_2px_4px_rgba(0,0,0,0.05)] overflow-hidden flex flex-col"><div className="p-md border-b border-outline-variant/20 bg-error-container/30 flex items-center justify-between"><h2 className="font-headline-md text-headline-md text-on-error-container flex items-center gap-sm"><span className="material-symbols-outlined icon-fill">analytics</span>
                            AI-Assisted Assessment
                        </h2><span className="font-caption text-caption text-on-surface-variant flex items-center gap-xs"><span className="material-symbols-outlined text-[14px]">update</span>
                            Updated 10 mins ago
                        </span></div><div className="p-lg flex-1 flex flex-col gap-lg">
<div><h3 className="font-label-md text-label-md text-on-surface-variant mb-md uppercase tracking-wider">Important Factors</h3><div className="grid grid-cols-1 md:grid-cols-3 gap-md"><div className="p-md rounded-lg bg-error-container/20 border border-error/10 flex flex-col items-start"><span className="material-symbols-outlined text-error mb-sm">favorite</span><span className="font-body-md text-body-md text-on-surface-variant mb-xs">Blood Pressure</span><span className="font-headline-lg text-headline-lg text-error font-bold">160/100</span></div><div className="p-md rounded-lg bg-surface-container border border-outline-variant/30 flex flex-col items-start"><span className="material-symbols-outlined text-primary mb-sm">history</span><span className="font-body-md text-body-md text-on-surface-variant mb-xs">History</span><span className="font-headline-md text-headline-md text-on-surface">Prev. Complications</span></div><div className="p-md rounded-lg bg-surface-container border border-outline-variant/30 flex flex-col items-start"><span className="material-symbols-outlined text-primary mb-sm">calendar_month</span><span className="font-body-md text-body-md text-on-surface-variant mb-xs">Age Factor</span><span className="font-headline-md text-headline-md text-on-surface">36 Years</span></div></div></div>
<div className="mt-auto p-md rounded-lg bg-surface-dim border border-outline-variant/50"><h3 className="font-label-md text-label-md text-on-surface-variant mb-sm">Recommended Action</h3><div className="flex items-start gap-md"><span className="material-symbols-outlined text-error icon-fill mt-xs">gavel</span><div><p className="font-headline-md text-headline-md text-on-surface font-bold">Immediate Referral to District Hospital</p><p className="font-body-md text-body-md text-on-surface-variant mt-xs">High risk of pre-eclampsia detected. ASHA worker on ground has been notified to prepare for transport.</p></div></div></div></div></div>
<div className="lg:col-span-4 flex flex-col gap-lg">
<div className="bg-surface-container-lowest rounded-xl border border-outline-variant/30 shadow-[0px_2px_4px_rgba(0,0,0,0.05)] p-lg"><div className="flex items-center gap-sm mb-md"><span className="material-symbols-outlined text-error icon-fill">assignment_late</span><h2 className="font-headline-md text-headline-md text-on-surface">Follow-up Priority</h2></div><div className="w-full py-md text-center rounded-lg bg-error text-on-error font-headline-lg text-headline-lg uppercase tracking-wide mb-md">
                            Critical
                        </div><ul className="space-y-sm"><li className="flex items-center justify-between border-b border-outline-variant/20 pb-sm"><span className="font-body-md text-body-md text-on-surface-variant">Assigned Worker</span><span className="font-label-md text-label-md text-on-surface">Kavita (ASHA)</span></li><li className="flex items-center justify-between pt-xs"><span className="font-body-md text-body-md text-on-surface-variant">Last Contact</span><span className="font-label-md text-label-md text-on-surface">Today, 09:30 AM</span></li></ul></div>
<div className="flex-1 bg-surface-container-lowest rounded-xl border border-outline-variant/30 shadow-[0px_2px_4px_rgba(0,0,0,0.05)] p-lg relative overflow-hidden group">
<div className="absolute -right-10 -bottom-10 opacity-5 group-hover:opacity-10 transition-opacity duration-500"><span className="material-symbols-outlined text-[180px]">monitor_heart</span></div><h2 className="font-headline-md text-headline-md text-on-surface mb-md">Vitals Snapshot</h2><div className="space-y-md relative z-10"><div className="flex justify-between items-center"><span className="font-body-md text-body-md text-on-surface-variant">Weight</span><span className="font-label-md text-label-md text-on-surface">68 kg <span className="text-error ml-xs material-symbols-outlined text-[16px] align-middle">trending_up</span></span></div><div className="flex justify-between items-center"><span className="font-body-md text-body-md text-on-surface-variant">Hemoglobin</span><span className="font-label-md text-label-md text-on-surface">10.5 g/dL</span></div><div className="flex justify-between items-center"><span className="font-body-md text-body-md text-on-surface-variant">Fundal Height</span><span className="font-label-md text-label-md text-on-surface">30 cm</span></div></div></div></div></div></div></main>
    </>
  )
}
