export default function HouseholdVisitSurveyAshaSathi() {
  return (
    <>
<header className="fixed top-0 w-full z-50 flex justify-between items-center px-lg h-touch-target bg-surface shadow-sm docked full-width top-0"><div className="flex items-center gap-sm"><button aria-label="Back" className="flex items-center justify-center w-touch-target h-touch-target rounded-full hover:bg-surface-container-highest transition-colors active:scale-95 duration-100 text-on-surface-variant"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>arrow_back</span></button><h1 className="text-headline-lg-mobile font-headline-lg-mobile font-bold text-primary truncate">ASHA Field Care</h1></div><button className="flex items-center justify-center w-touch-target h-touch-target rounded-full hover:bg-surface-container-highest transition-colors active:scale-95 duration-100 text-primary"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>more_vert</span></button></header>
<main className="flex-1 mt-[48px] pb-safe-nav px-sm md:px-lg max-w-[1440px] mx-auto w-full flex flex-col gap-lg pt-lg">
<section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm relative overflow-hidden"><div className="absolute left-0 top-0 bottom-0 w-2 bg-primary"></div><div className="pl-sm"><div className="flex justify-between items-start mb-sm"><div><p className="text-caption font-caption text-on-surface-variant">Household ID</p><h2 className="text-headline-md font-headline-md text-on-surface">HH-2023-8942</h2></div><span className="bg-secondary-container text-on-secondary-container text-caption font-caption px-sm py-xs rounded-full">Active</span></div><div className="flex items-center gap-sm text-body-md font-body-md text-on-surface mt-sm"><span className="material-symbols-outlined text-outline">person</span><span><strong>Head:</strong> Ramesh Kumar</span></div><div className="flex items-center gap-sm text-body-md font-body-md text-on-surface mt-xs"><span className="material-symbols-outlined text-outline">location_on</span><span>Village Block C, Sector 4</span></div></div></section>
<section className="flex flex-col gap-sm"><div className="flex justify-between items-center px-xs"><h3 className="text-headline-md font-headline-md text-on-surface">Family Members</h3><span className="text-caption font-caption bg-surface-container-high text-on-surface px-sm py-xs rounded-full">4 Members</span></div><div className="grid grid-cols-1 md:grid-cols-2 gap-sm">
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex justify-between items-center active:scale-[0.98] transition-transform"><div className="flex items-center gap-md"><div className="w-touch-target h-touch-target rounded-full bg-surface-container-high flex items-center justify-center text-primary"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>face</span></div><div><h4 className="text-body-md font-body-md font-bold text-on-surface">Ramesh Kumar</h4><p className="text-caption font-caption text-on-surface-variant">Male, 45y</p></div></div><button className="w-touch-target h-touch-target rounded-full hover:bg-surface-container-low flex items-center justify-center text-outline"><span className="material-symbols-outlined">chevron_right</span></button></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex justify-between items-center active:scale-[0.98] transition-transform"><div className="flex items-center gap-md"><div className="w-touch-target h-touch-target rounded-full bg-error-container flex items-center justify-center text-on-error-container relative"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>pregnant_woman</span><div className="absolute -top-1 -right-1 w-3 h-3 bg-error rounded-full border-2 border-surface-container-lowest"></div></div><div><h4 className="text-body-md font-body-md font-bold text-on-surface">Sunita Devi</h4><p className="text-caption font-caption text-on-surface-variant">Female, 40y</p></div></div><div className="flex items-center gap-xs"><span className="bg-error-container text-on-error-container text-caption font-caption px-sm py-xs rounded-full">High Risk</span><button className="w-touch-target h-touch-target rounded-full hover:bg-surface-container-low flex items-center justify-center text-outline"><span className="material-symbols-outlined">chevron_right</span></button></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex justify-between items-center active:scale-[0.98] transition-transform"><div className="flex items-center gap-md"><div className="w-touch-target h-touch-target rounded-full bg-secondary-container flex items-center justify-center text-on-secondary-container"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>child_care</span></div><div><h4 className="text-body-md font-body-md font-bold text-on-surface">Amit Kumar</h4><p className="text-caption font-caption text-on-surface-variant">Male, 4y</p></div></div><div className="flex items-center gap-xs"><span className="bg-secondary-container text-on-secondary-container text-caption font-caption px-sm py-xs rounded-full">Immunization Due</span><button className="w-touch-target h-touch-target rounded-full hover:bg-surface-container-low flex items-center justify-center text-outline"><span className="material-symbols-outlined">chevron_right</span></button></div></div></div><button className="mt-sm flex items-center justify-center gap-sm w-full py-md border-2 border-dashed border-primary text-primary rounded-xl font-label-md text-label-md hover:bg-surface-container-low transition-colors h-touch-target"><span className="material-symbols-outlined">person_add</span>
                Add Family Member
            </button></section>
<section className="flex flex-col gap-md mt-sm"><h3 className="text-headline-md font-headline-md text-on-surface px-xs">Household Health Survey</h3><div className="flex flex-col gap-sm">
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex justify-between items-center"><div className="pr-md"><h4 className="text-body-md font-body-md font-bold text-on-surface">Clean water available?</h4><p className="text-caption font-caption text-on-surface-variant mt-xs">Access to safe drinking water within premises.</p></div>
<div className="relative inline-block w-12 h-6 align-middle select-none transition duration-200 ease-in"><input className="toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-4 appearance-none cursor-pointer border-outline-variant checked:border-secondary checked:right-0 transition-all duration-200 z-10" id="toggle1" name="toggle1" type="checkbox" /><label className="toggle-label block overflow-hidden h-6 rounded-full bg-outline-variant cursor-pointer transition-colors duration-200" htmlFor="toggle1"></label></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex justify-between items-center"><div className="pr-md"><h4 className="text-body-md font-body-md font-bold text-on-surface">Functional toilet?</h4><p className="text-caption font-caption text-on-surface-variant mt-xs">Working latrine facility used by family.</p></div><div className="relative inline-block w-12 h-6 align-middle select-none transition duration-200 ease-in"><input checked={false} className="toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-4 appearance-none cursor-pointer border-outline-variant checked:border-secondary checked:right-0 transition-all duration-200 z-10" id="toggle2" name="toggle2" type="checkbox" /><label className="toggle-label block overflow-hidden h-6 rounded-full bg-secondary cursor-pointer transition-colors duration-200" htmlFor="toggle2"></label></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex flex-col gap-md"><div><h4 className="text-body-md font-body-md font-bold text-on-surface">Any recent fever or illness?</h4><p className="text-caption font-caption text-on-surface-variant mt-xs">In the last 14 days among any family member.</p></div><div className="flex gap-md"><label className="flex-1 cursor-pointer"><input className="peer sr-only" name="fever" type="radio" /><div className="w-full text-center py-md rounded-xl border border-outline-variant peer-checked:bg-primary-container peer-checked:text-on-primary-container peer-checked:border-primary peer-checked:font-bold transition-all h-touch-target flex items-center justify-center font-label-md text-label-md text-on-surface-variant">
                                Yes
                            </div></label><label className="flex-1 cursor-pointer"><input checked={false} className="peer sr-only" name="fever" type="radio" /><div className="w-full text-center py-md rounded-xl border border-outline-variant peer-checked:bg-surface-container-high peer-checked:text-on-surface peer-checked:border-outline peer-checked:font-bold transition-all h-touch-target flex items-center justify-center font-label-md text-label-md text-on-surface-variant">
                                No
                            </div></label></div></div></div></section>
<section className="mt-md flex flex-col gap-md"><button className="w-full bg-primary text-on-primary rounded-xl h-touch-target flex items-center justify-center font-label-md text-label-md font-bold shadow-md hover:bg-surface-tint active:scale-95 transition-all"><span className="material-symbols-outlined mr-sm">check_circle</span>
                Complete Visit
            </button></section></main>
<nav className="md:hidden fixed bottom-0 w-full z-50 flex justify-around items-center px-md pb-safe h-[72px] bg-surface border-t border-outline-variant shadow-lg docked full-width bottom-0 rounded-t-xl"><button className="flex flex-col items-center justify-center text-on-surface-variant px-lg py-sm hover:bg-surface-container-low active:scale-90 transition-transform"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>home</span><span className="text-label-md font-label-md mt-xs text-[10px]">Home</span></button><button className="flex flex-col items-center justify-center bg-primary-container text-on-primary-container rounded-full px-lg py-sm active:scale-90 transition-transform"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>group</span><span className="text-label-md font-label-md mt-xs text-[10px]">Households</span></button><button className="flex flex-col items-center justify-center text-on-surface-variant px-lg py-sm hover:bg-surface-container-low active:scale-90 transition-transform"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>person_search</span><span className="text-label-md font-label-md mt-xs text-[10px]">Patients</span></button><button className="flex flex-col items-center justify-center text-on-surface-variant px-lg py-sm hover:bg-surface-container-low active:scale-90 transition-transform"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>assignment</span><span className="text-label-md font-label-md mt-xs text-[10px]">Tasks</span></button><button className="flex flex-col items-center justify-center text-on-surface-variant px-lg py-sm hover:bg-surface-container-low active:scale-90 transition-transform"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>account_circle</span><span className="text-label-md font-label-md mt-xs text-[10px]">Profile</span></button></nav>
    </>
  )
}
