import { Link } from 'react-router-dom'
export default function OfflineSyncCenterAshaSathi() {
  return (
    <>
<header className="fixed top-0 w-full z-50 flex justify-between items-center px-lg h-touch-target bg-surface shadow-sm"><button className="text-primary font-bold hover:bg-surface-container-highest transition-colors active:scale-95 duration-100 flex items-center justify-center w-touch-target h-touch-target rounded-full -ml-sm"><span className="material-symbols-outlined">sync</span></button><h1 className="text-headline-md font-headline-md font-bold text-primary">ASHA Field Care</h1><button className="text-on-surface-variant hover:bg-surface-container-highest transition-colors active:scale-95 duration-100 flex items-center justify-center w-touch-target h-touch-target rounded-full -mr-sm"><span className="material-symbols-outlined" data-weight="fill">notifications</span></button></header><main className="flex flex-col w-full max-w-[600px] mx-auto">
<div className="px-lg py-md mt-sm"><h2 className="text-headline-lg-mobile font-headline-lg-mobile text-on-surface">Offline Sync Center</h2></div>
<section className="px-lg mb-lg"><div className="bg-surface-container-low border border-outline-variant shadow-sm rounded-xl p-md flex flex-col items-center text-center relative overflow-hidden">
<div className="absolute top-0 right-0 w-32 h-32 bg-primary-fixed rounded-full opacity-20 -mr-16 -mt-16 pointer-events-none"></div><span className="material-symbols-outlined text-primary mb-sm" style={{ fontSize: '40px' }}>cloud_off</span><h3 className="text-display-lg font-display-lg text-on-surface">12</h3><p className="text-body-lg-mobile font-body-lg-mobile text-on-surface-variant font-medium">Pending Records</p><p className="text-caption font-caption text-outline mt-xs">Last Synced: 2 hours ago</p><button className="mt-md w-full min-h-[48px] bg-primary text-on-primary rounded-full flex items-center justify-center gap-sm hover:bg-surface-tint transition-colors active:scale-95 shadow-sm"><span className="material-symbols-outlined">sync</span><span className="text-label-md font-label-md">Sync Now</span></button></div></section>
<div className="px-lg mb-md flex border-b border-outline-variant"><button className="flex-1 pb-sm text-label-md font-label-md text-primary border-b-2 border-primary text-center">Pending (12)</button><button className="flex-1 pb-sm text-label-md font-label-md text-on-surface-variant text-center">Synced</button><button className="flex-1 pb-sm text-label-md font-label-md text-error text-center relative">
                Failed
                <span className="absolute top-0 right-2 w-2 h-2 bg-error rounded-full"></span></button></div>
<section className="px-lg flex flex-col gap-sm">
<article className="bg-surface-container-lowest border border-tertiary border-opacity-50 shadow-sm rounded-lg p-md flex flex-col gap-sm relative overflow-hidden">
<div className="absolute top-0 left-0 h-1 bg-tertiary w-1/3 animate-pulse"></div><div className="flex justify-between items-start"><div className="pr-md"><div className="w-[4px] h-full absolute left-0 top-0 bg-secondary"></div>
<h4 className="text-body-lg-mobile font-body-lg-mobile text-on-surface font-semibold pl-sm">Ramesh Household Visit</h4><p className="text-body-md font-body-md text-on-surface-variant mt-xs pl-sm">Form: Routine Follow-up</p></div><span className="material-symbols-outlined text-tertiary animate-spin mt-xs">sync</span></div><div className="flex items-center gap-xs mt-xs pl-sm"><div className="bg-tertiary-fixed text-on-tertiary-fixed-variant px-sm py-xs rounded-full flex items-center gap-xs"><span className="material-symbols-outlined text-[14px]">cloud_sync</span><span className="text-caption font-caption font-bold">Syncing...</span></div></div></article>
<article className="bg-surface-container-lowest border border-outline-variant shadow-sm rounded-lg p-md flex flex-col gap-sm relative"><div className="flex justify-between items-start"><div className="pr-md"><div className="w-[4px] h-full absolute left-0 top-0 bg-primary-container"></div>
<h4 className="text-body-lg-mobile font-body-lg-mobile text-on-surface font-semibold pl-sm">Anita Devi ANC Checkup</h4><p className="text-body-md font-body-md text-on-surface-variant mt-xs pl-sm">Form: Trimester 2</p></div><button className="text-outline p-xs -mr-xs active:bg-surface-container-low rounded-full"><span className="material-symbols-outlined">more_vert</span></button></div><div className="flex items-center gap-xs mt-xs pl-sm"><div className="bg-surface-variant text-on-surface-variant px-sm py-xs rounded-full flex items-center gap-xs"><span className="material-symbols-outlined text-[14px]">sd_storage</span><span className="text-caption font-caption font-bold">Stored Locally</span></div></div></article>
<article className="bg-error-container border border-error border-opacity-30 shadow-sm rounded-lg p-md flex flex-col gap-sm relative mt-sm"><div className="flex justify-between items-start"><div className="pr-md"><div className="w-[4px] h-full absolute left-0 top-0 bg-error"></div>
<h4 className="text-body-lg-mobile font-body-lg-mobile text-on-error-container font-semibold pl-sm">Sunita Newborn Reg.</h4><p className="text-body-md font-body-md text-on-error-container opacity-80 mt-xs pl-sm">Error: Network timeout</p></div><span className="material-symbols-outlined text-error mt-xs">error</span></div><div className="flex items-center justify-between mt-xs pl-sm"><div className="bg-error text-on-error px-sm py-xs rounded-full flex items-center gap-xs"><span className="material-symbols-outlined text-[14px]">warning</span><span className="text-caption font-caption font-bold">Failed</span></div><button className="text-label-md font-label-md text-error underline active:opacity-70 p-xs">Retry</button></div></article></section></main>
<nav className="fixed bottom-0 w-full z-50 flex justify-around items-center px-md pb-safe h-[72px] bg-surface shadow-lg">
<Link className="flex flex-col items-center justify-center text-on-surface-variant px-lg py-sm hover:bg-surface-container-low active:scale-90 transition-transform rounded-lg" to="/asha/home"><span className="material-symbols-outlined mb-xs">home</span><span className="text-label-md font-label-md text-[12px]">Home</span></Link>
<Link className="flex flex-col items-center justify-center text-on-surface-variant px-lg py-sm hover:bg-surface-container-low active:scale-90 transition-transform rounded-lg" to="/asha/households"><span className="material-symbols-outlined mb-xs">group</span><span className="text-label-md font-label-md text-[12px]">Households</span></Link>
<Link className="flex flex-col items-center justify-center text-on-surface-variant px-lg py-sm hover:bg-surface-container-low active:scale-90 transition-transform rounded-lg" to="/asha/patients"><span className="material-symbols-outlined mb-xs">person_search</span><span className="text-label-md font-label-md text-[12px]">Patients</span></Link>
<Link className="flex flex-col items-center justify-center bg-primary-container text-on-primary-container rounded-full px-lg py-sm active:scale-90 transition-transform shadow-sm" to="/asha/tasks"><span className="material-symbols-outlined mb-xs" data-weight="fill">assignment</span><span className="text-label-md font-label-md text-[12px]">Tasks</span></Link>
<Link className="flex flex-col items-center justify-center text-on-surface-variant px-lg py-sm hover:bg-surface-container-low active:scale-90 transition-transform rounded-lg" to="/asha/patients/1/profile"><span className="material-symbols-outlined mb-xs">account_circle</span><span className="text-label-md font-label-md text-[12px]">Profile</span></Link></nav>
    </>
  )
}
