export default function PatientDashboardAshaSathi() {
  return (
    <>
<header className="fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target md:px-lg bg-surface dark:bg-on-background border-b border-outline-variant dark:border-outline shadow-sm"><div className="flex items-center gap-sm"><span className="text-headline-md font-headline-md font-bold text-primary dark:text-primary-fixed-dim">ASHA Sathi</span></div><div className="flex items-center gap-sm"><button aria-label="Sync" className="h-touch-target w-touch-target flex items-center justify-center rounded-full hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors text-primary dark:text-primary-fixed-dim"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>sync</span></button><button aria-label="Notifications" className="h-touch-target w-touch-target flex items-center justify-center rounded-full hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors text-primary dark:text-primary-fixed-dim"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>notifications</span></button><div className="h-8 w-8 rounded-full bg-surface-variant overflow-hidden ml-sm border border-outline-variant"><img alt="User Profile" className="w-full h-full object-cover" data-alt="A close-up portrait of a reassuring Indian patient, softly lit with warm daylight. The style is modern healthcare photography, focusing on empathetic and clear visual communication. The color palette features natural skin tones against a soft, blurred background to maintain a calm, professional aesthetic." src="https://lh3.googleusercontent.com/aida-public/AB6AXuAGezzRQbUiGCfo8W7cwLEdIubdaU-a1b5cIyKshjGKx4jneiieWc9Az-RQydepSWSPqszpfSCB-s90LRozXM-9IIOHXmq5iYLzUGgZEhr9a5XQVsWjbdDyTHOr3xhM6cTkiy2usSku8PByi8o4EwmEeFfC9uqnKTtoH4zVE1DfnPrXTMopNJ1GQW_YHtbxEHnUxiWYj3J6nbOSFoJ9Y8hYT4Y5E69BgJswNuSvg6WS7zf3THi5yJWqLA" /></div></div></header>
<main className="pt-[64px] px-md md:px-lg max-w-7xl mx-auto space-y-lg mt-md">
<section className="py-sm"><h1 className="font-headline-lg-mobile text-headline-lg-mobile md:font-headline-lg md:text-headline-lg text-on-background">Namaste, Aarav</h1><p className="font-body-md text-body-md text-on-surface-variant mt-xs">Here is your health overview for today.</p></section>
<section><div className="bg-primary text-on-primary rounded-xl p-md shadow-sm relative overflow-hidden"><div className="absolute top-0 right-0 opacity-10 pointer-events-none w-32 h-32 transform translate-x-8 -translate-y-8"><span className="material-symbols-outlined text-[120px]">vaccines</span></div><div className="relative z-10"><div className="flex items-center gap-sm mb-xs"><span className="material-symbols-outlined text-secondary-container" style={{ fontVariationSettings: '\'FILL\' 1' }}>calendar_today</span><span className="font-label-md text-label-md text-secondary-container uppercase tracking-wider">Upcoming Task</span></div><h2 className="font-headline-md text-headline-md font-bold mb-xs">Next Vaccination</h2><p className="font-body-md text-body-md mb-md">Scheduled for 15 Oct 2023 at Primary Health Centre.</p><button className="bg-on-primary text-primary font-label-md text-label-md py-sm px-md rounded-full hover:bg-surface-container transition-colors shadow-sm inline-flex items-center gap-xs">
                        View Details
                        <span className="material-symbols-outlined text-[18px]">arrow_forward</span></button></div></div></section>
<section><h3 className="font-label-md text-label-md text-on-surface-variant uppercase tracking-wider mb-sm">Quick Access</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-md">
<button className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex flex-col items-start gap-sm hover:bg-surface-container transition-colors active:scale-95 text-left"><div className="w-10 h-10 rounded-full bg-primary-container text-on-primary-container flex items-center justify-center"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>medical_information</span></div><div><h4 className="font-label-md text-label-md text-on-background">My Health Records</h4><p className="font-caption text-caption text-on-surface-variant mt-xs line-clamp-1">View lab results & vitals</p></div></button>
<button className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex flex-col items-start gap-sm hover:bg-surface-container transition-colors active:scale-95 text-left"><div className="w-10 h-10 rounded-full bg-secondary-container text-on-secondary-container flex items-center justify-center"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>vaccines</span></div><div><h4 className="font-label-md text-label-md text-on-background">Vaccination History</h4><p className="font-caption text-caption text-on-surface-variant mt-xs line-clamp-1">Past immunization records</p></div></button>
<button className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex flex-col items-start gap-sm hover:bg-surface-container transition-colors active:scale-95 text-left"><div className="w-10 h-10 rounded-full bg-tertiary-container text-on-tertiary-container flex items-center justify-center"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>event_note</span></div><div><h4 className="font-label-md text-label-md text-on-background">My Appointments</h4><p className="font-caption text-caption text-on-surface-variant mt-xs line-clamp-1">Manage scheduled visits</p></div></button>
<button className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm flex flex-col items-start gap-sm hover:bg-surface-container transition-colors active:scale-95 text-left"><div className="w-10 h-10 rounded-full bg-surface-variant text-on-surface-variant flex items-center justify-center border border-outline-variant"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>prescriptions</span></div><div><h4 className="font-label-md text-label-md text-on-background">Prescriptions</h4><p className="font-caption text-caption text-on-surface-variant mt-xs line-clamp-1">Active medications</p></div></button></div></section>
<section className="pb-xl"><div className="flex justify-between items-center mb-sm"><h3 className="font-label-md text-label-md text-on-surface-variant uppercase tracking-wider">Recent Activity</h3><button className="text-primary font-label-md text-label-md hover:underline flex items-center">
                    See All <span className="material-symbols-outlined text-[16px] ml-xs">arrow_forward</span></button></div><div className="bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm divide-y divide-outline-variant">
<div className="p-md flex gap-md hover:bg-surface-container transition-colors cursor-pointer"><div className="flex-shrink-0 mt-xs"><div className="w-2 h-2 mt-2 rounded-full bg-secondary"></div></div><div className="flex-1"><div className="flex justify-between items-start mb-xs"><h4 className="font-label-md text-label-md text-on-background">Routine Check-up Completed</h4><span className="font-caption text-caption text-on-surface-variant whitespace-nowrap">2 Days Ago</span></div><p className="font-body-md text-body-md text-on-surface-variant mb-xs">ASHA Worker Sunita visited for a routine household check. Vitals are normal.</p><div className="inline-flex items-center bg-secondary-container text-on-secondary-container px-sm py-xs rounded-full font-caption text-caption"><span className="material-symbols-outlined text-[14px] mr-xs">check_circle</span> Status: Healthy
                        </div></div></div>
<div className="p-md flex gap-md hover:bg-surface-container transition-colors cursor-pointer"><div className="flex-shrink-0 mt-xs"><div className="w-2 h-2 mt-2 rounded-full bg-primary"></div></div><div className="flex-1"><div className="flex justify-between items-start mb-xs"><h4 className="font-label-md text-label-md text-on-background">Dietary Advice Provided</h4><span className="font-caption text-caption text-on-surface-variant whitespace-nowrap">1 Week Ago</span></div><p className="font-body-md text-body-md text-on-surface-variant">Received advice on incorporating more iron-rich foods into daily meals to prevent anemia.</p></div></div></div></section></main>
<nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-sm py-xs bg-surface dark:bg-on-background border-t border-outline-variant shadow-lg rounded-t-full pb-safe">
<button className="flex flex-col items-center justify-center bg-primary-container dark:bg-primary text-on-primary-container dark:text-on-primary rounded-full px-4 py-1 hover:bg-surface-container-highest dark:hover:bg-surface-variant scale-90 transition-transform duration-200"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>home</span><span className="font-label-md text-label-md mt-1">Home</span></button>
<button className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant rounded-xl p-2 transition-colors"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>folder_shared</span><span className="font-caption text-caption mt-1">Records</span></button>
<button className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant rounded-xl p-2 transition-colors"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>calendar_month</span><span className="font-caption text-caption mt-1">Visits</span></button>
<button className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant rounded-xl p-2 transition-colors"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>assignment_turned_in</span><span className="font-caption text-caption mt-1">Tasks</span></button>
<button className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant rounded-xl p-2 transition-colors"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>account_circle</span><span className="font-caption text-caption mt-1">Profile</span></button></nav>
<nav className="hidden md:flex flex-col h-screen fixed left-0 top-0 p-md gap-sm bg-surface-container-low dark:bg-inverse-surface border-r border-outline-variant w-64 z-40 pt-[80px]">
<div className="px-md mb-md"><h2 className="font-headline-md text-headline-md font-black text-primary">Patient Portal</h2></div>
<button className="flex items-center gap-md px-md py-sm bg-secondary-container dark:bg-secondary text-on-secondary-container dark:text-on-secondary font-bold rounded-lg w-full text-left scale-95 transition-transform duration-150"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>dashboard</span><span className="font-label-md text-label-md">Dashboard</span></button>
<button className="flex items-center gap-md px-md py-sm text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all rounded-lg w-full text-left"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>folder_shared</span><span className="font-label-md text-label-md">Health Records</span></button>
<button className="flex items-center gap-md px-md py-sm text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all rounded-lg w-full text-left"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>calendar_month</span><span className="font-label-md text-label-md">Appointments</span></button><div className="mt-auto border-t border-outline-variant pt-sm"><button className="flex items-center gap-md px-md py-sm text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all rounded-lg w-full text-left"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 0' }}>settings</span><span className="font-label-md text-label-md">Settings</span></button></div></nav>
    </>
  )
}
