/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#00478d',
        'primary-container': '#005eb8',
        'on-primary': '#ffffff',
        'on-primary-container': '#c8daff',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00468c',
        secondary: '#006e28',
        'secondary-container': '#82fc90',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00752a',
        'secondary-fixed': '#82fc90',
        'secondary-fixed-dim': '#65df77',
        'on-secondary-fixed': '#002107',
        'on-secondary-fixed-variant': '#00531c',
        tertiary: '#004e61',
        'tertiary-container': '#006880',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#9be4ff',
        'tertiary-fixed': '#b6ebff',
        'tertiary-fixed-dim': '#57d5fc',
        'on-tertiary-fixed': '#001f28',
        'on-tertiary-fixed-variant': '#004e60',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f9f9ff',
        'surface-dim': '#cadbfc',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dfe8ff',
        'surface-container-highest': '#d6e3ff',
        'on-surface': '#091c35',
        'on-surface-variant': '#424752',
        'inverse-surface': '#20314b',
        'inverse-on-surface': '#ecf0ff',
        'inverse-primary': '#a9c7ff',
        outline: '#727783',
        'outline-variant': '#c2c6d4',
        'surface-tint': '#005db6',
        background: '#f9f9ff',
        'on-background': '#091c35',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-lg-mobile': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-lg-mobile': ['18px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'form-gap': '20px',
        'touch-target': '48px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(0,0,0,0.05), 0 1px 3px rgba(0,0,0,0.1)',
        modal: '0 4px 16px rgba(0,0,0,0.1), 0 2px 8px rgba(0,0,0,0.08)',
      },
      screens: {
        tablet: '768px',
        desktop: '1024px',
        wide: '1440px',
      },
    },
  },
  plugins: [],
}
