apiVersion: v1
kind: Service
metadata:
  name: {{ include "asha-sathi.fullname" . }}-web
  labels:
    {{- include "asha-sathi.componentLabels" (dict "context" . "component" "web") | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "asha-sathi.componentSelectorLabels" (dict "context" . "component" "web") | nindent 4 }}
