name: asha_design_system
description: ASHA Sathi Design System for Flutter
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  material_symbols_icons: ^4.2670.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Variable.ttf