import { Link } from 'react-router-dom'
export default function AccountRecoveryAshaSathi() {
  return (
    <>
<header className="fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target md:px-lg bg-surface dark:bg-on-background shadow-sm border-b border-outline-variant dark:border-outline"><div className="flex items-center gap-sm"><span className="material-symbols-outlined text-primary dark:text-primary-fixed-dim" style={{ fontVariationSettings: '\'FILL\' 1' }}>medical_services</span><span className="text-headline-md font-headline-md font-bold text-primary dark:text-primary-fixed-dim">ASHA Sathi</span></div><Link className="font-label-md text-label-md text-primary dark:text-primary-fixed-dim flex items-center gap-xs hover:bg-surface-container transition-colors p-sm rounded-lg" to="/login"><span className="material-symbols-outlined">arrow_back</span>
            Back to Login
        </Link></header><main className="w-full max-w-md mx-auto mt-xxl"><div className="bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm p-lg md:p-xl"><div className="text-center mb-xl"><div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary-container text-on-primary-container mb-md"><span className="material-symbols-outlined text-3xl" style={{ fontVariationSettings: '\'FILL\' 0' }}>lock_reset</span></div><h1 className="font-headline-lg-mobile text-headline-lg-mobile md:font-headline-lg md:text-headline-lg text-on-surface mb-sm">Account Recovery</h1><p className="font-body-md text-body-md text-on-surface-variant">
                    Enter your registered mobile number or email address below. We'll send you instructions to reset your password.
                </p></div><form className="space-y-form-gap"><div><label className="block font-label-md text-label-md text-on-surface mb-xs" htmlFor="recovery_contact">Mobile Number or Email</label><div className="relative"><span className="absolute inset-y-0 left-0 flex items-center pl-sm"><span className="material-symbols-outlined text-outline">contact_mail</span></span><input className="block w-full pl-xl pr-sm py-sm min-h-[48px] bg-surface border border-outline-variant rounded-lg text-on-surface focus:ring-2 focus:ring-primary focus:border-primary placeholder-outline-variant font-body-md text-body-md transition-shadow" id="recovery_contact" name="recovery_contact" placeholder="e.g. +91 9876543210 or user@example.com" required type="text" /></div></div><div className="bg-surface-container rounded-lg p-sm border border-outline-variant/50 flex gap-sm items-start"><span className="material-symbols-outlined text-primary mt-1" style={{ fontVariationSettings: '\'FILL\' 1' }}>info</span><p className="font-caption text-caption text-on-surface-variant">
                        For mobile numbers, an SMS with a one-time password (OTP) will be sent. For email, you will receive a secure reset link valid for 15 minutes.
                    </p></div><button className="w-full flex justify-center items-center gap-sm bg-primary text-on-primary font-label-md text-label-md min-h-[48px] rounded-lg shadow-sm hover:bg-on-primary-fixed-variant transition-colors active:scale-95" type="submit">
                    Request Reset Link
                    <span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>send</span></button></form><div className="mt-xl text-center border-t border-outline-variant pt-lg"><p className="font-body-md text-body-md text-on-surface-variant">
                    Having trouble? 
                    <Link className="font-label-md text-label-md text-primary hover:underline ml-xs" to="/account-recovery">Contact Admin Support</Link></p></div></div></main>
    </>
  )
}
