import { Link } from 'react-router-dom'
export default function AddNewAshaWorkerPhcAdmin() {
  return (
    <>
<nav className="hidden md:flex flex-col h-screen fixed left-0 top-0 p-md gap-sm bg-surface-container-low dark:bg-inverse-surface border-r border-outline-variant docked left-0 h-full w-64 z-40">
<div className="flex items-center gap-md p-sm mb-lg"><div className="w-12 h-12 rounded-full overflow-hidden bg-surface flex-shrink-0"><img alt="Admin Avatar" className="w-full h-full object-cover" data-alt="A professional headshot of an administrative healthcare worker in a well-lit, modern office setting. The subject is wearing business casual attire suitable for a clinical administration role. The lighting is soft and neutral, conveying competence and approachability within a healthcare context." src="https://lh3.googleusercontent.com/aida-public/AB6AXuBaESrhhVZVrca1_FOa0kfHfAwaQ1k5P9TMzLNECoZfv1PYzI1pkTltc8Tueza_prWuZ6xmNL8Zbn4fWbcvpFnmJb-UQjoQ50lwOLA8kMw6ZP5VhussQZncQd42QKjoMajz4BbV5HkuwIsNJMgtXV6_MaKHbPHDFiD3ACgtHx8yaA3T15Ldd_kwdHw8u2mWvZoCgBiriuQhHciuB7PKwaceYzDF4wV-LnIVYmz00B2k6i-xYRBCtM5vYw" /></div><div><h1 className="font-headline-md text-headline-md font-black text-primary">Admin Portal</h1><p className="font-caption text-caption text-on-surface-variant">District Health Office</p></div></div>
<button className="w-full bg-primary-container text-on-primary-container font-label-md text-label-md py-sm px-md rounded-lg mb-md hover:bg-surface-container-highest transition-colors flex items-center justify-center gap-sm shadow-sm"><span className="material-symbols-outlined">add</span>
            Add New Worker
        </button>
<div className="flex-grow flex flex-col gap-xs font-label-md text-label-md"><Link className="flex items-center gap-md p-sm text-on-surface-variant hover:bg-surface-container-high hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all rounded-lg" to="/phc/dashboard"><span className="material-symbols-outlined">dashboard</span>
                Dashboard
            </Link>
<Link className="flex items-center gap-md p-sm bg-secondary-container dark:bg-secondary text-on-secondary-container dark:text-on-secondary font-bold rounded-lg scale-95 transition-transform duration-150" to="/phc/ashas"><span className="material-symbols-outlined fill-icon">groups</span>
                Workers
            </Link><Link className="flex items-center gap-md p-sm text-on-surface-variant hover:bg-surface-container-high hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all rounded-lg" to="/phc/beneficiaries"><span className="material-symbols-outlined">person_celebrate</span>
                Beneficiaries
            </Link><Link className="flex items-center gap-md p-sm text-on-surface-variant hover:bg-surface-container-high hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all rounded-lg" to="/phc/reports/maternal"><span className="material-symbols-outlined">analytics</span>
                Reports
            </Link><Link className="flex items-center gap-md p-sm text-on-surface-variant hover:bg-surface-container-high hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all rounded-lg" to="/phc/vaccination"><span className="material-symbols-outlined">inventory_2</span>
                Inventory
            </Link></div>
<div className="mt-auto border-t border-outline-variant pt-md flex flex-col gap-xs font-label-md text-label-md"><a className="flex items-center gap-md p-sm text-on-surface-variant hover:bg-surface-container-high hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all rounded-lg" href="#"><span className="material-symbols-outlined">settings</span>
                Settings
            </a><a className="flex items-center gap-md p-sm text-on-surface-variant hover:bg-surface-container-high hover:bg-surface-container-highest dark:hover:bg-surface-variant transition-all rounded-lg" href="#"><span className="material-symbols-outlined">help</span>
                Support
            </a></div></nav>
<div className="flex-grow flex flex-col md:ml-64 w-full h-full relative">
<header className="fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target md:px-lg bg-surface dark:bg-on-background border-b border-outline-variant dark:border-outline shadow-sm md:w-[calc(100%-16rem)]">
<div className="flex items-center gap-sm"><span className="text-headline-md font-headline-md font-bold text-primary dark:text-primary-fixed-dim">ASHA Sathi</span></div>
<div className="flex items-center gap-md">
<button aria-label="Search" className="p-xs text-on-surface-variant hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors rounded-full"><span className="material-symbols-outlined">search</span></button>
<button aria-label="sync" className="p-xs text-on-surface-variant hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors rounded-full"><span className="material-symbols-outlined">sync</span></button><button aria-label="notifications" className="p-xs text-on-surface-variant hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors rounded-full relative"><span className="material-symbols-outlined">notifications</span><span className="absolute top-1 right-1 w-2 h-2 bg-error rounded-full"></span></button>
<div className="w-8 h-8 rounded-full overflow-hidden bg-surface-container border border-outline-variant cursor-pointer ml-sm"><img alt="User Profile" className="w-full h-full object-cover" data-alt="A small, circular profile picture of an administrative user. The image shows a generic, professional silhouette or a generic stock headshot suitable for a healthcare dashboard top navigation bar. Clean, light background." src="https://lh3.googleusercontent.com/aida-public/AB6AXuDI5y61lApiLodDt9J8bLWByeO3wjuBLkwiH1L6JIQ9fk8OP5RwWyDD3HRAKduX435W0WumbhKzu3wLesrp8sB_tXVKH9M3TsEOuVBBuIHJkFAUTLlfqBXev0_czieGse8vD25xZLWRXiwadu142aBWeSHT1OXD1yL8zWTvVkOlfjAWf_4rvMtK7So4yPSi8_o_d1P_8ooKkHtMzpV1j50OyzCnFb-E8kR5JdPSDZX79xmaJpMQu9ARrA" /></div></div></header>
<main className="flex-grow pt-[calc(var(--spacing-touch-target)+var(--spacing-lg))] px-md md:px-xl pb-xxl overflow-y-auto bg-surface-bright">
<div className="max-w-4xl mx-auto mb-lg flex justify-between items-end"><div><div className="flex items-center gap-sm text-on-surface-variant font-caption text-caption mb-xs"><span className="material-symbols-outlined text-[16px]">arrow_back</span><Link className="hover:underline" to="/phc/ashas">Back to Workers List</Link></div><h2 className="font-display-lg text-display-lg text-on-surface">Register New ASHA Worker</h2></div><div className="hidden md:flex gap-sm">
<span className="inline-flex items-center px-sm py-xs rounded-full bg-surface-container-high text-on-surface-variant font-label-md text-label-md"><span className="w-2 h-2 rounded-full bg-outline mr-sm"></span> Draft
                    </span></div></div>
<form className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-12 gap-lg pb-xxl">
<div className="md:col-span-4 flex flex-col gap-lg">
<div className="bg-surface border border-outline-variant rounded-xl p-lg shadow-[0px_2px_4px_rgba(0,0,0,0.05)] flex flex-col items-center text-center"><div className="w-32 h-32 rounded-full bg-surface-container border-2 border-dashed border-outline-variant flex items-center justify-center mb-md relative overflow-hidden group cursor-pointer hover:bg-surface-container-high transition-colors"><div className="absolute inset-0 flex flex-col items-center justify-center text-on-surface-variant group-hover:text-primary transition-colors z-10 bg-white/50 backdrop-blur-[2px]"><span className="material-symbols-outlined text-[32px] mb-xs">add_a_photo</span><span className="font-caption text-caption">Upload Photo</span></div>
<img alt="Upload Placeholder" className="absolute inset-0 w-full h-full object-cover opacity-30" data-alt="A placeholder graphic indicating an image upload area. It features a soft, light blue-grey background with a subtle, stylized human silhouette icon in the center, representing a missing profile picture. The style is flat, modern, and clinical." src="https://lh3.googleusercontent.com/aida-public/AB6AXuD7RXgvg70h5xonRMW4SyGUceS36CBZ0D184xTcWGI65GfT8kXzsxceN25aCnAkHvYExsMDZ7mDjBswr_1vzgNtM54XNctW1WzuTdtQUP-yur8aQBXQSAGTWKndm618GONt9oOGvXFbvEmWl9cVhIfvZhrUEDhn-_46Pqchw2pzlreEwE5A2dDFEXtNPJZ7WtK1oOe73iIqpryFIf9oWktXmbZu0dcABsswYtXIfhxRE3UPJRxQCBXhtQ" /></div><h3 className="font-headline-md text-headline-md text-on-surface">Profile Picture</h3><p className="font-caption text-caption text-on-surface-variant mt-xs mb-md">JPG or PNG. Max size 5MB.</p><div className="w-full bg-surface-container-low rounded-lg p-sm border border-outline-variant flex items-center gap-sm mt-auto"><span className="material-symbols-outlined text-secondary">verified_user</span><div className="text-left"><span className="block font-label-md text-label-md text-on-surface">ID Verification</span><span className="block font-caption text-caption text-on-surface-variant">Required for activation</span></div></div></div>
<div className="bg-surface border border-outline-variant rounded-xl p-lg shadow-[0px_2px_4px_rgba(0,0,0,0.05)]"><h3 className="font-headline-md text-headline-md text-on-surface mb-md flex items-center gap-sm"><span className="material-symbols-outlined text-primary">badge</span>
                            Credentials
                        </h3><div className="space-y-form-gap"><div className="flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="username">Assigned Username / ID</label><div className="relative"><span className="absolute inset-y-0 left-0 pl-sm flex items-center pointer-events-none text-on-surface-variant"><span className="material-symbols-outlined text-[20px]">person</span></span><input className="w-full pl-[36px] pr-sm py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow h-touch-target md:h-auto min-h-[48px]" id="username" name="username" placeholder="e.g. ASHA-1042" type="text" /></div><p className="font-caption text-caption text-on-surface-variant mt-xs">Auto-generated based on district code if left blank.</p></div></div></div></div>
<div className="md:col-span-8 flex flex-col gap-lg">
<div className="bg-surface border border-outline-variant rounded-xl p-lg shadow-[0px_2px_4px_rgba(0,0,0,0.05)]"><div className="border-b border-outline-variant pb-sm mb-md flex items-center gap-sm"><div className="w-8 h-8 rounded-full bg-primary-fixed flex items-center justify-center text-on-primary-fixed font-label-md text-label-md">1</div><h3 className="font-headline-md text-headline-md text-on-surface">Personal Information</h3></div><div className="grid grid-cols-1 md:grid-cols-2 gap-form-gap">
<div className="col-span-1 md:col-span-2 flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="fullName">Full Name *</label><input className="w-full px-md py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow h-touch-target md:h-auto min-h-[48px]" id="fullName" name="fullName" required type="text" /></div>
<div className="flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="dob">Date of Birth *</label><div className="relative"><span className="absolute inset-y-0 left-0 pl-sm flex items-center pointer-events-none text-on-surface-variant"><span className="material-symbols-outlined text-[20px]">calendar_today</span></span><input className="w-full pl-[36px] pr-sm py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow h-touch-target md:h-auto min-h-[48px] appearance-none" id="dob" name="dob" required type="date" /></div></div>
<div className="flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="gender">Gender *</label><div className="relative"><select className="w-full pl-sm pr-lg py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow appearance-none h-touch-target md:h-auto min-h-[48px]" id="gender" name="gender" required><option disabled selected value="">Select Gender</option><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></select><div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-sm text-on-surface-variant"><span className="material-symbols-outlined">arrow_drop_down</span></div></div></div>
<div className="col-span-1 md:col-span-2 flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="aadhaar">Aadhaar Number *</label><div className="relative"><span className="absolute inset-y-0 left-0 pl-sm flex items-center pointer-events-none text-on-surface-variant"><span className="material-symbols-outlined text-[20px]">fingerprint</span></span><input className="w-full pl-[36px] pr-sm py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow font-mono tracking-widest h-touch-target md:h-auto min-h-[48px]" id="aadhaar" name="aadhaar" pattern="\d{4}\s\d{4}\s\d{4}" placeholder="XXXX XXXX XXXX" required type="text" /></div></div></div></div>
<div className="bg-surface border border-outline-variant rounded-xl p-lg shadow-[0px_2px_4px_rgba(0,0,0,0.05)]"><div className="border-b border-outline-variant pb-sm mb-md flex items-center gap-sm"><div className="w-8 h-8 rounded-full bg-primary-fixed flex items-center justify-center text-on-primary-fixed font-label-md text-label-md">2</div><h3 className="font-headline-md text-headline-md text-on-surface">Contact Details</h3></div><div className="grid grid-cols-1 md:grid-cols-2 gap-form-gap">
<div className="flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="mobile">Mobile Number *</label><div className="relative"><span className="absolute inset-y-0 left-0 pl-sm flex items-center pointer-events-none text-on-surface-variant"><span className="material-symbols-outlined text-[20px]">phone_iphone</span></span><input className="w-full pl-[36px] pr-sm py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow h-touch-target md:h-auto min-h-[48px]" id="mobile" name="mobile" placeholder="+91" required type="tel" /></div></div>
<div className="flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="email">Email Address (Optional)</label><div className="relative"><span className="absolute inset-y-0 left-0 pl-sm flex items-center pointer-events-none text-on-surface-variant"><span className="material-symbols-outlined text-[20px]">mail</span></span><input className="w-full pl-[36px] pr-sm py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow h-touch-target md:h-auto min-h-[48px]" id="email" name="email" type="email" /></div></div>
<div className="col-span-1 md:col-span-2 flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="emergency">Emergency Contact *</label><div className="flex flex-col md:flex-row gap-sm"><input className="w-full md:w-1/2 px-md py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow h-touch-target md:h-auto min-h-[48px]" placeholder="Contact Name" required type="text" /><div className="relative w-full md:w-1/2"><span className="absolute inset-y-0 left-0 pl-sm flex items-center pointer-events-none text-on-surface-variant"><span className="material-symbols-outlined text-[20px]">sos</span></span><input className="w-full pl-[36px] pr-sm py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow h-touch-target md:h-auto min-h-[48px]" placeholder="Emergency Number" required type="tel" /></div></div></div></div></div>
<div className="bg-surface border border-outline-variant rounded-xl p-lg shadow-[0px_2px_4px_rgba(0,0,0,0.05)]"><div className="border-b border-outline-variant pb-sm mb-md flex items-center gap-sm"><div className="w-8 h-8 rounded-full bg-primary-fixed flex items-center justify-center text-on-primary-fixed font-label-md text-label-md">3</div><h3 className="font-headline-md text-headline-md text-on-surface">Work Assignment</h3></div><div className="grid grid-cols-1 md:grid-cols-2 gap-form-gap">
<div className="col-span-1 md:col-span-2 flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="subcenter">Reporting Sub-center *</label><div className="relative"><span className="absolute inset-y-0 left-0 pl-sm flex items-center pointer-events-none text-on-surface-variant"><span className="material-symbols-outlined text-[20px]">local_hospital</span></span><select className="w-full pl-[36px] pr-lg py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow appearance-none h-touch-target md:h-auto min-h-[48px]" id="subcenter" name="subcenter" required><option disabled selected value="">Select Sub-center</option><option value="sc1">Rampur Sub-center</option><option value="sc2">Shyamnagar Sub-center</option><option value="sc3">Madhupur Sub-center</option></select><div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-sm text-on-surface-variant"><span className="material-symbols-outlined">arrow_drop_down</span></div></div></div>
<div className="flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="village">Assigned Village *</label><div className="relative"><span className="absolute inset-y-0 left-0 pl-sm flex items-center pointer-events-none text-on-surface-variant"><span className="material-symbols-outlined text-[20px]">location_on</span></span><select className="w-full pl-[36px] pr-lg py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow appearance-none h-touch-target md:h-auto min-h-[48px]" id="village" name="village" required><option disabled selected value="">Select Village</option><option value="v1">Kalyanpur</option><option value="v2">Bishanpur</option><option value="v3">Govindpur</option></select><div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-sm text-on-surface-variant"><span className="material-symbols-outlined">arrow_drop_down</span></div></div></div>
<div className="flex flex-col"><label className="font-label-md text-label-md text-on-surface mb-xs" htmlFor="doj">Date of Joining *</label><div className="relative"><span className="absolute inset-y-0 left-0 pl-sm flex items-center pointer-events-none text-on-surface-variant"><span className="material-symbols-outlined text-[20px]">event_available</span></span><input className="w-full pl-[36px] pr-sm py-[10px] bg-surface-container-lowest border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-shadow appearance-none h-touch-target md:h-auto min-h-[48px]" id="doj" name="doj" required type="date" /></div></div></div></div>
<div className="mt-lg pt-lg border-t border-outline-variant flex flex-col-reverse md:flex-row justify-end gap-md sticky bottom-0 bg-surface-bright/95 backdrop-blur-sm z-20 pb-md md:static md:bg-transparent md:backdrop-blur-none"><button className="w-full md:w-auto px-xl py-[12px] bg-transparent border border-primary text-primary font-label-md text-label-md rounded-lg hover:bg-primary-fixed transition-colors h-touch-target flex items-center justify-center" type="button">
                            Cancel
                        </button><button className="w-full md:w-auto px-xl py-[12px] bg-primary text-on-primary font-label-md text-label-md rounded-lg hover:bg-primary-fixed-variant transition-colors h-touch-target flex items-center justify-center shadow-md shadow-primary/20 gap-sm" type="submit"><span className="material-symbols-outlined text-[20px]">save</span>
                            Save Worker Details
                        </button></div></div></form></main></div>
    </>
  )
}
