export default function AddNewPatientAshaSathi() {
  return (
    <>
<header className="bg-surface border-b border-outline-variant h-16 flex-shrink-0 flex items-center px-md lg:px-lg sticky top-0 z-50"><div className="flex items-center gap-sm w-full max-w-5xl mx-auto"><button aria-label="Go back" className="w-10 h-10 rounded-full flex items-center justify-center text-on-surface-variant hover:bg-surface-container-highest transition-colors"><span className="material-symbols-outlined">arrow_back</span></button><div className="flex flex-col"><h1 className="font-headline-md text-headline-md text-on-surface leading-tight">Add New Patient</h1><p className="font-caption text-caption text-on-surface-variant hidden md:block">Register a new beneficiary in the PHC database</p></div><div className="ml-auto flex items-center gap-sm"><div className="hidden md:flex items-center gap-xs px-sm py-xs bg-surface-container rounded-full text-primary font-label-md text-label-md"><span className="material-symbols-outlined text-[18px]">cloud_sync</span><span>Online</span></div></div></div></header>
<main className="flex-1 overflow-y-auto p-md md:p-lg pb-xxl"><form className="max-w-4xl mx-auto flex flex-col gap-lg">
<section className="bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden"><div className="bg-surface-container-lowest px-lg py-md border-b border-outline-variant flex items-center gap-sm"><span className="material-symbols-outlined text-primary">person</span><h2 className="font-headline-md text-headline-md text-on-surface">Personal Information</h2></div><div className="p-lg grid grid-cols-1 md:grid-cols-2 gap-form-gap">
<div className="flex flex-col gap-xs md:col-span-2"><label className="font-label-md text-label-md text-on-surface-variant" htmlFor="patient_name">Full Name *</label><input className="h-touch-target px-md rounded-lg border border-outline bg-surface text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all" id="patient_name" placeholder="Enter legal name" required type="text" /></div>
<div className="flex flex-col gap-xs"><label className="font-label-md text-label-md text-on-surface-variant" htmlFor="uid">ABHA / Health ID</label><input className="h-touch-target px-md rounded-lg border border-outline bg-surface text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all" id="uid" placeholder="14-digit ID (Optional)" type="text" /></div>
<div className="flex flex-col gap-xs"><label className="font-label-md text-label-md text-on-surface-variant" htmlFor="mobile">Mobile Number *</label><div className="relative"><span className="absolute inset-y-0 left-0 flex items-center pl-md text-on-surface-variant font-body-md text-body-md">+91</span><input className="h-touch-target pl-12 pr-md w-full rounded-lg border border-outline bg-surface text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all" id="mobile" pattern="[0-9]{10}" placeholder="10-digit number" required type="tel" /></div></div>
<div className="flex flex-col gap-xs"><label className="font-label-md text-label-md text-on-surface-variant" htmlFor="dob">Date of Birth *</label><input className="h-touch-target px-md rounded-lg border border-outline bg-surface text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all" id="dob" required type="date" /></div>
<div className="flex flex-col gap-xs"><label className="font-label-md text-label-md text-on-surface-variant" htmlFor="gender">Gender *</label><div className="relative"><select className="h-touch-target px-md w-full rounded-lg border border-outline bg-surface text-on-surface appearance-none focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all" id="gender" required><option disabled selected value="">Select gender</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select><span className="material-symbols-outlined absolute inset-y-0 right-0 flex items-center pr-md pointer-events-none text-on-surface-variant">expand_more</span></div></div></div></section>
<section className="bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden"><div className="bg-surface-container-lowest px-lg py-md border-b border-outline-variant flex items-center gap-sm"><span className="material-symbols-outlined text-primary">cottage</span><h2 className="font-headline-md text-headline-md text-on-surface">Family & Household</h2></div><div className="p-lg grid grid-cols-1 md:grid-cols-2 gap-form-gap">
<div className="flex flex-col gap-xs"><label className="font-label-md text-label-md text-on-surface-variant" htmlFor="village">Village / Locality *</label><div className="relative"><select className="h-touch-target px-md w-full rounded-lg border border-outline bg-surface text-on-surface appearance-none focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all" id="village" required><option disabled selected value="">Select assigned village</option><option value="v1">Rampur</option><option value="v2">Sitapur</option><option value="v3">Lakshmanpur</option></select><span className="material-symbols-outlined absolute inset-y-0 right-0 flex items-center pr-md pointer-events-none text-on-surface-variant">expand_more</span></div></div>
<div className="flex flex-col gap-xs"><label className="font-label-md text-label-md text-on-surface-variant" htmlFor="household_id">Household ID (Optional)</label><input className="h-touch-target px-md rounded-lg border border-outline bg-surface text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all" id="household_id" placeholder="Link to existing household" type="text" /></div></div></section>
<section className="bg-surface rounded-xl border border-outline-variant shadow-sm overflow-hidden relative">
<div className="absolute left-0 top-0 bottom-0 w-1 bg-tertiary-container rounded-l-xl"></div><div className="bg-surface-container-lowest px-lg py-md border-b border-outline-variant flex items-center gap-sm pl-xl"><span className="material-symbols-outlined text-tertiary-container">medical_services</span><h2 className="font-headline-md text-headline-md text-on-surface">Initial Health Assessment</h2></div><div className="p-lg pl-xl grid grid-cols-1 gap-form-gap">
<div className="flex flex-col gap-xs md:w-1/2"><label className="font-label-md text-label-md text-on-surface-variant" htmlFor="asha_worker">Assigned ASHA Worker *</label><div className="relative"><select className="h-touch-target px-md w-full rounded-lg border border-outline bg-surface text-on-surface appearance-none focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all" id="asha_worker" required><option disabled selected value="">Select worker</option><option value="w1">Sunita Devi (Rampur)</option><option value="w2">Anita Kumari (Sitapur)</option></select><span className="material-symbols-outlined absolute inset-y-0 right-0 flex items-center pr-md pointer-events-none text-on-surface-variant">expand_more</span></div></div>
<div className="flex flex-col gap-sm mt-sm"><label className="font-label-md text-label-md text-on-surface-variant">Initial Risk Assessment</label><div className="flex flex-col sm:flex-row gap-md"><label className="relative flex items-center p-md rounded-lg border border-outline-variant cursor-pointer hover:bg-surface-container-low transition-colors w-full"><input className="peer sr-only" name="risk_level" type="radio" value="low" /><div className="w-5 h-5 rounded-full border-2 border-outline peer-checked:border-secondary peer-checked:bg-secondary flex items-center justify-center mr-sm"><div className="w-2.5 h-2.5 rounded-full bg-surface hidden peer-checked:block"></div></div><span className="font-body-md text-body-md text-on-surface">Routine / Low Risk</span><div className="ml-auto w-3 h-3 rounded-full bg-secondary-container border border-secondary"></div></label><label className="relative flex items-center p-md rounded-lg border border-outline-variant cursor-pointer hover:bg-surface-container-low transition-colors w-full"><input className="peer sr-only" name="risk_level" type="radio" value="medium" /><div className="w-5 h-5 rounded-full border-2 border-outline peer-checked:border-[orange] peer-checked:bg-[orange] flex items-center justify-center mr-sm"><div className="w-2.5 h-2.5 rounded-full bg-surface hidden peer-checked:block"></div></div><span className="font-body-md text-body-md text-on-surface">Monitor / Medium Risk</span><div className="ml-auto w-3 h-3 rounded-full bg-[orange] border border-[darkorange] opacity-50"></div></label><label className="relative flex items-center p-md rounded-lg border border-outline-variant cursor-pointer hover:bg-surface-container-low transition-colors w-full"><input className="peer sr-only" name="risk_level" type="radio" value="high" /><div className="w-5 h-5 rounded-full border-2 border-outline peer-checked:border-error peer-checked:bg-error flex items-center justify-center mr-sm"><div className="w-2.5 h-2.5 rounded-full bg-surface hidden peer-checked:block"></div></div><span className="font-body-md text-body-md text-on-surface">Urgent / High Risk</span><div className="ml-auto w-3 h-3 rounded-full bg-error-container border border-error"></div></label></div></div>
<div className="flex flex-col gap-xs"><label className="font-label-md text-label-md text-on-surface-variant" htmlFor="notes">Clinical Notes / Presenting Conditions</label><textarea className="p-md rounded-lg border border-outline bg-surface text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all resize-y min-h-[100px]" id="notes" placeholder="Briefly describe any current symptoms or conditions..." rows={3}></textarea></div></div></section></form></main>
<footer className="bg-surface border-t border-outline-variant px-md py-sm md:px-lg md:py-md flex-shrink-0 z-40"><div className="max-w-4xl mx-auto flex items-center justify-end gap-md"><button className="h-touch-target px-lg rounded-full font-label-md text-label-md text-primary hover:bg-surface-container-highest transition-colors flex items-center justify-center" type="button">
                Cancel
            </button><button className="h-touch-target px-xl rounded-full font-label-md text-label-md bg-primary-container text-on-primary-container hover:bg-primary hover:text-on-primary transition-colors flex items-center justify-center shadow-sm" type="button">
                Save Patient
            </button></div></footer>
    </>
  )
}
