import { useState } from 'react'
import { Link } from 'react-router-dom'

interface PendingTask {
  id: string
  title: string
  subtitle: string
  icon: string
  done: boolean
}

const INITIAL_TASKS: PendingTask[] = [
  { id: 't1', title: 'Polio Vaccine Due', subtitle: 'Rahul (6 months) • Ward 2', icon: 'vaccines', done: false },
  { id: 't2', title: 'IFA Tablets Distribution', subtitle: 'Sita Devi • Ward 1', icon: 'medication', done: false },
]

export default function AshaWorkerHomeAshaSathi() {
  const [tasks, setTasks] = useState<PendingTask[]>(INITIAL_TASKS)
  const pending = tasks.filter((t) => !t.done).length

  const toggleTask = (id: string) => {
    setTasks((prev) => prev.map((t) => (t.id === id ? { ...t, done: !t.done } : t)))
  }

  return (
    <>
<header className="bg-surface dark:bg-surface-dim font-headline-lg-mobile text-headline-lg-mobile text-primary dark:text-primary-fixed-dim bg-surface-container-low dark:bg-surface-container-low shadow-sm fixed top-0 left-0 w-full z-50 flex justify-between items-center px-lg h-touch-target"><button className="text-on-surface-variant dark:text-on-surface-variant hover:bg-surface-variant dark:hover:bg-surface-variant active:scale-95 transition-transform duration-200 p-sm rounded-full flex items-center justify-center"><span className="material-symbols-outlined">menu</span></button><div className="font-headline-lg-mobile text-headline-lg-mobile text-primary dark:text-primary-fixed-dim">
            ASHA Sathi
        </div><div className="flex items-center gap-xs">
<div className="flex items-center gap-xs px-sm py-xs bg-surface-container-high rounded-full mr-sm shadow-sm"><span className="w-3 h-3 rounded-full bg-secondary"></span><span className="font-label-md text-label-md text-on-surface">Online</span></div><button className="text-on-surface-variant dark:text-on-surface-variant hover:bg-surface-variant dark:hover:bg-surface-variant active:scale-95 transition-transform duration-200 p-sm rounded-full flex items-center justify-center"><span className="material-symbols-outlined">sync</span></button></div></header><main className="flex-1 px-lg py-md flex flex-col gap-xl">
<section className="flex flex-col gap-sm"><h1 className="font-display-lg text-display-lg text-on-background">Namaste, Sunita!</h1><div className="bg-surface-container rounded-xl p-md border border-outline-variant shadow-sm flex flex-col gap-sm"><div className="font-headline-md text-headline-md text-primary">Today's Agenda</div><div className="flex justify-between items-center"><div className="flex flex-col"><span className="font-display-lg text-display-lg text-on-surface">8</span><span className="font-label-md text-label-md text-on-surface-variant">Visits Planned</span></div><div className="w-px h-10 bg-outline-variant"></div><div className="flex flex-col"><span className="font-display-lg text-display-lg text-on-surface">{pending}</span><span className="font-label-md text-label-md text-on-surface-variant">Pending Tasks</span></div></div></div></section>
<section className="grid grid-cols-3 gap-sm"><button className="flex flex-col items-center justify-center bg-primary text-on-primary rounded-xl p-md h-[100px] shadow-sm hover:bg-on-primary-fixed-variant transition-colors active:scale-95"><span className="material-symbols-outlined mb-xs text-[32px]">person_add</span><span className="font-label-md text-label-md text-center">Add Patient</span></button><button className="flex flex-col items-center justify-center bg-primary text-on-primary rounded-xl p-md h-[100px] shadow-sm hover:bg-on-primary-fixed-variant transition-colors active:scale-95"><span className="material-symbols-outlined mb-xs text-[32px]">edit_document</span><span className="font-label-md text-label-md text-center">Record Visit</span></button><button className="flex flex-col items-center justify-center bg-[#D50000] text-white rounded-xl p-md h-[100px] shadow-sm hover:bg-red-800 transition-colors active:scale-95"><span className="material-symbols-outlined mb-xs text-[32px]">emergency</span><span className="font-label-md text-label-md text-center">Emergency</span></button></section>
<section className="flex flex-col gap-sm"><div className="flex justify-between items-center"><h2 className="font-headline-md text-headline-md text-on-background flex items-center gap-xs text-error"><span className="material-symbols-outlined text-error">warning</span> High-Risk Alerts
                </h2></div><div className="flex overflow-x-auto pb-sm gap-md snap-x"><div className="min-w-[280px] bg-error-container rounded-xl p-md border border-error/20 shadow-sm snap-center relative overflow-hidden flex flex-col gap-xs"><div className="absolute left-0 top-0 bottom-0 w-2 bg-error"></div><div className="pl-sm"><div className="flex justify-between items-start"><span className="font-label-md text-label-md text-on-error-container bg-error/10 px-2 py-1 rounded-full">High BP</span><span className="font-caption text-caption text-on-error-container/80">2 days overdue</span></div><div className="font-headline-md text-headline-md text-on-error-container mt-xs">Anjali Devi</div><div className="font-body-md text-body-md text-on-error-container/80">3rd Trimester • Ward 4</div><button className="mt-sm bg-error text-white font-label-md text-label-md px-md py-sm rounded-full w-full shadow-sm hover:bg-red-800 transition-colors active:scale-95">Follow Up Now</button></div></div><div className="min-w-[280px] bg-error-container rounded-xl p-md border border-error/20 shadow-sm snap-center relative overflow-hidden flex flex-col gap-xs"><div className="absolute left-0 top-0 bottom-0 w-2 bg-[#FF8C00]"></div>
<div className="pl-sm"><div className="flex justify-between items-start"><span className="font-label-md text-label-md text-on-error-container bg-error/10 px-2 py-1 rounded-full">Severe Malnutrition</span><span className="font-caption text-caption text-on-error-container/80">Today</span></div><div className="font-headline-md text-headline-md text-on-error-container mt-xs">Raju Kumar</div><div className="font-body-md text-body-md text-on-error-container/80">2 years • Ward 1</div><button className="mt-sm bg-[#FF8C00] text-white font-label-md text-label-md px-md py-sm rounded-full w-full shadow-sm hover:bg-orange-700 transition-colors active:scale-95">Review Status</button></div></div></div></section>
<section className="flex flex-col gap-sm"><h2 className="font-headline-md text-headline-md text-on-background">Today's Visits</h2><div className="flex flex-col gap-md">
<div className="bg-surface-container-lowest rounded-xl p-md border border-outline-variant shadow-sm relative overflow-hidden flex items-center justify-between"><div className="absolute left-0 top-0 bottom-0 w-2 bg-secondary"></div><div className="pl-sm flex flex-col gap-xs"><span className="font-label-md text-label-md text-on-surface-variant bg-surface-container px-2 py-1 rounded-full w-fit">ANC Checkup</span><div className="font-headline-lg-mobile text-headline-lg-mobile text-on-surface">Sunita Patel</div><div className="font-body-md text-body-md text-on-surface-variant flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">location_on</span> Ward 3, Main Street
                        </div></div><button className="p-sm rounded-full bg-primary-container text-on-primary-container hover:bg-primary transition-colors active:scale-95 shadow-sm"><span className="material-symbols-outlined">directions_walk</span></button></div>
<div className="bg-surface-container-lowest rounded-xl p-md border border-outline-variant shadow-sm relative overflow-hidden flex items-center justify-between"><div className="absolute left-0 top-0 bottom-0 w-2 bg-secondary"></div><div className="pl-sm flex flex-col gap-xs"><span className="font-label-md text-label-md text-on-surface-variant bg-surface-container px-2 py-1 rounded-full w-fit">Newborn Visit</span><div className="font-headline-lg-mobile text-headline-lg-mobile text-on-surface">Meena Kumari</div><div className="font-body-md text-body-md text-on-surface-variant flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">location_on</span> Ward 5, East Colony
                        </div></div><button className="p-sm rounded-full bg-primary-container text-on-primary-container hover:bg-primary transition-colors active:scale-95 shadow-sm"><span className="material-symbols-outlined">directions_walk</span></button></div></div></section>
<section className="flex flex-col gap-sm"><div className="flex justify-between items-center"><h2 className="font-headline-md text-headline-md text-on-background">Pending Tasks</h2><Link to="/asha/tasks" className="font-label-md text-label-md text-primary">View All</Link></div><div className="bg-surface-container-lowest rounded-xl border border-outline-variant shadow-sm flex flex-col">{tasks.map((t) => (
<div key={t.id} className={`p-md flex items-center justify-between border-b border-outline-variant ${t.done ? 'opacity-50' : ''}`}><div className="flex items-center gap-sm"><div className="w-10 h-10 rounded-full bg-tertiary-container text-on-tertiary-container flex items-center justify-center"><span className="material-symbols-outlined">{t.icon}</span></div><div className="flex flex-col"><span className={`font-label-md text-label-md text-on-surface ${t.done ? 'line-through' : ''}`}>{t.title}</span><span className="font-caption text-caption text-on-surface-variant">{t.subtitle}</span></div></div><button onClick={() => toggleTask(t.id)} className={`text-primary p-xs hover:bg-surface-variant rounded-full active:scale-95`} aria-label={t.done ? 'Mark as pending' : 'Mark as done'}><span className="material-symbols-outlined" style={{ fontVariationSettings: t.done ? '\'FILL\' 1' : '\'FILL\' 0' }}>{t.done ? 'check_circle' : 'radio_button_unchecked'}</span></button></div>
))}</div></section></main>
<nav className="bg-surface-container dark:bg-surface-container text-primary dark:text-primary-fixed-dim font-label-md text-label-md font-headline-md text-headline-md text-primary bg-surface-container dark:bg-surface-container shadow-lg fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-sm py-sm md:hidden"><button className="flex flex-col items-center justify-center bg-primary-container dark:bg-primary-container text-on-primary-container dark:text-on-primary-container rounded-full px-lg py-xs hover:bg-surface-variant dark:hover:bg-surface-variant active:scale-95 transition-all duration-150"><span className="material-symbols-outlined filled">home</span><span className="font-label-md text-label-md mt-xs">Home</span></button><button className="flex flex-col items-center justify-center text-on-surface-variant dark:text-on-surface-variant px-lg py-xs hover:bg-surface-variant dark:hover:bg-surface-variant active:scale-95 transition-all duration-150"><span className="material-symbols-outlined">group</span><span className="font-label-md text-label-md mt-xs">Households</span></button><button className="flex flex-col items-center justify-center text-on-surface-variant dark:text-on-surface-variant px-lg py-xs hover:bg-surface-variant dark:hover:bg-surface-variant active:scale-95 transition-all duration-150"><span className="material-symbols-outlined">person</span><span className="font-label-md text-label-md mt-xs">Patients</span></button><button className="flex flex-col items-center justify-center text-on-surface-variant dark:text-on-surface-variant px-lg py-xs hover:bg-surface-variant dark:hover:bg-surface-variant active:scale-95 transition-all duration-150"><span className="material-symbols-outlined">assignment</span><span className="font-label-md text-label-md mt-xs">Tasks</span></button><button className="flex flex-col items-center justify-center text-on-surface-variant dark:text-on-surface-variant px-lg py-xs hover:bg-surface-variant dark:hover:bg-surface-variant active:scale-95 transition-all duration-150"><span className="material-symbols-outlined">account_circle</span><span className="font-label-md text-label-md mt-xs">Profile</span></button></nav>
    </>
  )
}
