import { Link } from 'react-router-dom'
export default function AshaPerformanceReportPhcAdmin() {
  return (
    <>
<header className="fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target md:px-lg bg-surface dark:bg-on-background border-b border-outline-variant dark:border-outline shadow-sm"><div className="flex items-center gap-sm"><h1 className="text-headline-md font-headline-md font-bold text-primary dark:text-primary-fixed-dim">ASHA Sathi</h1></div><div className="flex items-center gap-md"><nav className="hidden md:flex gap-lg h-full"><Link className="h-full flex items-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors font-label-md text-label-md px-2" to="/phc/dashboard">Home</Link><Link className="h-full flex items-center text-primary dark:text-primary-fixed-dim font-bold border-b-2 border-primary hover:bg-surface-container dark:hover:bg-surface-container-highest transition-colors font-label-md text-label-md px-2" to="/phc/reports/maternal">Reports</Link></nav><button className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-surface-container-highest text-on-surface-variant"><span className="material-symbols-outlined" data-icon="sync">sync</span></button><button className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-surface-container-highest text-on-surface-variant"><span className="material-symbols-outlined" data-icon="notifications">notifications</span></button><img alt="User Profile" className="w-8 h-8 rounded-full border border-outline-variant cursor-pointer" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAP_QShQ39oCl0e9j0DyLj_ZjfAtt_cy6BQVK2iHVFWrRoHieW2Nwz0cp3S1B5AFN68ZOYKvCenqnHSptZbpV8CGap-TRPzJYqEEiIhoZCtiJGe1zhIvk-puHv-RB7WJDfgUvvkpj2_rP1iu2FRXx3ELYh3jwjHFGWKv9eaQ2KdN8IeQ1X7uVyBPCY48kL_v5eamom9RAzaJzfwRmvlr6yqx3bIVCUkEoFo-Kdhx1G03uQHHhOcB7oseA" /></div></header>
<aside className="hidden md:flex flex-col h-screen fixed left-0 top-0 p-md gap-sm bg-surface-container-low dark:bg-inverse-surface border-r border-outline-variant w-64 pt-[calc(48px+16px)] z-40"><div className="mb-lg"><h2 className="font-headline-md text-headline-md font-black text-primary">Admin Portal</h2><p className="font-caption text-caption text-on-surface-variant">District Health Office</p></div><nav className="flex-1 flex flex-col gap-unit"><Link className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="dashboard">dashboard</span>
                Dashboard
            </Link><Link className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" to="/phc/ashas"><span className="material-symbols-outlined" data-icon="groups">groups</span>
                Workers
            </Link><Link className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" to="/phc/beneficiaries"><span className="material-symbols-outlined" data-icon="person_celebrate">person_celebrate</span>
                Beneficiaries
            </Link><Link className="flex items-center gap-sm p-sm rounded-lg bg-secondary-container dark:bg-secondary text-on-secondary-container dark:text-on-secondary font-bold transition-transform duration-150 scale-95 font-label-md text-label-md" to="/phc/reports/maternal"><span className="material-symbols-outlined" data-icon="analytics" style={{ fontVariationSettings: '\'FILL\' 1' }}>analytics</span>
                Reports
            </Link><Link className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" to="/phc/vaccination"><span className="material-symbols-outlined" data-icon="inventory_2">inventory_2</span>
                Inventory
            </Link></nav><button className="bg-primary-container text-on-primary-container font-label-md text-label-md py-2 px-4 rounded-full flex items-center justify-center gap-sm hover:opacity-90 transition-opacity mt-auto mb-md"><span className="material-symbols-outlined">add</span>
            Add New Worker
        </button><div className="flex flex-col gap-unit border-t border-outline-variant pt-sm"><a className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" href="#"><span className="material-symbols-outlined" data-icon="settings">settings</span>
                Settings
            </a><a className="flex items-center gap-sm p-sm rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all font-label-md text-label-md" href="#"><span className="material-symbols-outlined" data-icon="help">help</span>
                Support
            </a></div></aside>
<main className="pt-[calc(48px+24px)] md:pl-64 px-sm md:px-lg pb-xxl min-h-screen"><div className="max-w-7xl mx-auto">
<div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-lg gap-md"><div><h2 className="font-headline-lg-mobile text-headline-lg-mobile md:font-headline-lg md:text-headline-lg text-on-surface">ASHA Performance & Activity</h2><p className="font-body-md text-body-md text-on-surface-variant mt-unit">Monitor field worker metrics and reporting compliance.</p></div><div className="flex flex-wrap gap-sm w-full md:w-auto"><div className="relative w-full md:w-48"><select className="w-full h-touch-target md:h-10 bg-surface border border-outline-variant rounded-lg pl-sm pr-lg text-on-surface font-body-md focus:ring-primary focus:border-primary appearance-none"><option>All ASHA Workers</option><option>Sunita Devi</option><option>Geeta Rani</option><option>Kamla Bai</option></select><span className="material-symbols-outlined absolute right-sm top-1/2 -translate-y-1/2 text-on-surface-variant pointer-events-none">arrow_drop_down</span></div><div className="relative w-full md:w-40"><select className="w-full h-touch-target md:h-10 bg-surface border border-outline-variant rounded-lg pl-sm pr-lg text-on-surface font-body-md focus:ring-primary focus:border-primary appearance-none"><option>October 2023</option><option>September 2023</option><option>August 2023</option></select><span className="material-symbols-outlined absolute right-sm top-1/2 -translate-y-1/2 text-on-surface-variant pointer-events-none">arrow_drop_down</span></div><button className="h-touch-target md:h-10 px-md bg-primary text-on-primary rounded-lg font-label-md text-label-md flex items-center justify-center gap-sm hover:opacity-90 transition-opacity w-full md:w-auto"><span className="material-symbols-outlined">download</span>
                        Export
                    </button></div></div>
<div className="grid grid-cols-1 md:grid-cols-3 gap-md mb-lg">
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm relative overflow-hidden flex flex-col justify-between min-h-[140px]"><div className="flex justify-between items-start"><h3 className="font-label-md text-label-md text-on-surface-variant">Avg. Household Visits/Day</h3><span className="material-symbols-outlined text-primary-container bg-primary-container/10 p-unit rounded-full">directions_walk</span></div><div className="mt-md"><span className="font-display-lg text-display-lg text-on-surface">12.4</span><span className="font-caption text-caption text-secondary ml-unit flex items-center inline-flex"><span className="material-symbols-outlined text-[16px]">trending_up</span> +2.1 vs last month
                        </span></div>
<div className="absolute -right-4 -bottom-4 w-24 h-24 bg-primary-container/5 rounded-full blur-xl pointer-events-none"></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm relative overflow-hidden flex flex-col justify-between min-h-[140px]"><div className="flex justify-between items-start"><h3 className="font-label-md text-label-md text-on-surface-variant">Referral Success Rate</h3><span className="material-symbols-outlined text-secondary-container bg-secondary-container/20 p-unit rounded-full text-on-secondary-container">local_hospital</span></div><div className="mt-md"><span className="font-display-lg text-display-lg text-on-surface">87%</span><span className="font-caption text-caption text-on-surface-variant ml-unit">Target: 85%</span></div><div className="absolute -right-4 -bottom-4 w-24 h-24 bg-secondary-container/10 rounded-full blur-xl pointer-events-none"></div></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm relative overflow-hidden flex flex-col justify-between min-h-[140px]"><div className="flex justify-between items-start"><h3 className="font-label-md text-label-md text-on-surface-variant">Reporting Timeliness</h3><span className="material-symbols-outlined text-tertiary-container bg-tertiary-container/10 p-unit rounded-full">schedule</span></div><div className="mt-md"><span className="font-display-lg text-display-lg text-on-surface">92%</span><span className="font-caption text-caption text-error ml-unit flex items-center inline-flex"><span className="material-symbols-outlined text-[16px]">trending_down</span> -1.5% vs last month
                        </span></div><div className="absolute -right-4 -bottom-4 w-24 h-24 bg-tertiary-container/5 rounded-full blur-xl pointer-events-none"></div></div></div><div className="grid grid-cols-1 lg:grid-cols-3 gap-md mb-lg">
<div className="lg:col-span-1 bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm"><h3 className="font-headline-md text-headline-md text-on-surface mb-sm">Top 5: Visits vs. Targets</h3><div className="h-64 flex items-end justify-between gap-unit pt-md pb-xs border-b border-outline-variant">
<div className="flex flex-col items-center gap-xs w-full"><div className="relative w-full h-full flex items-end justify-center"><div className="w-1/3 bg-surface-variant rounded-t-sm h-[90%] mx-px" title="Target: 90"></div><div className="w-1/3 bg-primary rounded-t-sm h-[95%] mx-px" title="Actual: 95"></div></div><span className="font-caption text-caption text-on-surface-variant truncate w-full text-center">Sunita</span></div><div className="flex flex-col items-center gap-xs w-full"><div className="relative w-full h-full flex items-end justify-center"><div className="w-1/3 bg-surface-variant rounded-t-sm h-[90%] mx-px" title="Target: 90"></div><div className="w-1/3 bg-primary rounded-t-sm h-[85%] mx-px" title="Actual: 85"></div></div><span className="font-caption text-caption text-on-surface-variant truncate w-full text-center">Geeta</span></div><div className="flex flex-col items-center gap-xs w-full"><div className="relative w-full h-full flex items-end justify-center"><div className="w-1/3 bg-surface-variant rounded-t-sm h-[80%] mx-px" title="Target: 80"></div><div className="w-1/3 bg-primary rounded-t-sm h-[88%] mx-px" title="Actual: 88"></div></div><span className="font-caption text-caption text-on-surface-variant truncate w-full text-center">Kamla</span></div><div className="flex flex-col items-center gap-xs w-full"><div className="relative w-full h-full flex items-end justify-center"><div className="w-1/3 bg-surface-variant rounded-t-sm h-[75%] mx-px" title="Target: 75"></div><div className="w-1/3 bg-primary rounded-t-sm h-[70%] mx-px" title="Actual: 70"></div></div><span className="font-caption text-caption text-on-surface-variant truncate w-full text-center">Radha</span></div><div className="flex flex-col items-center gap-xs w-full"><div className="relative w-full h-full flex items-end justify-center"><div className="w-1/3 bg-surface-variant rounded-t-sm h-[85%] mx-px" title="Target: 85"></div><div className="w-1/3 bg-primary rounded-t-sm h-[92%] mx-px" title="Actual: 92"></div></div><span className="font-caption text-caption text-on-surface-variant truncate w-full text-center">Meena</span></div></div><div className="flex justify-center gap-md mt-sm"><div className="flex items-center gap-xs"><div className="w-3 h-3 bg-surface-variant rounded-sm"></div><span className="font-caption text-caption text-on-surface-variant">Target</span></div><div className="flex items-center gap-xs"><div className="w-3 h-3 bg-primary rounded-sm"></div><span className="font-caption text-caption text-on-surface-variant">Actual</span></div></div></div>
<div className="lg:col-span-2 bg-surface-container-lowest border border-outline-variant rounded-xl p-0 shadow-sm overflow-hidden flex flex-col"><div className="p-md border-b border-outline-variant flex justify-between items-center bg-surface-container-lowest"><h3 className="font-headline-md text-headline-md text-on-surface">Worker Detail View</h3><div className="relative hidden sm:block"><span className="material-symbols-outlined absolute left-sm top-1/2 -translate-y-1/2 text-on-surface-variant text-[20px]">search</span><input className="h-8 pl-8 pr-sm py-1 bg-surface border border-outline-variant rounded-md text-on-surface font-body-md text-sm focus:ring-primary focus:border-primary w-48" placeholder="Search worker..." type="text" /></div></div><div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="bg-surface-container-low border-b border-outline-variant"><th className="p-sm font-label-md text-label-md text-on-surface-variant font-semibold pl-md">Worker Name</th><th className="p-sm font-label-md text-label-md text-on-surface-variant font-semibold">Assigned HH</th><th className="p-sm font-label-md text-label-md text-on-surface-variant font-semibold">Total Visits</th><th className="p-sm font-label-md text-label-md text-on-surface-variant font-semibold">High-Risk Cases</th><th className="p-sm font-label-md text-label-md text-on-surface-variant font-semibold pr-md">Score</th></tr></thead><tbody className="font-body-md text-body-md text-on-surface"><tr className="border-b border-outline-variant/50 hover:bg-surface-container-lowest transition-colors h-10"><td className="p-sm pl-md flex items-center gap-sm"><div className="w-2 h-full absolute left-0 top-0 bg-secondary rounded-l-md" style={{ height: '100%', width: '4px', display: 'none' }}></div>
<img alt="Worker Avatar" className="w-6 h-6 rounded-full hidden sm:block" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBmdqUFoNgXzK5neNTBQxWIg1QmvGPESZJTgVoeLeFyW8-ies55tdtC3pVpE_IRDGFMVuak01YRYC0UJzNqAS4gP9mgq_SN_OfNNydG0BEqi5u-XE-Zr4bdAunNxwmZ2cDrQhP0lEBDjXBjSEmVU8DPpXDL4_-PCf1u3KINIZCPuwXBoQYR3AxXUANOsKXWfdwj0PWuzEb4QLJk3A_TJXTGinE9LBvF9mNhiqoyVk9e-D-XU1w_t8aq5Q" />
                                        Sunita Devi
                                    </td><td className="p-sm">145</td><td className="p-sm">312</td><td className="p-sm"><span className="inline-flex items-center gap-xs px-2 py-0.5 rounded-full bg-error-container text-on-error-container font-label-md text-[12px]">
                                            12
                                        </span></td><td className="p-sm pr-md"><div className="flex items-center gap-sm"><div className="flex-1 h-2 bg-surface-variant rounded-full overflow-hidden w-16"><div className="h-full bg-secondary w-[92%]"></div></div><span className="text-sm font-semibold">92</span></div></td></tr><tr className="border-b border-outline-variant/50 hover:bg-surface-container-lowest transition-colors bg-surface/30 h-10"><td className="p-sm pl-md flex items-center gap-sm relative"><div className="absolute left-0 top-0 h-full w-1 bg-error"></div><img alt="Worker Avatar" className="w-6 h-6 rounded-full hidden sm:block" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAbDxUYlJwVGNaTCD1JWK3BRdTIYtRzKBhphmdSLU-yX8mK3BELPthmP_1w30IQQ7Y-t1L4NpIInpmiD3IKaxBqrxouBipQ-24tIMwbQDqcDuPoD_zqiv23yMvtAWBWtzuajuuRR_9HrSXfoEMF5SGAdOhFTkhLc9qIknW7c89NB29gbyhZGslac4lXudFRtMuID-tzFcd-2wXKYQoymsFgsqf0wNshnKmF_BvBzXLavsD6MoF-k3_EDA" />
                                        Geeta Rani
                                    </td><td className="p-sm">120</td><td className="p-sm">250</td><td className="p-sm"><span className="inline-flex items-center gap-xs px-2 py-0.5 rounded-full bg-error-container text-on-error-container font-label-md text-[12px]">
                                            24
                                        </span></td><td className="p-sm pr-md"><div className="flex items-center gap-sm"><div className="flex-1 h-2 bg-surface-variant rounded-full overflow-hidden w-16"><div className="h-full bg-primary w-[85%]"></div></div><span className="text-sm font-semibold">85</span></div></td></tr><tr className="border-b border-outline-variant/50 hover:bg-surface-container-lowest transition-colors h-10"><td className="p-sm pl-md flex items-center gap-sm relative"><div className="absolute left-0 top-0 h-full w-1 bg-secondary"></div><img alt="Worker Avatar" className="w-6 h-6 rounded-full hidden sm:block" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBBm7-UM2SGJV-EyPADEJgvrfHJ693YZ1KnKCN6-UDQhX9muPM0I4yneQOQQ8OuLB3rmt_CcQvLfzARtdXg5J3aXrUyfHmgxxALxIU42psqCMJ4rXQSyq1XWlpNcCJ6YfYiYCShIFQPXyIuUsJ6vELprFE6Pe8BEOjEU6LeeouehI225Ks5IsKg8fVngSy6tMENNkDRiByvUqNItm0f7SQ1PSm_G0scSzbGrsssBB4nkUEvF1OnTNefoA" />
                                        Kamla Bai
                                    </td><td className="p-sm">160</td><td className="p-sm">340</td><td className="p-sm"><span className="inline-flex items-center gap-xs px-2 py-0.5 rounded-full bg-surface-container-high text-on-surface font-label-md text-[12px]">
                                            5
                                        </span></td><td className="p-sm pr-md"><div className="flex items-center gap-sm"><div className="flex-1 h-2 bg-surface-variant rounded-full overflow-hidden w-16"><div className="h-full bg-secondary w-[95%]"></div></div><span className="text-sm font-semibold">95</span></div></td></tr><tr className="hover:bg-surface-container-lowest transition-colors bg-surface/30 h-10"><td className="p-sm pl-md flex items-center gap-sm relative"><div className="absolute left-0 top-0 h-full w-1 bg-secondary-container"></div><img alt="Worker Avatar" className="w-6 h-6 rounded-full hidden sm:block" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAxgDlZc4U_a1ERQvkl2oFdFuH6vzePQesODg4bpDfrnxXW5x7osNdwshqaT6GJCdqP0d8VJQ71NrWiTYvugvc-P8qvAIKMBDphlkPmuBPL_3QZr19nNjNk__OyplDmfgbZZW5hXAKrpDyRxBfHWUJBxyjv0MmfIor_KS4vKAr2vRii9EKn-Q7Hylw08eDmAIxP9-udPXcegqCW7QnR8YXwASjdhvucDV0Q9mHJkOBn8DkgjE5wMxY59w" />
                                        Radha Kumari
                                    </td><td className="p-sm">95</td><td className="p-sm">180</td><td className="p-sm"><span className="inline-flex items-center gap-xs px-2 py-0.5 rounded-full bg-error-container text-on-error-container font-label-md text-[12px]">
                                            8
                                        </span></td><td className="p-sm pr-md"><div className="flex items-center gap-sm"><div className="flex-1 h-2 bg-surface-variant rounded-full overflow-hidden w-16"><div className="h-full bg-secondary-container w-[78%]"></div></div><span className="text-sm font-semibold">78</span></div></td></tr></tbody></table></div></div></div></div></main>
<nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-sm py-xs bg-surface dark:bg-on-background border-t border-outline-variant shadow-lg rounded-t-full pb-[env(safe-area-inset-bottom)]"><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant p-2 rounded-lg" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="home">home</span><span className="font-label-md text-[10px]">Home</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant p-2 rounded-lg" to="/phc/households"><span className="material-symbols-outlined" data-icon="cottage">cottage</span><span className="font-label-md text-[10px]">Households</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant p-2 rounded-lg" to="/phc/beneficiaries"><span className="material-symbols-outlined" data-icon="person_search">person_search</span><span className="font-label-md text-[10px]">Patients</span></Link><Link className="flex flex-col items-center justify-center bg-primary-container dark:bg-primary text-on-primary-container dark:text-on-primary rounded-full px-4 py-1 scale-90 transition-transform duration-200" to="/phc/reports/maternal"><span className="material-symbols-outlined" data-icon="assignment_turned_in">assignment_turned_in</span><span className="font-label-md text-[10px]">Reports</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-highest dark:hover:bg-surface-variant p-2 rounded-lg" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="account_circle">account_circle</span><span className="font-label-md text-[10px]">Profile</span></Link></nav>
    </>
  )
}
