import { Link } from 'react-router-dom'
export default function AshaWorkerProfileSunitaDevi() {
  return (
    <>
<header className="fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target md:px-lg bg-surface dark:bg-on-background shadow-sm"><div className="flex items-center gap-sm"><span className="text-headline-md font-headline-md font-bold text-primary dark:text-primary-fixed-dim">ASHA Sathi</span></div><div className="flex items-center gap-sm"><button aria-label="sync" className="w-touch-target h-touch-target flex items-center justify-center text-on-surface-variant hover:bg-surface-container transition-colors rounded-full rounded-full"><span className="material-symbols-outlined">sync</span></button><button aria-label="notifications" className="w-touch-target h-touch-target flex items-center justify-center text-on-surface-variant hover:bg-surface-container transition-colors rounded-full"><span className="material-symbols-outlined">notifications</span></button><img alt="User Profile" className="w-8 h-8 rounded-full object-cover border border-outline-variant ml-2" data-alt="A small circular avatar placeholder image for a user profile in a healthcare application, simple flat design." src="https://lh3.googleusercontent.com/aida-public/AB6AXuDEVp1zZ3Ktn1P3f4_RrWs3X7lCB3Rj9TBC_JplKSNrPyWp5EBfQgcHqLhYvZAX1LtXNn7WcHK5GInjleKpSSfyttNurDBZIUn0kNpRTu1ZqzaTsI3aoroa-X0t5tG9TMxbmGWK8IYW_ivdACA7ez83tPILWDBZKMXX3Clty-u1KsUyuE3M-SI_c8He9IBiryZ03iFGXCz0q-_Qsxkw2qrBG8oOR27TwoZps313GgaT8quCSDG1Jxy7VQ" /></div></header>
<nav className="hidden md:flex flex-col h-screen fixed left-0 top-0 p-md gap-sm bg-surface-container-low dark:bg-inverse-surface w-64 pt-20 z-40"><div className="flex flex-col mb-xl px-sm"><div className="flex items-center gap-sm mb-2"><img alt="Admin Avatar" className="w-10 h-10 rounded-full object-cover" data-alt="A professional headshot of an administrative healthcare worker, suitable for an admin portal sidebar header." src="https://lh3.googleusercontent.com/aida-public/AB6AXuA7rdeSX9dpvunKFth_PRTQnwo-WYyeo3PnZkA3ynZgZaox-hakUz1SPBW8vyiFGcJsX-o9o-K6mxBcwgRfe5zk4Z_0r0YyP05fUTaRIBGOX0J2bD16yu4Qfr7ChXgJ_-BYI11-gsyUZbGfCM8bNIThhozAjBtGlW5O8fiHQRnTM6WgKaimuBvZouPh8tsMLjfgvvneS6sgDre2_zpm78wcXczO0pW5CPEV0RW4YLCSpe2wehRu2VdVYw" /><div><div className="font-headline-md text-headline-md font-bold text-on-surface">Admin Portal</div><div className="font-caption text-caption text-on-surface-variant">District Health Office</div></div></div><button className="mt-md bg-primary-container text-on-primary-container font-label-md text-label-md py-2 px-4 rounded-full flex items-center justify-center gap-xs hover:bg-primary hover:text-on-primary transition-colors"><span className="material-symbols-outlined">add</span>
                 Add New Worker
             </button></div><div className="flex flex-col gap-1 flex-1"><Link className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" to="/phc/dashboard"><span className="material-symbols-outlined">dashboard</span><span className="font-label-md text-label-md">Dashboard</span></Link><Link className="flex items-center gap-md px-4 py-3 bg-secondary-container dark:bg-secondary text-on-secondary-container dark:text-on-secondary font-bold rounded-lg scale-95 transition-transform duration-150" to="/phc/ashas"><span className="material-symbols-outlined fill-icon">groups</span><span className="font-label-md text-label-md">Workers</span></Link><Link className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" to="/phc/beneficiaries"><span className="material-symbols-outlined">person_celebrate</span><span className="font-label-md text-label-md">Beneficiaries</span></Link><Link className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" to="/phc/reports/maternal"><span className="material-symbols-outlined">analytics</span><span className="font-label-md text-label-md">Reports</span></Link><Link className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" to="/phc/vaccination"><span className="material-symbols-outlined">inventory_2</span><span className="font-label-md text-label-md">Inventory</span></Link></div><div className="flex flex-col gap-1 mt-auto pb-4"><a className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" href="#"><span className="material-symbols-outlined">settings</span><span className="font-label-md text-label-md">Settings</span></a><a className="flex items-center gap-md px-4 py-3 rounded-lg text-on-surface-variant dark:text-surface-variant hover:bg-surface-container-high transition-all" href="#"><span className="material-symbols-outlined">help</span><span className="font-label-md text-label-md">Support</span></a></div></nav>
<main className="pt-20 pb-24 md:pb-md md:pl-64 min-h-screen"><div className="max-w-7xl mx-auto p-md md:p-lg">
<div className="flex items-center justify-between mb-lg"><Link className="flex items-center text-primary font-label-md text-label-md hover:underline gap-xs" to="/phc/ashas"><span className="material-symbols-outlined text-[20px]">arrow_back</span>
                    Back to Workers List
                </Link><div className="flex items-center gap-xs text-on-surface-variant font-caption text-caption"><span className="w-2 h-2 rounded-full bg-secondary"></span>
                    Last Sync: 10 mins ago
                </div></div>
<div className="grid grid-cols-1 lg:grid-cols-3 gap-md mb-xl">
<div className="bg-surface border border-outline-variant rounded-xl p-lg shadow-[0px_2px_4px_rgba(0,0,0,0.05)] flex flex-col items-center text-center"><div className="relative mb-md"><img alt="Sunita Devi" className="w-24 h-24 rounded-full object-cover border-4 border-surface" data-alt="A professional portrait of an Indian ASHA healthcare worker in a rural setting, wearing a traditional saree with a blue border, smiling warmly, bright natural lighting." src="https://lh3.googleusercontent.com/aida-public/AB6AXuAu6QsSjUT6XV-NgGEfedTWVIxX1STatH1jyOqwVua_QE0R3_aN6cOIOtY1MGFTc8i9vy8UsChVTsc8E9xRCjmXey8GKBBne2ibdybunhQWaX-4yKyAZ2bkVdjjWQ5YX5kxk7IMruoD1dbEh4rubL_UzBb9zeJ_JuWNiFQa_Z5Vx7PvQpe7t-YmCRBZ-7JO-RDFPDgxtDUeTxhLCaDWYeGNM_cGr4GsyRoDl4PUt5i4NyIc8Hmji9_8gA" /><span className="absolute bottom-0 right-0 w-4 h-4 bg-secondary border-2 border-surface rounded-full"></span></div><h1 className="font-headline-lg-mobile text-headline-lg-mobile md:font-headline-lg md:text-headline-lg text-on-surface mb-xs">Sunita Devi</h1><p className="font-body-md text-body-md text-on-surface-variant mb-sm">ASHA Worker ID: AW-2049-BR</p><span className="inline-flex items-center px-3 py-1 rounded-full bg-secondary-container text-on-secondary-container font-label-md text-label-md mb-lg">
                        Active Field Worker
                    </span><div className="w-full flex justify-center gap-sm mt-auto"><button className="bg-primary-container text-on-primary-container px-4 py-2 rounded-full font-label-md text-label-md flex items-center gap-xs hover:bg-primary hover:text-on-primary transition-colors flex-1 justify-center"><span className="material-symbols-outlined text-[18px]">call</span> Call
                        </button><button className="border border-outline-variant text-on-surface px-4 py-2 rounded-full font-label-md text-label-md flex items-center gap-xs hover:bg-surface-container transition-colors flex-1 justify-center"><span className="material-symbols-outlined text-[18px]">mail</span> Message
                        </button></div></div>
<div className="lg:col-span-2 grid grid-cols-1 sm:grid-cols-3 gap-md">
<div className="bg-surface border border-outline-variant rounded-xl p-md shadow-[0px_2px_4px_rgba(0,0,0,0.05)] flex flex-col justify-between"><div className="flex items-center justify-between mb-sm"><span className="material-symbols-outlined text-primary bg-primary-fixed p-2 rounded-lg">cottage</span><span className="font-label-md text-label-md text-secondary">Target: 100%</span></div><div><div className="font-display-lg text-display-lg text-on-surface mb-xs">98%</div><div className="font-body-md text-body-md text-on-surface-variant">Household Coverage</div></div></div>
<div className="bg-surface border border-outline-variant rounded-xl p-md shadow-[0px_2px_4px_rgba(0,0,0,0.05)] flex flex-col justify-between"><div className="flex items-center justify-between mb-sm"><span className="material-symbols-outlined text-tertiary bg-tertiary-fixed p-2 rounded-lg">checklist</span><span className="font-label-md text-label-md text-on-surface-variant">This Month</span></div><div><div className="font-display-lg text-display-lg text-on-surface mb-xs">42<span className="text-headline-md text-on-surface-variant">/45</span></div><div className="font-body-md text-body-md text-on-surface-variant">Visit Completion</div></div><div className="w-full bg-surface-container-high rounded-full h-1.5 mt-md"><div className="bg-tertiary h-1.5 rounded-full" style={{ width: '93%' }}></div></div></div>
<div className="bg-surface border border-outline-variant rounded-xl p-md shadow-[0px_2px_4px_rgba(0,0,0,0.05)] flex flex-col justify-between"><div className="flex items-center justify-between mb-sm"><span className="material-symbols-outlined text-secondary bg-secondary-fixed p-2 rounded-lg">health_and_safety</span></div><div><div className="font-display-lg text-display-lg text-on-surface mb-xs">95%</div><div className="font-body-md text-body-md text-on-surface-variant">High-Risk Accuracy</div></div></div></div></div>
<div className="border-b border-outline-variant mb-lg overflow-x-auto"><nav aria-label="Tabs" className="flex gap-lg min-w-max px-xs"><button className="border-b-2 border-primary text-primary font-label-md text-label-md py-3 px-1 whitespace-nowrap">Overview</button><button className="border-b-2 border-transparent text-on-surface-variant hover:text-on-surface font-label-md text-label-md py-3 px-1 whitespace-nowrap">Assigned Households</button><button className="border-b-2 border-transparent text-on-surface-variant hover:text-on-surface font-label-md text-label-md py-3 px-1 whitespace-nowrap">Visit History</button><button className="border-b-2 border-transparent text-on-surface-variant hover:text-on-surface font-label-md text-label-md py-3 px-1 whitespace-nowrap">Performance Analytics</button></nav></div>
<div className="grid grid-cols-1 md:grid-cols-2 gap-md">
<div className="bg-surface border border-outline-variant rounded-xl p-lg shadow-[0px_2px_4px_rgba(0,0,0,0.05)]"><h2 className="font-headline-md text-headline-md text-on-surface mb-md">Personal Information</h2><div className="space-y-md"><div className="flex flex-col"><span className="font-caption text-caption text-on-surface-variant">Phone Number</span><span className="font-body-md text-body-md text-on-surface">+91 98765 43210</span></div><div className="flex flex-col"><span className="font-caption text-caption text-on-surface-variant">Date of Joining</span><span className="font-body-md text-body-md text-on-surface">12 March 2018 (6 Years)</span></div><div className="flex flex-col"><span className="font-caption text-caption text-on-surface-variant">Primary Language</span><span className="font-body-md text-body-md text-on-surface">Hindi, Bhojpuri</span></div><div className="flex flex-col"><span className="font-caption text-caption text-on-surface-variant">Address</span><span className="font-body-md text-body-md text-on-surface">House 42, Ward 3, Block A, Patna District, Bihar</span></div></div></div>
<div className="bg-surface border border-outline-variant rounded-xl p-lg shadow-[0px_2px_4px_rgba(0,0,0,0.05)]"><h2 className="font-headline-md text-headline-md text-on-surface mb-md">Territory Assignment</h2><div className="mb-lg"><div className="flex items-center justify-between mb-sm"><span className="font-body-md text-body-md text-on-surface font-semibold">Primary Sub-center:</span><span className="font-body-md text-body-md text-on-surface-variant">Danapur PHC</span></div><div className="w-full h-32 bg-surface-container-low rounded-lg flex items-center justify-center border border-outline-variant overflow-hidden relative">
<div className="absolute inset-0 bg-cover bg-center w-full h-full opacity-50" data-alt="A stylized map interface showing a rural district in Bihar, India with highlighted ward boundaries and scattered house icons representing a healthcare worker&#x27;s assigned territory. Light mode map styling with soft blues and greens." data-location="Danapur, Bihar" style={{ backgroundImage: 'url(\'https://lh3.googleusercontent.com/aida-public/AB6AXuD3F7VAyYSHV-AlxzzuVMztSAnSs-4SGyaxwT4dx1eZGv56y1F9MNf47PKSfsIDpW8VjxhoYHfKOtHRTAbAy_UtO14f-W0-RGdqSs5zVU9uRfNWVfgooL7blhc1T1OUoE_y_yYy25V-GuqNCjwxkwwAoEBLYyQyCezluxj-Vy3Y82eWcWMh8CrpOpOib6zANssGsRnh9dX-uTWQoeWKGT1usij7kY1X6yjRsWSjZYubGQtQDXAkIjPF6A\')' }}></div><span className="relative z-10 bg-surface px-3 py-1 rounded-full font-caption text-caption border border-outline-variant shadow-sm flex items-center gap-xs"><span className="material-symbols-outlined text-[16px]">location_on</span> View Map
                             </span></div></div><div><h3 className="font-label-md text-label-md text-on-surface-variant mb-sm">Assigned Wards / Villages</h3><div className="flex flex-wrap gap-sm"><span className="bg-surface-container px-3 py-1 rounded-lg font-body-md text-body-md text-on-surface border border-outline-variant">Ward 3 (East)</span><span className="bg-surface-container px-3 py-1 rounded-lg font-body-md text-body-md text-on-surface border border-outline-variant">Ward 4</span><span className="bg-surface-container px-3 py-1 rounded-lg font-body-md text-body-md text-on-surface border border-outline-variant">Rampur Village</span></div></div></div></div></div></main>
<nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-sm py-xs bg-surface dark:bg-on-background border-t border-outline-variant shadow-lg rounded-t-full pb-safe"><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant w-16 h-12 hover:bg-surface-container-highest dark:hover:bg-surface-variant rounded-xl transition-colors" to="/phc/dashboard"><span className="material-symbols-outlined mb-1">home</span><span className="font-caption text-[10px] leading-tight">Home</span></Link><Link className="flex flex-col items-center justify-center bg-primary-container dark:bg-primary text-on-primary-container dark:text-on-primary rounded-full px-4 py-1 scale-90 transition-transform duration-200" to="/phc/ashas"><span className="material-symbols-outlined fill-icon mb-1">groups</span><span className="font-caption text-[10px] leading-tight font-bold">Workers</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant w-16 h-12 hover:bg-surface-container-highest dark:hover:bg-surface-variant rounded-xl transition-colors" to="/phc/beneficiaries"><span className="material-symbols-outlined mb-1">person_search</span><span className="font-caption text-[10px] leading-tight">Patients</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant w-16 h-12 hover:bg-surface-container-highest dark:hover:bg-surface-variant rounded-xl transition-colors" to="/phc/alerts"><span className="material-symbols-outlined mb-1">assignment_turned_in</span><span className="font-caption text-[10px] leading-tight">Tasks</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant dark:text-surface-variant w-16 h-12 hover:bg-surface-container-highest dark:hover:bg-surface-variant rounded-xl transition-colors" to="/phc/dashboard"><span className="material-symbols-outlined mb-1">account_circle</span><span className="font-caption text-[10px] leading-tight">Profile</span></Link></nav>
    </>
  )
}
