export default function ChildProfilePhcAdmin() {
  return (
    <>
<header className="fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target md:px-lg bg-surface dark:bg-on-background border-b border-outline-variant dark:border-outline shadow-sm"><div className="flex items-center gap-md"><button className="md:hidden flex items-center justify-center text-on-surface-variant hover:bg-surface-container rounded-full w-touch-target h-touch-target transition-colors"><span className="material-symbols-outlined">arrow_back</span></button><div className="font-headline-md text-headline-md font-bold text-primary dark:text-primary-fixed-dim">ASHA Sathi</div></div><div className="flex items-center gap-sm"><button className="flex items-center justify-center text-primary dark:text-primary-fixed-dim hover:bg-surface-container rounded-full w-touch-target h-touch-target transition-colors"><span className="material-symbols-outlined">sync</span></button><button className="flex items-center justify-center text-primary dark:text-primary-fixed-dim hover:bg-surface-container rounded-full w-touch-target h-touch-target transition-colors relative"><span className="material-symbols-outlined">notifications</span><span className="absolute top-2 right-2 w-2 h-2 bg-error rounded-full"></span></button><img alt="User Profile" className="w-8 h-8 rounded-full border border-outline-variant ml-sm" data-alt="A small circular avatar showing a professional female Indian healthcare worker wearing a blue sari, smiling warmly. Bright, clean background, modern corporate healthcare style." src="https://lh3.googleusercontent.com/aida-public/AB6AXuAdH3QFiZc7qsUfZPUdiZAERb2qYkuJFQ7WoAWtyCknNb7qqCryG53uhZo67ppMnLXeNkEbMBgtSVeiYgVfPmc68kGV9oIg2uQzUo2cH3mqeFeO00LYOqpIo4k35dJtJjRG2Td3HZ3Ee_PpejhBWQb89kXzBX0_w6zjDAGgKY3PcekooBvQMmhUafpBaXMuC4s-twHqISly-X5NPK0umUOdVZxWVhsbfoKWx-KRMHoYLMA_UBQKQEcWtA" /></div></header>
<main className="flex-1 pt-[64px] pb-xl px-md md:px-lg max-w-7xl mx-auto w-full flex flex-col gap-lg">
<div className="hidden md:flex items-center gap-sm mt-md text-on-surface-variant font-label-md text-label-md"><button className="hover:text-primary transition-colors flex items-center gap-xs"><span className="material-symbols-outlined text-[18px]">arrow_back</span>
                Back to Beneficiaries
            </button><span>/</span><span>Child Profile</span></div>
<div className="flex flex-col md:flex-row md:items-end justify-between gap-md mt-md md:mt-0"><div className="flex items-center gap-md"><div className="w-20 h-20 md:w-24 md:h-24 rounded-full border-2 border-surface-container-high overflow-hidden shadow-sm relative shrink-0"><img alt="Aarav Kumar Profile Photo" className="w-full h-full object-cover" data-alt="A high-quality, closely cropped portrait of a 2-year-old Indian boy looking slightly tired but calm. He is sitting indoors in a brightly lit rural home with white walls. The lighting is soft and natural, creating a clean, modern, high-contrast healthcare aesthetic. Deep blacks, pristine whites, subtle skin tones." src="https://lh3.googleusercontent.com/aida-public/AB6AXuAq-EHUgaEXg7ItyrztXBcR_ffBL3GI5T9hfWjb8SeQ0CQtTaLfGV-exzRhkapqYl2bssAAV3c_buO0g6w4rVb7jePe8R9575glUbipUn9LlcCQQIDpXz_08WZvk13jFKK1PYyDRh2o5oFucPdFoXODszWs7JPnN0BmwaQGtmyjovEy40V8-V3Pmzo8lN2qEDK5XEQcSqpNV_maAu2tU14hY4npBfSjQKRQD8QHyJFy54JGrJ4wqizGiQ" /></div><div><h1 className="font-headline-lg-mobile text-headline-lg-mobile md:font-headline-lg md:text-headline-lg text-on-surface mb-xs">Aarav Kumar</h1><div className="flex flex-wrap items-center gap-sm font-body-md text-body-md text-on-surface-variant"><span>Male, 2 Years (26 Months)</span><span className="w-1 h-1 bg-outline rounded-full"></span><span>ID: CH-9928-11</span></div><div className="mt-sm flex items-center gap-xs">
<div className="inline-flex items-center gap-xs bg-error-container text-on-error-container font-label-md text-label-md px-md py-xs rounded-full border border-error/20 shadow-sm"><span className="material-symbols-outlined text-[16px] fill">warning</span>
                            High Risk (SAM)
                        </div></div></div></div><div className="flex gap-sm"><button className="flex-1 md:flex-none h-touch-target flex items-center justify-center gap-xs bg-surface-container border border-outline-variant text-primary font-label-md text-label-md px-lg rounded-lg hover:bg-surface-container-high transition-colors shadow-sm"><span className="material-symbols-outlined">edit</span>
                    Edit
                </button><button className="flex-1 md:flex-none h-touch-target flex items-center justify-center gap-xs bg-primary text-on-primary font-label-md text-label-md px-lg rounded-lg hover:opacity-90 transition-opacity shadow-sm"><span className="material-symbols-outlined">add_task</span>
                    Log Visit
                </button></div></div>
<div className="flex overflow-x-auto border-b border-outline-variant hide-scrollbar mt-sm"><button className="px-md py-sm font-label-md text-label-md text-primary font-bold border-b-2 border-primary whitespace-nowrap">
                Summary
            </button><button className="px-md py-sm font-label-md text-label-md text-on-surface-variant hover:bg-surface-container-highest transition-colors whitespace-nowrap">
                Growth Monitoring
            </button><button className="px-md py-sm font-label-md text-label-md text-on-surface-variant hover:bg-surface-container-highest transition-colors whitespace-nowrap">
                Vaccination
            </button><button className="px-md py-sm font-label-md text-label-md text-on-surface-variant hover:bg-surface-container-highest transition-colors whitespace-nowrap">
                Health History
            </button></div>
<div className="grid grid-cols-1 md:grid-cols-12 gap-md">
<div className="md:col-span-8 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm relative overflow-hidden flex flex-col">
<div className="absolute left-0 top-0 bottom-0 w-2 bg-error"></div><div className="p-md md:p-lg pl-xl border-b border-outline-variant flex justify-between items-center bg-surface-bright"><h2 className="font-headline-md text-headline-md text-on-surface flex items-center gap-sm"><span className="material-symbols-outlined text-error">monitor_heart</span>
                        Current Health Status
                    </h2><span className="font-caption text-caption text-on-surface-variant">Last Updated: 2 days ago</span></div><div className="p-md md:p-lg pl-xl flex-1 flex flex-col gap-lg">
<div className="grid grid-cols-2 md:grid-cols-4 gap-md"><div className="bg-error-container/30 p-sm rounded-lg border border-error-container"><div className="font-caption text-caption text-on-surface-variant mb-xs">Weight</div><div className="font-headline-md text-headline-md text-error font-bold flex items-end gap-xs">
                                9.2 <span className="font-body-md text-body-md mb-[2px]">kg</span></div><div className="font-caption text-caption text-error mt-xs flex items-center gap-xs"><span className="material-symbols-outlined text-[14px]">trending_down</span> -0.3kg since last
                            </div></div><div className="bg-surface-container p-sm rounded-lg border border-outline-variant"><div className="font-caption text-caption text-on-surface-variant mb-xs">Height</div><div className="font-headline-md text-headline-md text-on-surface font-bold flex items-end gap-xs">
                                82 <span className="font-body-md text-body-md mb-[2px]">cm</span></div></div><div className="bg-error-container/30 p-sm rounded-lg border border-error-container col-span-2 md:col-span-1"><div className="font-caption text-caption text-on-surface-variant mb-xs">MUAC</div><div className="font-headline-md text-headline-md text-error font-bold flex items-end gap-xs">
                                11.0 <span className="font-body-md text-body-md mb-[2px]">cm</span></div><div className="font-caption text-caption text-error mt-xs">Severe (Red Zone)</div></div><div className="bg-surface-container p-sm rounded-lg border border-outline-variant col-span-2 md:col-span-1"><div className="font-caption text-caption text-on-surface-variant mb-xs">Edema</div><div className="font-headline-md text-headline-md text-on-surface font-bold">
                                Absent
                            </div></div></div>
<div className="bg-surface-bright rounded-lg p-md border border-outline-variant"><h3 className="font-label-md text-label-md text-on-surface mb-xs">Latest Field Notes</h3><p className="font-body-md text-body-md text-on-surface-variant">Child appears lethargic and has poor appetite. Mother reports loose stools for the past 2 days. Weight has dropped below the -3 SD curve. Immediate referral to Nutritional Rehabilitation Centre (NRC) recommended.</p></div></div></div>
<div className="md:col-span-4 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm overflow-hidden flex flex-col"><div className="p-md border-b border-outline-variant bg-surface-bright"><h2 className="font-headline-md text-headline-md text-on-surface">Interventions</h2></div><div className="p-md flex flex-col gap-sm flex-1 bg-surface"><button className="w-full h-touch-target flex items-center justify-between px-md bg-error text-on-error rounded-lg shadow-sm hover:opacity-90 transition-opacity"><div className="flex items-center gap-sm font-label-md text-label-md"><span className="material-symbols-outlined">local_hospital</span>
                            Refer to NRC
                        </div><span className="material-symbols-outlined">chevron_right</span></button><button className="w-full h-touch-target flex items-center justify-between px-md bg-surface-container border border-outline-variant text-primary rounded-lg hover:bg-surface-container-high transition-colors"><div className="flex items-center gap-sm font-label-md text-label-md"><span className="material-symbols-outlined">medication</span>
                            Dispense Supplements
                        </div><span className="material-symbols-outlined">chevron_right</span></button><div className="mt-auto pt-md border-t border-outline-variant"><h3 className="font-label-md text-label-md text-on-surface-variant mb-sm">Upcoming Tasks</h3><div className="flex items-start gap-sm bg-surface-bright p-sm rounded border border-outline-variant border-l-4 border-l-primary"><span className="material-symbols-outlined text-primary text-[20px] mt-[2px]">calendar_today</span><div><div className="font-label-md text-label-md text-on-surface">Follow-up Visit</div><div className="font-caption text-caption text-error">Overdue by 1 day</div></div></div></div></div></div>
<div className="md:col-span-6 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm overflow-hidden"><div className="p-md border-b border-outline-variant bg-surface-bright"><h2 className="font-headline-md text-headline-md text-on-surface flex items-center gap-sm"><span className="material-symbols-outlined text-primary">family_home</span>
                        Household Information
                    </h2></div><div className="p-md grid grid-cols-1 md:grid-cols-2 gap-md"><div><div className="font-caption text-caption text-on-surface-variant mb-xs">Mother's Name</div><div className="font-body-md text-body-md text-on-surface font-semibold">Priya Kumar</div><div className="font-caption text-caption text-primary flex items-center gap-xs mt-[2px]"><span className="material-symbols-outlined text-[14px]">call</span> +91 98765 43210
                        </div></div><div><div className="font-caption text-caption text-on-surface-variant mb-xs">Father's Name</div><div className="font-body-md text-body-md text-on-surface">Rahul Kumar</div></div><div className="md:col-span-2 mt-sm pt-sm border-t border-outline-variant"><div className="font-caption text-caption text-on-surface-variant mb-xs">Address</div><div className="font-body-md text-body-md text-on-surface flex items-start gap-xs"><span className="material-symbols-outlined text-on-surface-variant text-[18px] mt-[2px]">location_on</span>
                            House No. 42, Ward 3, Village Rampur, Block A, District Health.
                        </div></div></div></div>
<div className="md:col-span-6 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm overflow-hidden"><div className="p-md border-b border-outline-variant bg-surface-bright"><h2 className="font-headline-md text-headline-md text-on-surface flex items-center gap-sm"><span className="material-symbols-outlined text-primary">assignment_ind</span>
                        Program Details
                    </h2></div><div className="p-md flex flex-col gap-sm"><div className="flex justify-between items-center py-xs border-b border-outline-variant/50"><span className="font-body-md text-body-md text-on-surface-variant">RCH Number</span><span className="font-body-md text-body-md text-on-surface font-semibold">102938475612</span></div><div className="flex justify-between items-center py-xs border-b border-outline-variant/50"><span className="font-body-md text-body-md text-on-surface-variant">Birth Weight</span><span className="font-body-md text-body-md text-on-surface">2.5 kg</span></div><div className="flex justify-between items-center py-xs"><span className="font-body-md text-body-md text-on-surface-variant">Associated ASHA</span><span className="font-body-md text-body-md text-primary flex items-center gap-xs">
                            Sunita Devi <span className="material-symbols-outlined text-[16px]">info</span></span></div></div></div></div></main>
    </>
  )
}
