import { Link } from 'react-router-dom'
import { LogoutButton } from '@/components/common/LogoutButton'
export default function HealthCheckUpHistoryPhcAdmin() {
  return (
    <>
<aside className="hidden md:flex bg-surface-container-low dark:bg-surface-dim h-screen w-64 fixed left-0 top-0 flex flex-col border-r border-outline-variant dark:border-outline z-50"><div className="p-lg border-b border-outline-variant dark:border-outline flex flex-col items-center"><div className="w-16 h-16 rounded-full bg-primary-container text-on-primary-container flex items-center justify-center mb-sm"><span className="material-symbols-outlined text-3xl">local_hospital</span></div><h1 className="font-headline-md text-headline-md font-extrabold text-primary dark:text-primary-fixed text-center">PHC Administration</h1><p className="font-caption text-caption text-on-surface-variant dark:text-outline-variant text-center">Rural Health Network</p></div><div className="p-md"><button className="w-full bg-primary-container text-on-primary font-label-md text-label-md py-sm px-md rounded-DEFAULT flex items-center justify-center gap-xs shadow-sm hover:bg-surface-tint transition-colors h-[48px]"><span className="material-symbols-outlined">add_chart</span>
                Generate Report
            </button></div><nav className="flex-1 overflow-y-auto py-sm"><ul className="space-y-xs"><li><Link className="flex items-center gap-md px-lg py-sm font-label-md text-label-md text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out h-[48px]" to="/phc/dashboard"><span className="material-symbols-outlined">dashboard</span>
                        Dashboard
                    </Link></li><li><Link className="flex items-center gap-md px-lg py-sm font-label-md text-label-md text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out h-[48px]" to="/phc/ashas"><span className="material-symbols-outlined">groups</span>
                        Workers
                    </Link></li><li><Link className="flex items-center gap-md px-lg py-sm font-label-md text-label-md text-primary dark:text-primary-fixed font-bold border-r-4 border-primary dark:border-primary-fixed bg-surface-container-high dark:bg-surface-container-highest transition-all duration-200 ease-in-out h-[48px]" to="/phc/beneficiaries"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>person</span>
                        Beneficiaries
                    </Link></li><li><Link className="flex items-center gap-md px-lg py-sm font-label-md text-label-md text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out h-[48px]" to="/phc/households"><span className="material-symbols-outlined">home_health</span>
                        Households
                    </Link></li><li><Link className="flex items-center gap-md px-lg py-sm font-label-md text-label-md text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out h-[48px]" to="/phc/maternal"><span className="material-symbols-outlined">pregnant_woman</span>
                        Maternal Health
                    </Link></li><li><Link className="flex items-center gap-md px-lg py-sm font-label-md text-label-md text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out h-[48px]" to="/phc/children"><span className="material-symbols-outlined">child_care</span>
                        Child Health
                    </Link></li><li><Link className="flex items-center gap-md px-lg py-sm font-label-md text-label-md text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out h-[48px]" to="/phc/vaccination"><span className="material-symbols-outlined">inventory_2</span>
                        Inventory
                    </Link></li></ul></nav><div className="border-t border-outline-variant dark:border-outline py-sm"><ul className="space-y-xs"><li><a className="flex items-center gap-md px-lg py-sm font-label-md text-label-md text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out h-[48px]" href="#"><span className="material-symbols-outlined">settings</span>
                        Settings
                    </a></li><li><LogoutButton className="className='flex items-center gap-md px-lg py-sm font-label-md text-label-md text-on-surface-variant dark:text-outline-variant hover:bg-surface-container dark:hover:bg-surface-container-high transition-all duration-200 ease-in-out h-[48px]'"><span className="material-symbols-outlined">logout</span>
                        Logout
                    </LogoutButton></li></ul></div></aside>
<main className="flex-1 md:ml-64 flex flex-col min-h-screen">
<header className="bg-surface-container-lowest dark:bg-inverse-surface w-full top-0 sticky z-40 bg-surface-container-lowest dark:bg-inverse-surface shadow-sm flex justify-between items-center px-lg py-sm h-16"><div className="flex items-center gap-md md:hidden"><button className="text-on-surface-variant dark:text-outline-variant cursor-pointer active:opacity-80 p-sm rounded-full hover:bg-surface-container dark:hover:bg-surface-variant transition-colors"><span className="material-symbols-outlined">menu</span></button><span className="font-headline-md text-headline-md font-bold text-primary dark:text-primary-fixed">PHC Admin Portal</span></div><div className="hidden md:flex items-center flex-1 max-w-md"><div className="relative w-full"><span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant">search</span><input className="w-full bg-surface-container text-on-surface pl-10 pr-4 py-2 rounded-full border-none focus:ring-2 focus:ring-primary font-body-md text-body-md h-[48px] placeholder:text-on-surface-variant" placeholder="Search patients, records..." type="text" /></div></div><div className="flex items-center gap-sm"><button className="text-on-surface-variant dark:text-outline-variant cursor-pointer active:opacity-80 p-sm rounded-full hover:bg-surface-container dark:hover:bg-surface-variant transition-colors"><span className="material-symbols-outlined">sync</span></button><button className="text-on-surface-variant dark:text-outline-variant cursor-pointer active:opacity-80 p-sm rounded-full hover:bg-surface-container dark:hover:bg-surface-variant transition-colors relative"><span className="material-symbols-outlined">notifications</span><span className="absolute top-2 right-2 w-2 h-2 bg-error rounded-full"></span></button><button className="text-on-surface-variant dark:text-outline-variant cursor-pointer active:opacity-80 p-sm rounded-full hover:bg-surface-container dark:hover:bg-surface-variant transition-colors"><span className="material-symbols-outlined">help</span></button><div className="w-10 h-10 rounded-full bg-surface-variant border border-outline-variant overflow-hidden ml-md cursor-pointer"><img alt="Administrator Profile" className="w-full h-full object-cover" data-alt="A professional headshot of an Indian healthcare administrator wearing a crisp collared shirt. The lighting is soft and natural, emphasizing a trustworthy and competent demeanor. The background is a clean, slightly blurred bright clinical office setting." src="https://lh3.googleusercontent.com/aida-public/AB6AXuCA7E4WpXgOFsgIvk_69g_I2UTeVFMOhBr7qtdNG1HeD7aMKe87h2zV3BG02fVkmoU_p04d4QfKdagHdd7FVb9vFcDRMSaWQzArkKkfuFJSBA9nf04bRN0OZ5snIVMfn_nl3QJ1-h4h5xII7gpoTQocaW3Kic0uJ0h979Mti5nTr74zDgQ5VufRTXgH_VAvKY3KV3pXuk1t_8nA8R8E9-aR2DO9-Ykaz6BnB55A8f43WMDMmgkrnrtXiQ" /></div></div></header>
<div className="p-4 md:p-lg lg:p-xl space-y-lg max-w-[1440px] mx-auto w-full">
<div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-md"><div><h2 className="font-display-lg text-display-lg text-on-background">Health Check-up History</h2><p className="font-body-md text-body-md text-on-surface-variant mt-xs">Longitudinal clinical view for Beneficiary #1042</p></div><button className="bg-primary-container text-on-primary font-label-md text-label-md py-sm px-lg rounded-DEFAULT flex items-center justify-center gap-xs shadow-sm hover:bg-surface-tint transition-colors h-[48px]"><span className="material-symbols-outlined">add</span>
                    Record New Check-up
                </button></div>
<div className="grid grid-cols-1 lg:grid-cols-12 gap-lg">
<div className="lg:col-span-4 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm relative overflow-hidden flex flex-col">
<div className="absolute left-0 top-0 bottom-0 w-2 bg-error"></div><div className="p-lg pl-xl flex-1 flex flex-col"><div className="flex items-start gap-md mb-md"><div className="w-16 h-16 rounded-full bg-surface-variant overflow-hidden flex-shrink-0 border-2 border-surface-container-highest"><img alt="Patient Photo" className="w-full h-full object-cover" data-alt="A portrait of an elderly rural Indian woman with weathered, expressive features. She is wearing a traditional sari. The lighting is soft and dignified, capturing resilience. The background is a simple, neutral-toned wall to keep the focus on her face." src="https://lh3.googleusercontent.com/aida-public/AB6AXuDf4o8lspPpVIoiDFlZD5OOLPV0vuKf72lGOZSCR_oSeXpWt60FqJGF8y6YeQHWRrQ-XWCE8QI7bD3Em_d_u-Lp7pgXGUrwo1IKAi-Ft_ga-rQGEawGTFvYe1Jy5Ua9MZ9axO4gRVa5-7RwClD0KhXJ6OUPQLFzkdqoeytODo06qaMJ0K-HS0Cq3xYs-Ms5lCKdiv4-KkMn6IJtNKmplrwFjDOi1Blzb4r8MbjSfwybYWOc86Rgl3bE7g" /></div><div><h3 className="font-headline-lg text-headline-lg text-on-background">Lakshmi Devi</h3><p className="font-body-md text-body-md text-on-surface-variant">Female, 68 yrs</p><span className="inline-block mt-xs px-sm py-xs bg-error-container text-on-error-container font-label-md text-caption rounded-full">
                                    High Risk
                                </span></div></div><div className="grid grid-cols-2 gap-md mb-lg"><div className="bg-surface-container-low p-sm rounded-lg border border-outline-variant"><p className="font-caption text-caption text-on-surface-variant">Blood Type</p><p className="font-headline-md text-headline-md text-on-surface">O+</p></div><div className="bg-surface-container-low p-sm rounded-lg border border-outline-variant"><p className="font-caption text-caption text-on-surface-variant">Primary Condition</p><p className="font-label-md text-label-md text-on-surface">Hypertension</p></div></div><div className="mt-auto space-y-sm border-t border-outline-variant pt-md"><div className="flex items-center gap-sm text-on-surface-variant"><span className="material-symbols-outlined text-xl">location_on</span><span className="font-body-md text-body-md">Village Ramgarh, Ward 4</span></div><div className="flex items-center gap-sm text-on-surface-variant"><span className="material-symbols-outlined text-xl">badge</span><span className="font-body-md text-body-md">Aadhar: XXXX-XXXX-9012</span></div></div></div></div>
<div className="lg:col-span-8 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm p-lg"><div className="flex justify-between items-center mb-md"><h3 className="font-headline-md text-headline-md text-on-background">Blood Pressure Trend</h3><div className="flex gap-2"><select className="bg-surface-container-low border border-outline-variant text-on-surface rounded-DEFAULT py-1 px-3 font-label-md text-caption h-[36px]"><option>Last 6 Months</option><option>Last Year</option></select></div></div>
<div className="w-full h-48 chart-grid relative rounded-lg border border-outline-variant overflow-hidden bg-surface-bright">
<div className="absolute left-2 top-0 bottom-6 flex flex-col justify-between text-caption text-outline py-2"><span>160</span><span>140</span><span>120</span><span>100</span></div>
<div className="absolute bottom-1 left-10 right-2 flex justify-between text-caption text-outline px-4"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span></div>
<svg className="absolute inset-0 w-full h-full" preserveAspectRatio="none"><polyline fill="none" points="50,140 150,120 250,90 350,110 450,60 550,50" stroke="#ba1a1a" stroke-linejoin="round" stroke-width="2"></polyline><circle cx="50" cy="140" fill="#ba1a1a" r="4"></circle><circle cx="150" cy="120" fill="#ba1a1a" r="4"></circle><circle cx="250" cy="90" fill="#ba1a1a" r="4"></circle><circle cx="350" cy="110" fill="#ba1a1a" r="4"></circle><circle cx="450" cy="60" fill="#ba1a1a" r="4"></circle><circle cx="550" cy="50" fill="#ba1a1a" r="4"></circle>
<polyline fill="none" points="50,170 150,160 250,140 350,150 450,120 550,110" stroke="#00478d" stroke-linejoin="round" stroke-width="2"></polyline><circle cx="50" cy="170" fill="#00478d" r="4"></circle><circle cx="150" cy="160" fill="#00478d" r="4"></circle><circle cx="250" cy="140" fill="#00478d" r="4"></circle><circle cx="350" cy="150" fill="#00478d" r="4"></circle><circle cx="450" cy="120" fill="#00478d" r="4"></circle><circle cx="550" cy="110" fill="#00478d" r="4"></circle></svg>
<div className="absolute top-2 right-4 flex gap-4 bg-surface/80 p-1 rounded backdrop-blur-sm"><div className="flex items-center gap-1 font-caption text-caption text-on-surface"><span className="w-2 h-2 rounded-full bg-error"></span> Systolic
                            </div><div className="flex items-center gap-1 font-caption text-caption text-on-surface"><span className="w-2 h-2 rounded-full bg-primary"></span> Diastolic
                            </div></div></div></div>
<div className="lg:col-span-12 bg-surface-container-lowest border border-outline-variant rounded-xl shadow-sm overflow-hidden"><div className="p-md border-b border-outline-variant bg-surface-container-low flex justify-between items-center"><h3 className="font-headline-md text-headline-md text-on-background">Encounter History</h3><button className="text-primary font-label-md text-label-md flex items-center gap-xs hover:bg-surface-container p-xs rounded transition-colors"><span className="material-symbols-outlined text-xl">filter_list</span>
                            Filter
                        </button></div><div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-outline-variant bg-surface-bright"><th className="p-sm px-md font-label-md text-label-md text-on-surface-variant whitespace-nowrap">Date</th><th className="p-sm px-md font-label-md text-label-md text-on-surface-variant">Vitals Summary</th><th className="p-sm px-md font-label-md text-label-md text-on-surface-variant">Primary Symptoms</th><th className="p-sm px-md font-label-md text-label-md text-on-surface-variant">Risk Level</th><th className="p-sm px-md font-label-md text-label-md text-on-surface-variant">Action / Plan</th><th className="p-sm px-md font-label-md text-label-md text-on-surface-variant text-right">Details</th></tr></thead><tbody className="divide-y divide-outline-variant bg-surface-container-lowest">
<tr className="hover:bg-surface-container-low transition-colors group"><td className="p-sm px-md font-body-md text-body-md text-on-surface whitespace-nowrap">
                                        12 Jun 2024
                                        <div className="font-caption text-caption text-on-surface-variant">Dr. Sharma</div></td><td className="p-sm px-md"><div className="font-body-md text-body-md text-on-surface"><span className="font-semibold text-error">BP: 155/95</span></div><div className="font-caption text-caption text-on-surface-variant">Wt: 62kg | Temp: 98.6°F</div></td><td className="p-sm px-md font-body-md text-body-md text-on-surface max-w-xs truncate" title="Severe headache, dizziness, mild chest discomfort">
                                        Severe headache, dizziness, mild chest...
                                    </td><td className="p-sm px-md"><span className="inline-flex items-center gap-1 px-2 py-1 bg-error-container text-on-error-container font-label-md text-caption rounded-full"><span className="w-1.5 h-1.5 rounded-full bg-error"></span> High
                                        </span></td><td className="p-sm px-md font-body-md text-body-md text-on-surface">
                                        Medication adjusted. Referred to CHC.
                                    </td><td className="p-sm px-md text-right"><button className="text-primary p-1 rounded-full hover:bg-surface-variant transition-colors" title="View Full Record"><span className="material-symbols-outlined">chevron_right</span></button></td></tr>
<tr className="hover:bg-surface-container-low transition-colors group"><td className="p-sm px-md font-body-md text-body-md text-on-surface whitespace-nowrap">
                                        28 May 2024
                                        <div className="font-caption text-caption text-on-surface-variant">ASHA Worker</div></td><td className="p-sm px-md"><div className="font-body-md text-body-md text-on-surface"><span className="font-semibold text-tertiary-container">BP: 142/88</span></div><div className="font-caption text-caption text-on-surface-variant">Wt: 63kg | Temp: 98.4°F</div></td><td className="p-sm px-md font-body-md text-body-md text-on-surface max-w-xs truncate" title="Fatigue, occasional mild headache">
                                        Fatigue, occasional mild headache
                                    </td><td className="p-sm px-md"><span className="inline-flex items-center gap-1 px-2 py-1 bg-tertiary-fixed text-on-tertiary-fixed font-label-md text-caption rounded-full"><span className="w-1.5 h-1.5 rounded-full bg-tertiary"></span> Moderate
                                        </span></td><td className="p-sm px-md font-body-md text-body-md text-on-surface">
                                        Advised salt reduction. Follow-up in 2 wks.
                                    </td><td className="p-sm px-md text-right"><button className="text-primary p-1 rounded-full hover:bg-surface-variant transition-colors" title="View Full Record"><span className="material-symbols-outlined">chevron_right</span></button></td></tr>
<tr className="hover:bg-surface-container-low transition-colors group"><td className="p-sm px-md font-body-md text-body-md text-on-surface whitespace-nowrap">
                                        15 Apr 2024
                                        <div className="font-caption text-caption text-on-surface-variant">Dr. Patel</div></td><td className="p-sm px-md"><div className="font-body-md text-body-md text-on-surface"><span className="font-semibold text-secondary">BP: 130/80</span></div><div className="font-caption text-caption text-on-surface-variant">Wt: 64kg | Temp: 98.6°F</div></td><td className="p-sm px-md font-body-md text-body-md text-on-surface max-w-xs truncate" title="Routine check-up, feeling well">
                                        Routine check-up, feeling well
                                    </td><td className="p-sm px-md"><span className="inline-flex items-center gap-1 px-2 py-1 bg-secondary-container text-on-secondary-container font-label-md text-caption rounded-full"><span className="w-1.5 h-1.5 rounded-full bg-secondary"></span> Low
                                        </span></td><td className="p-sm px-md font-body-md text-body-md text-on-surface">
                                        Continue current regimen.
                                    </td><td className="p-sm px-md text-right"><button className="text-primary p-1 rounded-full hover:bg-surface-variant transition-colors" title="View Full Record"><span className="material-symbols-outlined">chevron_right</span></button></td></tr></tbody></table></div></div></div></div></main>
    </>
  )
}
