import { Link } from 'react-router-dom'
import { LogoutButton } from '@/components/common/LogoutButton'
export default function HouseholdDirectoryPhcAdmin() {
  return (
    <>
<nav className="hidden md:flex flex-col fixed left-0 top-0 h-full w-64 pt-xxl pb-lg z-40 bg-surface-container-low dark:bg-surface-container-low border-r border-outline-variant font-label-md text-label-md"><div className="px-lg mb-xl flex items-center gap-md"><div className="w-12 h-12 rounded-full bg-primary-container text-on-primary-container flex items-center justify-center shrink-0"><span className="material-symbols-outlined icon-fill">local_hospital</span></div><div><h1 className="font-headline-lg text-headline-lg text-primary-container dark:text-primary-fixed truncate">PHC Rural Admin</h1><p className="font-caption text-caption text-on-surface-variant truncate">District Division A-12</p></div></div><div className="px-md mb-lg"><button className="w-full flex items-center justify-center gap-sm bg-primary-container text-on-primary-container rounded-lg py-sm px-md font-bold hover:bg-surface-container-highest transition-all active:scale-95 duration-150 shadow-sm"><span className="material-symbols-outlined">sync</span>
                Sync Records
            </button></div><div className="flex-1 overflow-y-auto overflow-x-hidden"><ul className="flex flex-col gap-xs"><li><Link className="flex items-center gap-md text-on-surface-variant dark:text-on-surface-variant mx-sm my-xs px-md py-sm hover:bg-surface-container-highest transition-all active:scale-95 duration-150 rounded-lg" to="/phc/dashboard"><span className="material-symbols-outlined" data-icon="dashboard">dashboard</span>
                        Dashboard
                    </Link></li><li><Link className="flex items-center gap-md text-on-surface-variant dark:text-on-surface-variant mx-sm my-xs px-md py-sm hover:bg-surface-container-highest transition-all active:scale-95 duration-150 rounded-lg" to="/phc/ashas"><span className="material-symbols-outlined" data-icon="groups">groups</span>
                        Workers
                    </Link></li><li><Link className="flex items-center gap-md text-on-surface-variant dark:text-on-surface-variant mx-sm my-xs px-md py-sm hover:bg-surface-container-highest transition-all active:scale-95 duration-150 rounded-lg" to="/phc/beneficiaries"><span className="material-symbols-outlined" data-icon="person_heart">person_heart</span>
                        Beneficiaries
                    </Link></li><li><Link className="flex items-center gap-md bg-primary-container text-on-primary-container rounded-lg mx-sm my-xs px-md py-sm font-bold active:scale-95 duration-150 shadow-sm" to="/phc/households"><span className="material-symbols-outlined icon-fill" data-icon="home_work">home_work</span>
                        Households
                    </Link></li><li><Link className="flex items-center gap-md text-on-surface-variant dark:text-on-surface-variant mx-sm my-xs px-md py-sm hover:bg-surface-container-highest transition-all active:scale-95 duration-150 rounded-lg" to="/phc/maternal"><span className="material-symbols-outlined" data-icon="pregnant_woman">pregnant_woman</span>
                        Maternal Health
                    </Link></li><li><Link className="flex items-center gap-md text-on-surface-variant dark:text-on-surface-variant mx-sm my-xs px-md py-sm hover:bg-surface-container-highest transition-all active:scale-95 duration-150 rounded-lg" to="/phc/vaccination"><span className="material-symbols-outlined" data-icon="inventory_2">inventory_2</span>
                        Inventory
                    </Link></li></ul></div><div className="mt-auto pt-md border-t border-outline-variant/50"><ul className="flex flex-col gap-xs"><li><a className="flex items-center gap-md text-on-surface-variant dark:text-on-surface-variant mx-sm my-xs px-md py-sm hover:bg-surface-container-highest transition-all active:scale-95 duration-150 rounded-lg" href="#"><span className="material-symbols-outlined" data-icon="help">help</span>
                        Support
                    </a></li><li><LogoutButton className="className='flex items-center gap-md text-on-surface-variant dark:text-on-surface-variant mx-sm my-xs px-md py-sm hover:bg-surface-container-highest transition-all active:scale-95 duration-150 rounded-lg'"><span className="material-symbols-outlined" data-icon="logout">logout</span>
                        Logout
                    </LogoutButton></li></ul></div></nav>
<main className="flex-1 flex flex-col md:ml-64 relative bg-background">
<header className="fixed md:sticky top-0 left-0 w-full z-30 flex justify-between items-center px-lg h-touch-target bg-surface-container-lowest border-b border-outline-variant shadow-sm md:w-auto"><div className="flex items-center gap-md w-full max-w-3xl"><button className="md:hidden p-sm -ml-sm text-on-surface-variant"><span className="material-symbols-outlined">menu</span></button><div className="flex-1 flex items-center relative"><span className="material-symbols-outlined absolute left-sm text-outline">search</span><input className="w-full pl-xl pr-md py-sm bg-surface-container-low border-none rounded-full font-body-md text-body-md focus:ring-2 focus:ring-primary-container outline-none h-[40px]" placeholder="Search households..." type="text" /></div></div><div className="hidden md:flex items-center gap-md ml-auto"><button className="p-sm text-outline hover:bg-surface-container-low rounded-full transition-colors"><span className="material-symbols-outlined" data-icon="notifications">notifications</span></button><button className="p-sm text-outline hover:bg-surface-container-low rounded-full transition-colors"><span className="material-symbols-outlined" data-icon="settings">settings</span></button><div className="w-8 h-8 rounded-full bg-surface-variant flex items-center justify-center border border-outline-variant cursor-pointer"><img className="w-full h-full rounded-full object-cover" data-alt="A small, professional circular avatar portrait of a healthcare administrator in a well-lit clinic setting, conveying a sense of calm authority. Modern corporate light mode aesthetic." src="https://lh3.googleusercontent.com/aida-public/AB6AXuA9pq53F1_zJ-fiQekpFjYLhnXddzr-JmEsu9oRTFSSTKIvDelktmNqfRBfQAjJ52DO4Z8tBMV1YHHpQqTBjzVctU0z9T4XEDLO0zL3PXbHl-UyIB0pBWzMzutSJrnfXfTXHYiGOtCL8sT9NXM48ZasHpgpKVndJ9lW62ieCaO2eFoNM6un8raAKFU5rtZUgt-wn48VMYUbfHpuixpqF5qmEgNwlXRJM9VhGF_yRyP9U8r-pC0P94tK3g" /></div></div></header>
<div className="flex-1 overflow-y-auto p-md md:p-lg pt-[64px] md:pt-lg"><div className="flex flex-col md:flex-row md:items-center justify-between gap-md mb-lg"><div><h2 className="font-display-lg text-display-lg text-on-surface">Household Directory</h2><p className="font-body-md text-body-md text-on-surface-variant mt-xs">Manage and monitor all registered households across jurisdictions.</p></div><button className="flex items-center justify-center gap-sm bg-[#005EB8] text-on-primary font-label-md text-label-md rounded-lg px-lg py-sm hover:bg-[#00478d] transition-colors shadow-sm min-h-[48px] whitespace-nowrap"><span className="material-symbols-outlined">add</span>
                    Register New Household
                </button></div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-t-xl p-md flex flex-wrap gap-md items-center justify-between shadow-sm"><div className="flex flex-wrap gap-sm"><select className="bg-surface-container-low border-none rounded-lg px-md py-sm font-label-md text-label-md text-on-surface focus:ring-2 focus:ring-primary-container outline-none h-10 appearance-none pr-xl relative"><option value="">All Villages</option><option value="v1">Rampur</option><option value="v2">Sitapur</option><option value="v3">Govindpur</option></select><select className="bg-surface-container-low border-none rounded-lg px-md py-sm font-label-md text-label-md text-on-surface focus:ring-2 focus:ring-primary-container outline-none h-10 appearance-none pr-xl"><option value="">All Risk Levels</option><option value="high">High Risk</option><option value="medium">Medium Risk</option><option value="low">Low Risk</option></select></div><div className="flex items-center gap-sm text-sm text-on-surface-variant font-label-md"><span className="material-symbols-outlined text-outline">sort</span><span>Sort by: Last Visit (Newest)</span></div></div>
<div className="bg-surface-container-lowest border border-t-0 border-outline-variant rounded-b-xl overflow-x-auto shadow-sm"><table className="w-full text-left border-collapse"><thead className="bg-surface-container text-on-surface-variant font-label-md text-label-md border-b border-outline-variant sticky top-0 z-10"><tr><th className="py-sm px-md font-semibold w-24">HH ID</th><th className="py-sm px-md font-semibold">Head of Family</th><th className="py-sm px-md font-semibold">Village</th><th className="py-sm px-md font-semibold">Assigned ASHA</th><th className="py-sm px-md font-semibold text-center w-24">Members</th><th className="py-sm px-md font-semibold text-center w-32">Risk Status</th><th className="py-sm px-md font-semibold w-32">Last Visit</th><th className="py-sm px-md font-semibold text-right w-16"></th></tr></thead><tbody className="font-body-md text-body-md divide-y divide-outline-variant/30"><tr className="hover:bg-surface-container-low transition-colors group cursor-pointer h-12"><td className="py-sm px-md font-label-md text-primary-container">#HH-4829</td><td className="py-sm px-md font-semibold text-on-surface">Ramesh Kumar</td><td className="py-sm px-md text-on-surface-variant">Rampur</td><td className="py-sm px-md text-on-surface-variant">Sunita Devi</td><td className="py-sm px-md text-center text-on-surface-variant">5</td><td className="py-sm px-md text-center"><span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold bg-error-container text-on-error-container">
                                    2 High Risk
                                </span></td><td className="py-sm px-md text-on-surface-variant font-caption text-caption">12 Oct 2023</td><td className="py-sm px-md text-right"><button className="text-outline hover:text-primary-container opacity-0 group-hover:opacity-100 transition-opacity p-1"><span className="material-symbols-outlined">chevron_right</span></button></td></tr><tr className="hover:bg-surface-container-low transition-colors group cursor-pointer h-12"><td className="py-sm px-md font-label-md text-primary-container">#HH-4830</td><td className="py-sm px-md font-semibold text-on-surface">Sita Sharma</td><td className="py-sm px-md text-on-surface-variant">Sitapur</td><td className="py-sm px-md text-on-surface-variant">Geeta Rani</td><td className="py-sm px-md text-center text-on-surface-variant">3</td><td className="py-sm px-md text-center"><span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold bg-secondary-container text-on-secondary-container">
                                    No Risk
                                </span></td><td className="py-sm px-md text-on-surface-variant font-caption text-caption">10 Oct 2023</td><td className="py-sm px-md text-right"><button className="text-outline hover:text-primary-container opacity-0 group-hover:opacity-100 transition-opacity p-1"><span className="material-symbols-outlined">chevron_right</span></button></td></tr><tr className="hover:bg-surface-container-low transition-colors group cursor-pointer h-12"><td className="py-sm px-md font-label-md text-primary-container">#HH-4831</td><td className="py-sm px-md font-semibold text-on-surface">Mohammad Ali</td><td className="py-sm px-md text-on-surface-variant">Rampur</td><td className="py-sm px-md text-on-surface-variant">Sunita Devi</td><td className="py-sm px-md text-center text-on-surface-variant">7</td><td className="py-sm px-md text-center"><span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold bg-[#fff3cd] text-[#856404]">
                                    1 Medium Risk
                                </span></td><td className="py-sm px-md text-on-surface-variant font-caption text-caption">05 Oct 2023</td><td className="py-sm px-md text-right"><button className="text-outline hover:text-primary-container opacity-0 group-hover:opacity-100 transition-opacity p-1"><span className="material-symbols-outlined">chevron_right</span></button></td></tr><tr className="hover:bg-surface-container-low transition-colors group cursor-pointer h-12"><td className="py-sm px-md font-label-md text-primary-container">#HH-4832</td><td className="py-sm px-md font-semibold text-on-surface">Lakshmi Bai</td><td className="py-sm px-md text-on-surface-variant">Govindpur</td><td className="py-sm px-md text-on-surface-variant">Aarti Patel</td><td className="py-sm px-md text-center text-on-surface-variant">2</td><td className="py-sm px-md text-center"><span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold bg-error-container text-on-error-container">
                                    1 High Risk
                                </span></td><td className="py-sm px-md text-on-surface-variant font-caption text-caption">01 Oct 2023</td><td className="py-sm px-md text-right"><button className="text-outline hover:text-primary-container opacity-0 group-hover:opacity-100 transition-opacity p-1"><span className="material-symbols-outlined">chevron_right</span></button></td></tr><tr className="hover:bg-surface-container-low transition-colors group cursor-pointer h-12"><td className="py-sm px-md font-label-md text-primary-container">#HH-4833</td><td className="py-sm px-md font-semibold text-on-surface">Vikram Singh</td><td className="py-sm px-md text-on-surface-variant">Sitapur</td><td className="py-sm px-md text-on-surface-variant">Geeta Rani</td><td className="py-sm px-md text-center text-on-surface-variant">4</td><td className="py-sm px-md text-center"><span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold bg-secondary-container text-on-secondary-container">
                                    No Risk
                                </span></td><td className="py-sm px-md text-on-surface-variant font-caption text-caption">28 Sep 2023</td><td className="py-sm px-md text-right"><button className="text-outline hover:text-primary-container opacity-0 group-hover:opacity-100 transition-opacity p-1"><span className="material-symbols-outlined">chevron_right</span></button></td></tr></tbody></table></div>
<div className="mt-md flex items-center justify-between px-sm text-on-surface-variant font-caption text-caption"><span>Showing 1 to 5 of 124 Households</span><div className="flex gap-sm"><button className="p-1 rounded hover:bg-surface-container-low disabled:opacity-50" disabled><span className="material-symbols-outlined text-sm">chevron_left</span></button><button className="p-1 rounded hover:bg-surface-container-low"><span className="material-symbols-outlined text-sm">chevron_right</span></button></div></div></div></main>
    </>
  )
}
