import { Link } from 'react-router-dom'
export default function MaternalHealthPhcAdmin() {
  return (
    <>
<nav className="hidden md:flex flex-col h-screen fixed left-0 top-0 p-md gap-sm bg-surface-container-low border-r border-outline-variant docked left-0 h-full w-64 z-50">
<div className="flex items-center gap-md p-md border-b border-outline-variant mb-sm"><img className="w-12 h-12 rounded-full bg-surface-container-highest object-cover shadow-sm" data-alt="A small circular avatar placeholder image for an administrator profile. It features a simple, stylized silhouette of a person on a solid light blue background, representing a generic user. The style is flat, clean, and modern, fitting a corporate healthcare dashboard interface." src="https://lh3.googleusercontent.com/aida-public/AB6AXuDyd9mlsm5t2j8_ii-LGkDkFbBS9wVtisB7b30tFUrAkAwx4aORyq8G1MIyhxof7GHSNgz6_LgboGSsyiawnAN7viu93hAVoGXBqlVzTeU93vLxsY7sj6AKVwm9QUxWl9mD4_WLl7h0_AuDu3HTK_lv36uJNuyG3hB3hwcBpkQr9ZvKCQDDW6wnUfJKY-UHGEwXuEvujOTvTemsCJS5sAGdwcSh77CftYzCWKTw4cZXDV36_UunC9_gBQ" /><div><h1 className="font-headline-md text-headline-md font-black text-primary">Admin Portal</h1><p className="font-label-md text-label-md text-on-surface-variant">District Health Office</p></div></div>
<div className="flex-1 flex flex-col gap-xs overflow-y-auto">
<Link className="flex items-center gap-md px-md py-sm bg-secondary-container text-on-secondary-container font-bold rounded-lg transition-transform duration-150 scale-95 shadow-sm" to="/phc/dashboard"><span className="material-symbols-outlined text-on-secondary-container" style={{ fontVariationSettings: '\'FILL\' 1' }}>dashboard</span><span className="font-label-md text-label-md">Dashboard</span></Link>
<Link className="flex items-center gap-md px-md py-sm text-on-surface-variant hover:bg-surface-container-highest transition-all rounded-lg" to="/phc/ashas"><span className="material-symbols-outlined text-on-surface-variant">groups</span><span className="font-label-md text-label-md">Workers</span></Link><Link className="flex items-center gap-md px-md py-sm text-on-surface-variant hover:bg-surface-container-highest transition-all rounded-lg" to="/phc/beneficiaries"><span className="material-symbols-outlined text-on-surface-variant">person_celebrate</span><span className="font-label-md text-label-md">Beneficiaries</span></Link><Link className="flex items-center gap-md px-md py-sm text-on-surface-variant hover:bg-surface-container-highest transition-all rounded-lg" to="/phc/reports/maternal"><span className="material-symbols-outlined text-on-surface-variant">analytics</span><span className="font-label-md text-label-md">Reports</span></Link><Link className="flex items-center gap-md px-md py-sm text-on-surface-variant hover:bg-surface-container-highest transition-all rounded-lg" to="/phc/vaccination"><span className="material-symbols-outlined text-on-surface-variant">inventory_2</span><span className="font-label-md text-label-md">Inventory</span></Link></div>
<div className="px-md mt-auto mb-sm"><button className="w-full bg-primary-container text-on-primary font-label-md text-label-md py-sm rounded-full shadow-sm hover:opacity-90 transition-opacity flex items-center justify-center gap-sm"><span className="material-symbols-outlined text-[18px]">add</span>
                Add New Worker
            </button></div>
<div className="flex flex-col gap-xs border-t border-outline-variant pt-sm"><a className="flex items-center gap-md px-md py-sm text-on-surface-variant hover:bg-surface-container-highest transition-all rounded-lg" href="#"><span className="material-symbols-outlined text-on-surface-variant">settings</span><span className="font-label-md text-label-md">Settings</span></a><a className="flex items-center gap-md px-md py-sm text-on-surface-variant hover:bg-surface-container-highest transition-all rounded-lg" href="#"><span className="material-symbols-outlined text-on-surface-variant">help</span><span className="font-label-md text-label-md">Support</span></a></div></nav>
<header className="md:hidden fixed top-0 w-full z-50 flex justify-between items-center px-md h-touch-target bg-surface border-b border-outline-variant shadow-sm docked full-width top-0"><div className="flex items-center gap-sm"><span className="material-symbols-outlined text-primary text-[28px]" style={{ fontVariationSettings: '\'FILL\' 1' }}>health_and_safety</span><span className="text-headline-md font-headline-md font-bold text-primary">ASHA Sathi</span></div><div className="flex items-center gap-md"><button className="text-on-surface-variant hover:bg-surface-container p-xs rounded-full transition-colors"><span className="material-symbols-outlined">sync</span></button><button className="text-on-surface-variant hover:bg-surface-container p-xs rounded-full transition-colors relative"><span className="material-symbols-outlined">notifications</span><span className="absolute top-1 right-1 w-2 h-2 bg-error rounded-full"></span></button><img alt="User Profile" className="w-8 h-8 rounded-full bg-surface-container-highest object-cover ml-sm" data-alt="A small circular avatar placeholder image for a mobile profile picture. It features a simple, stylized silhouette of a person on a solid light blue background, representing a generic user." src="https://lh3.googleusercontent.com/aida-public/AB6AXuASCVnU9Zt2QtzV2yqPbzUVizf9gjZiqDxugwM1ACHSqj48e7DAtCAcfYDTqw2KDmwkq8wk7G9YA1zoBxhLUhzjyzmnkkcl2sBMPq8psyGr6K1StimvP5mKA6WYSeaSZ7B_5vQ78BSrDZj8SCMNPLlfc2AnhPI4roiQsYnJ7pbjejBbiOx8PrmeGbcAfncGrz1i7isgR9Q8mrTLNaY3WejaxjCceHQ79m9RiDM-cAw6B19yjppRWaH5lg" /></div></header>
<main className="flex-1 ml-0 md:ml-64 mt-[48px] md:mt-0 p-lg w-full max-w-[1440px] mx-auto min-h-screen pb-24 md:pb-lg">
<div className="flex flex-col md:flex-row justify-between items-start md:items-end mb-xl gap-md"><div><div className="flex items-center gap-sm mb-xs"><span className="material-symbols-outlined text-tertiary-container text-[24px]">pregnant_woman</span><h2 className="font-headline-lg-mobile text-headline-lg-mobile md:font-headline-lg md:text-headline-lg text-on-background">Maternal Health Overview</h2></div><p className="font-body-md text-body-md text-on-surface-variant">Primary Health Center - District Level Dashboard</p></div><div className="flex items-center gap-md bg-surface-container-low px-md py-sm rounded-lg border border-outline-variant"><span className="material-symbols-outlined text-on-surface-variant">calendar_today</span><span className="font-label-md text-label-md text-on-surface-variant">Last 30 Days</span><span className="material-symbols-outlined text-on-surface-variant cursor-pointer">arrow_drop_down</span></div></div>
<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-md mb-xl">
<div className="bg-surface rounded-xl p-md border border-outline-variant shadow-sm flex flex-col justify-between"><div className="flex justify-between items-start mb-md"><div className="bg-surface-container p-xs rounded-lg"><span className="material-symbols-outlined text-primary-container">fact_check</span></div><span className="font-label-md text-label-md text-secondary flex items-center gap-xs bg-secondary-container/30 px-2 py-1 rounded-full"><span className="material-symbols-outlined text-[16px]">trending_up</span> +5.2%</span></div><div><h3 className="font-display-lg text-display-lg text-on-background mb-xs">1,248</h3><p className="font-body-md text-body-md text-on-surface-variant">Total Registered Pregnancies</p></div></div>
<div className="bg-surface rounded-xl p-md border border-error/30 shadow-sm flex flex-col justify-between risk-strip-high relative overflow-hidden"><div className="absolute -right-4 -top-4 w-24 h-24 bg-error-container/20 rounded-full blur-xl"></div><div className="flex justify-between items-start mb-md relative z-10"><div className="bg-error-container p-xs rounded-lg"><span className="material-symbols-outlined text-on-error-container" style={{ fontVariationSettings: '\'FILL\' 1' }}>warning</span></div><span className="font-label-md text-label-md text-error flex items-center gap-xs bg-error-container/50 px-2 py-1 rounded-full"><span className="material-symbols-outlined text-[16px]">trending_up</span> +2.1%</span></div><div className="relative z-10"><h3 className="font-display-lg text-display-lg text-error mb-xs">84</h3><p className="font-body-md text-body-md text-on-surface-variant">High-Risk Cases Currently Tracked</p></div></div>
<div className="bg-surface rounded-xl p-md border border-outline-variant shadow-sm flex flex-col justify-between"><div className="flex justify-between items-start mb-md"><div className="bg-surface-container p-xs rounded-lg"><span className="material-symbols-outlined text-tertiary-container">local_hospital</span></div><span className="font-label-md text-label-md text-secondary flex items-center gap-xs bg-secondary-container/30 px-2 py-1 rounded-full"><span className="material-symbols-outlined text-[16px]">trending_up</span> +8.4%</span></div><div><h3 className="font-display-lg text-display-lg text-on-background mb-xs">92%</h3><p className="font-body-md text-body-md text-on-surface-variant">Institutional Delivery Rate</p></div></div>
<div className="bg-surface rounded-xl p-md border border-outline-variant shadow-sm flex flex-col justify-between"><div className="flex justify-between items-start mb-md"><div className="bg-surface-container p-xs rounded-lg"><span className="material-symbols-outlined text-primary-container">medical_information</span></div><span className="font-label-md text-label-md text-on-surface-variant flex items-center gap-xs bg-surface-container-high px-2 py-1 rounded-full"><span className="material-symbols-outlined text-[16px]">horizontal_rule</span> 0.0%</span></div><div><h3 className="font-display-lg text-display-lg text-on-background mb-xs">76%</h3><p className="font-body-md text-body-md text-on-surface-variant">ANC-4 Coverage</p></div></div></div>
<div className="bento-grid mb-xl">
<div className="col-span-12 lg:col-span-8 flex flex-col gap-lg">
<div className="bento-card flex flex-col"><div className="flex justify-between items-center mb-lg"><div><h3 className="font-headline-md text-headline-md text-on-background">ANC Visit Compliance</h3><p className="font-body-md text-body-md text-on-surface-variant">Trimester breakdown by month</p></div><button className="p-xs text-on-surface-variant hover:bg-surface-container rounded-full transition-colors"><span className="material-symbols-outlined">more_vert</span></button></div>
<div className="flex-1 min-h-[240px] flex flex-col"><div className="flex justify-end gap-md mb-md"><div className="flex items-center gap-xs"><div className="w-3 h-3 rounded-sm bg-primary-container"></div><span className="font-caption text-caption text-on-surface-variant">ANC 1</span></div><div className="flex items-center gap-xs"><div className="w-3 h-3 rounded-sm bg-primary-fixed-dim"></div><span className="font-caption text-caption text-on-surface-variant">ANC 2+</span></div></div>
<div className="flex-1 flex border-l border-b border-outline-variant pb-xs pl-xs relative">
<div className="absolute left-[-32px] top-0 bottom-0 flex flex-col justify-between font-caption text-caption text-on-surface-variant h-full pb-6"><span>100%</span><span>75%</span><span>50%</span><span>25%</span></div>
<div className="absolute inset-0 flex flex-col justify-between ml-1 pb-6 w-full z-0 pointer-events-none"><div className="border-b border-dashed border-outline-variant w-full h-[1px]"></div><div className="border-b border-dashed border-outline-variant w-full h-[1px]"></div><div className="border-b border-dashed border-outline-variant w-full h-[1px]"></div><div className="border-b border-dashed border-outline-variant w-full h-[1px]"></div></div>
<div className="flex-1 flex justify-around items-end h-[calc(100%-24px)] z-10 pt-4">
<div className="flex flex-col items-center w-full h-full justify-end group"><div className="chart-bar-bg group-hover:bg-surface-container-highest transition-colors"><div className="chart-bar-fill-secondary" style={{ height: '85%' }}></div><div className="chart-bar-fill" style={{ height: '60%' }}></div></div><span className="font-caption text-caption text-on-surface-variant mt-sm">Jan</span></div>
<div className="flex flex-col items-center w-full h-full justify-end group"><div className="chart-bar-bg group-hover:bg-surface-container-highest transition-colors"><div className="chart-bar-fill-secondary" style={{ height: '90%' }}></div><div className="chart-bar-fill" style={{ height: '75%' }}></div></div><span className="font-caption text-caption text-on-surface-variant mt-sm">Feb</span></div>
<div className="flex flex-col items-center w-full h-full justify-end group"><div className="chart-bar-bg group-hover:bg-surface-container-highest transition-colors"><div className="chart-bar-fill-secondary" style={{ height: '80%' }}></div><div className="chart-bar-fill" style={{ height: '65%' }}></div></div><span className="font-caption text-caption text-on-surface-variant mt-sm">Mar</span></div>
<div className="flex flex-col items-center w-full h-full justify-end group"><div className="chart-bar-bg group-hover:bg-surface-container-highest transition-colors"><div className="chart-bar-fill-secondary" style={{ height: '88%' }}></div><div className="chart-bar-fill" style={{ height: '70%' }}></div></div><span className="font-caption text-caption text-on-surface-variant mt-sm">Apr</span></div>
<div className="flex flex-col items-center w-full h-full justify-end group"><div className="chart-bar-bg group-hover:bg-surface-container-highest transition-colors"><div className="chart-bar-fill-secondary" style={{ height: '92%' }}></div><div className="chart-bar-fill" style={{ height: '82%' }}></div></div><span className="font-caption text-caption text-on-surface-variant mt-sm">May</span></div></div></div></div></div>
<div className="bento-card"><div className="flex justify-between items-center mb-md pb-md border-b border-outline-variant"><div className="flex items-center gap-sm"><span className="material-symbols-outlined text-error" style={{ fontVariationSettings: '\'FILL\' 1' }}>emergency</span><h3 className="font-headline-md text-headline-md text-on-background">Critical Attention Required</h3></div><button className="font-label-md text-label-md text-primary hover:underline">View All (84)</button></div><div className="overflow-x-auto custom-scrollbar"><table className="w-full text-left border-collapse min-w-[600px]"><thead><tr className="bg-surface-container-low font-label-md text-label-md text-on-surface-variant"><th className="p-sm font-semibold rounded-tl-lg">Patient Name</th><th className="p-sm font-semibold">EDD</th><th className="p-sm font-semibold">Risk Factors</th><th className="p-sm font-semibold">ASHA Worker</th><th className="p-sm font-semibold text-right rounded-tr-lg">Action</th></tr></thead><tbody>
<tr className="border-b border-outline-variant hover:bg-surface-container-lowest transition-colors h-10"><td className="p-sm font-label-md text-label-md text-on-background flex items-center gap-sm"><div className="w-2 h-10 bg-error rounded-full ml-[-8px] absolute"></div><img className="w-6 h-6 rounded-full bg-surface-container-high object-cover" data-alt="A very small, low resolution placeholder avatar for a female patient profile. It shows a simple silhouette of a woman&#x27;s head and shoulders on a muted grey background." src="https://lh3.googleusercontent.com/aida-public/AB6AXuBTV7CYtA56LUJCP6GQoznFgNaXsYPXwS_FTBQOglRp4sW66Yn6IgyGjLR_VXie8hBL58aIE_S9ReztkMD_KQj7zuQfz76vFce_Kfse4-RIgBzgU1cfpyn33RGVhCVg9B7nBn2I4TP5T6SdW6NIkUKTgQE5yammz6CJQeBGu4lwSsb9S2rO7UbhU6hh7jydErsilOfS8cbG2K6khzfB3gT8DH7SouFow9SQ6pLRZ20PLanr_xsRCljUug" />
                                        Sita Devi
                                    </td><td className="p-sm font-body-md text-body-md text-on-background">12 Oct 2023</td><td className="p-sm"><span className="inline-block bg-error-container text-on-error-container font-caption text-caption px-2 py-0.5 rounded-full mr-xs mb-1 border border-error/20">Severe Anemia</span><span className="inline-block bg-surface-variant text-on-surface-variant font-caption text-caption px-2 py-0.5 rounded-full border border-outline-variant">G3P2</span></td><td className="p-sm font-body-md text-body-md text-on-surface-variant">Meena Kumari</td><td className="p-sm text-right"><button className="bg-[#D50000] text-on-error font-label-md text-label-md px-3 py-1 rounded-md shadow-sm hover:opacity-90 transition-opacity">Intervene</button></td></tr>
<tr className="border-b border-outline-variant hover:bg-surface-container-lowest transition-colors h-10"><td className="p-sm font-label-md text-label-md text-on-background flex items-center gap-sm"><div className="w-2 h-10 bg-error rounded-full ml-[-8px] absolute"></div><div className="w-6 h-6 rounded-full bg-tertiary-container flex items-center justify-center text-on-tertiary text-[10px] font-bold">R</div>
                                        Radha Sharma
                                    </td><td className="p-sm font-body-md text-body-md text-on-background">28 Oct 2023</td><td className="p-sm"><span className="inline-block bg-error-container text-on-error-container font-caption text-caption px-2 py-0.5 rounded-full mr-xs mb-1 border border-error/20">Hypertension (PIH)</span></td><td className="p-sm font-body-md text-body-md text-on-surface-variant">Suman Lata</td><td className="p-sm text-right"><button className="bg-[#D50000] text-on-error font-label-md text-label-md px-3 py-1 rounded-md shadow-sm hover:opacity-90 transition-opacity">Intervene</button></td></tr>
<tr className="hover:bg-surface-container-lowest transition-colors h-10"><td className="p-sm font-label-md text-label-md text-on-background flex items-center gap-sm"><div className="w-2 h-10 bg-error rounded-full ml-[-8px] absolute"></div><div className="w-6 h-6 rounded-full bg-primary-container flex items-center justify-center text-on-primary text-[10px] font-bold">P</div>
                                        Pooja Verma
                                    </td><td className="p-sm font-body-md text-body-md text-on-background">05 Nov 2023</td><td className="p-sm"><span className="inline-block bg-error-container text-on-error-container font-caption text-caption px-2 py-0.5 rounded-full mr-xs mb-1 border border-error/20">Previous C-Section</span><span className="inline-block bg-surface-variant text-on-surface-variant font-caption text-caption px-2 py-0.5 rounded-full border border-outline-variant">Age {'>'} 35</span></td><td className="p-sm font-body-md text-body-md text-on-surface-variant">Aarti Singh</td><td className="p-sm text-right"><button className="border border-primary text-primary font-label-md text-label-md px-3 py-1 rounded-md hover:bg-surface-container-highest transition-colors">Review</button></td></tr></tbody></table></div></div></div>
<div className="col-span-12 lg:col-span-4 flex flex-col gap-lg">
<div className="bento-card bg-surface-container-lowest border-primary/20 shadow-md"><h3 className="font-headline-md text-headline-md text-on-background mb-sm flex items-center gap-xs"><span className="material-symbols-outlined text-primary">child_care</span>
                        Expected Deliveries
                    </h3><p className="font-caption text-caption text-on-surface-variant mb-md">Next 30 Days Forecast</p><div className="flex items-center justify-center mb-lg relative h-40">
<div className="w-32 h-32 rounded-full border-8 border-surface-variant flex items-center justify-center relative">
<div className="absolute inset-0 rounded-full border-8 border-primary border-t-transparent border-r-transparent transform -rotate-45"></div><div className="absolute inset-0 rounded-full border-8 border-tertiary-container border-b-transparent border-l-transparent transform rotate-12"></div><div className="absolute inset-0 flex flex-col items-center justify-center bg-surface-container-lowest rounded-full m-2"><span className="font-display-lg text-display-lg text-on-background">142</span><span className="font-caption text-caption text-on-surface-variant">Total</span></div></div></div><div className="flex flex-col gap-xs"><div className="flex justify-between items-center p-sm bg-surface rounded-md border border-outline-variant"><div className="flex items-center gap-xs"><div className="w-3 h-3 rounded-full bg-primary"></div><span className="font-label-md text-label-md text-on-background">Normal Risk</span></div><span className="font-headline-md text-headline-md text-on-background">104</span></div><div className="flex justify-between items-center p-sm bg-error-container/20 rounded-md border border-error/30 risk-strip-high"><div className="flex items-center gap-xs"><div className="w-3 h-3 rounded-full bg-error"></div><span className="font-label-md text-label-md text-error">High Risk</span></div><span className="font-headline-md text-headline-md text-error">38</span></div></div></div>
<div className="bento-card"><div className="flex justify-between items-center mb-md"><h3 className="font-headline-md text-headline-md text-on-background">Village Breakdown</h3><span className="material-symbols-outlined text-on-surface-variant cursor-pointer">sort</span></div><div className="flex flex-col gap-sm">
<div className="flex flex-col gap-xs"><div className="flex justify-between font-label-md text-label-md"><span className="text-on-background">Rampur</span><span className="text-on-surface-variant">42 Pregnancies</span></div><div className="w-full bg-surface-variant h-2 rounded-full overflow-hidden flex"><div className="bg-primary h-full" style={{ width: '70%' }}></div><div className="bg-error h-full" style={{ width: '15%' }}></div></div></div>
<div className="flex flex-col gap-xs mt-sm"><div className="flex justify-between font-label-md text-label-md"><span className="text-on-background">Sitapur</span><span className="text-on-surface-variant">28 Pregnancies</span></div><div className="w-full bg-surface-variant h-2 rounded-full overflow-hidden flex"><div className="bg-primary h-full" style={{ width: '60%' }}></div><div className="bg-error h-full" style={{ width: '25%' }}></div></div></div>
<div className="flex flex-col gap-xs mt-sm"><div className="flex justify-between font-label-md text-label-md"><span className="text-on-background">Kishangarh</span><span className="text-on-surface-variant">35 Pregnancies</span></div><div className="w-full bg-surface-variant h-2 rounded-full overflow-hidden flex"><div className="bg-primary h-full" style={{ width: '80%' }}></div><div className="bg-error h-full" style={{ width: '5%' }}></div></div></div><button className="mt-md text-primary font-label-md text-label-md w-full text-center hover:bg-surface-container py-sm rounded-md transition-colors border border-outline-variant border-dashed">
                            View All 12 Villages
                        </button></div></div></div></div></main>
<nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-sm py-xs bg-surface border-t border-outline-variant shadow-lg docked full-width bottom-0 rounded-t-[0.75rem]">
<Link className="flex flex-col items-center justify-center bg-primary-container text-on-primary-container rounded-full px-4 py-1 scale-90 transition-transform duration-200" to="/phc/dashboard"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>home</span><span className="font-label-md text-label-md">Home</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant hover:bg-surface-container-highest rounded-lg px-2 py-1 transition-colors" to="/phc/households"><span className="material-symbols-outlined">cottage</span><span className="font-caption text-caption mt-1">Households</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant hover:bg-surface-container-highest rounded-lg px-2 py-1 transition-colors" to="/phc/beneficiaries"><span className="material-symbols-outlined">person_search</span><span className="font-caption text-caption mt-1">Patients</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant hover:bg-surface-container-highest rounded-lg px-2 py-1 transition-colors" to="/phc/alerts"><span className="material-symbols-outlined">assignment_turned_in</span><span className="font-caption text-caption mt-1">Tasks</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant hover:bg-surface-container-highest rounded-lg px-2 py-1 transition-colors" to="/phc/dashboard"><span className="material-symbols-outlined">account_circle</span><span className="font-caption text-caption mt-1">Profile</span></Link></nav>
    </>
  )
}
