import { Link } from 'react-router-dom'
import { LogoutButton } from '@/components/common/LogoutButton'
export default function PregnantWomenListPhcAdmin() {
  return (
    <>
<nav className="hidden md:flex flex-col h-screen w-64 left-0 top-0 border-r border-outline-variant p-md bg-surface-container-low flex-shrink-0"><div className="mb-xl flex items-center gap-sm"><div className="w-10 h-10 rounded-full bg-primary flex items-center justify-center text-on-primary"><span className="material-symbols-outlined">local_hospital</span></div><div><h1 className="font-headline-sm text-headline-sm font-bold text-on-surface">PHC Admin Portal</h1><p className="font-caption text-caption text-on-surface-variant">Regional Health Center</p></div></div><button className="mb-lg w-full bg-error text-on-error hover:bg-error/90 transition-colors py-sm px-md rounded-lg font-label-md text-label-md flex items-center justify-center gap-xs"><span className="material-symbols-outlined">emergency</span>
            Emergency Referral
        </button><ul className="flex flex-col gap-xs flex-grow"><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-variant transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/dashboard"><span className="material-symbols-outlined">dashboard</span>
                    Overview
                </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg bg-primary-container text-on-primary-container transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/maternal/pregnant"><span className="material-symbols-outlined" style={{ fontVariationSettings: '\'FILL\' 1' }}>groups</span>
                    Women Directory
                </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-variant transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/alerts/critical"><span className="material-symbols-outlined">error</span>
                    High Risk Cases
                </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-variant transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/referrals"><span className="material-symbols-outlined">moving</span>
                    Referrals
                </Link></li><li><Link className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-variant transition-all duration-200 ease-in-out font-label-md text-label-md" to="/phc/reports/maternal"><span className="material-symbols-outlined">assessment</span>
                    Reports
                </Link></li></ul><ul className="flex flex-col gap-xs mt-auto pt-lg border-t border-outline-variant"><li><a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-variant transition-all duration-200 ease-in-out font-label-md text-label-md" href="#"><span className="material-symbols-outlined">help</span>
                    Help Center
                </a></li><li><LogoutButton className="className='flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-variant transition-all duration-200 ease-in-out font-label-md text-label-md'"><span className="material-symbols-outlined">logout</span>
                    Logout
                </LogoutButton></li></ul></nav>
<main className="flex-1 flex flex-col h-full overflow-hidden">
<header className="flex justify-between items-center w-full px-lg py-sm bg-surface flex-shrink-0 relative z-10 border-b border-surface-container-low shadow-sm"><div className="flex items-center gap-md md:hidden"><button className="p-sm text-on-surface-variant hover:text-primary transition-colors cursor-pointer active:opacity-80"><span className="material-symbols-outlined">menu</span></button><span className="font-headline-md text-headline-md font-bold text-primary">MaternalCare PHC</span></div><div className="hidden md:flex gap-md ml-auto"><div className="relative flex items-center"><span className="material-symbols-outlined absolute left-3 text-on-surface-variant">search</span><input className="pl-10 pr-4 py-2 bg-surface-container-low border border-outline-variant rounded-full text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary w-64 transition-all" placeholder="Search patients, ID..." type="text" /></div><button className="bg-primary text-on-primary hover:bg-primary/90 px-md py-2 rounded-full font-label-md text-label-md transition-colors flex items-center gap-xs"><span className="material-symbols-outlined">add</span>
                    New Registration
                </button></div><div className="flex items-center gap-sm ml-4"><button className="p-sm text-on-surface-variant hover:text-primary transition-colors cursor-pointer active:opacity-80"><span className="material-symbols-outlined">sync</span></button><button className="p-sm text-on-surface-variant hover:text-primary transition-colors cursor-pointer active:opacity-80 relative"><span className="material-symbols-outlined">notifications</span><span className="absolute top-1 right-1 w-2 h-2 bg-error rounded-full"></span></button><button className="p-sm text-on-surface-variant hover:text-primary transition-colors cursor-pointer active:opacity-80"><span className="material-symbols-outlined">settings</span></button><img alt="Administrator Profile" className="w-10 h-10 rounded-full ml-sm object-cover border border-outline-variant" data-alt="Professional headshot of a healthcare administrator, soft indoor lighting, modern clinical setting background, clear and reassuring expression" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCS-mRIV4cyhIILhzDpO8ym9hWksKj2CE1lKHC7EpAirRmovXdL1R-rPxRf5Uh47E5IyCeYNeTOJ9u0V_mlRMbuX8ReUtAIuiluFQe8EemTMY_6PlPJShIJjZAAfKULQPO_EvuL7gFRTj7R5wZX3vKP0ZMnnyZ2g-NaPcPuIHqxdx5QL5ze-_vjYkOXqs-JD08Qga68cO7rYNXjVPO6WeFjfDSGkXaC2_a_NdnIdljU_72GQAiWaubjRw" /></div></header>
<div className="flex-1 overflow-y-auto p-4 md:p-lg bg-surface-container-lowest"><div className="max-w-[1440px] mx-auto space-y-lg">
<div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><h2 className="font-display-lg text-display-lg text-on-surface mb-1">Pregnant Women Directory</h2><p className="font-body-md text-body-md text-on-surface-variant">Manage and monitor maternal health records.</p></div></div>
<div className="grid grid-cols-2 md:grid-cols-4 gap-4"><div className="bg-surface p-md rounded-xl border border-surface-container-high flex flex-col justify-between h-32 relative overflow-hidden group hover:border-primary-container transition-colors"><div className="absolute -right-4 -top-4 w-24 h-24 bg-primary-container/10 rounded-full group-hover:scale-110 transition-transform"></div><p className="font-label-md text-label-md text-on-surface-variant z-10">Total Pregnancies</p><div className="flex items-baseline gap-2 z-10"><h3 className="font-display-lg text-display-lg text-on-surface">1,248</h3><span className="font-caption text-caption text-secondary flex items-center"><span className="material-symbols-outlined text-[16px]">arrow_upward</span> 12%</span></div></div><div className="bg-surface p-md rounded-xl border border-error-container flex flex-col justify-between h-32 relative overflow-hidden group hover:border-error transition-colors"><div className="absolute -right-4 -top-4 w-24 h-24 bg-error-container/20 rounded-full group-hover:scale-110 transition-transform"></div><p className="font-label-md text-label-md text-on-error-container z-10">High-Risk Cases</p><div className="flex items-baseline gap-2 z-10"><h3 className="font-display-lg text-display-lg text-error">42</h3></div></div><div className="bg-surface p-md rounded-xl border border-surface-container-high flex flex-col justify-between h-32 relative overflow-hidden group hover:border-tertiary-container transition-colors"><div className="absolute -right-4 -top-4 w-24 h-24 bg-tertiary-container/10 rounded-full group-hover:scale-110 transition-transform"></div><p className="font-label-md text-label-md text-on-surface-variant z-10">Due this Month</p><div className="flex items-baseline gap-2 z-10"><h3 className="font-display-lg text-display-lg text-on-surface">86</h3></div></div><div className="bg-surface p-md rounded-xl border border-surface-container-high flex flex-col justify-between h-32 relative overflow-hidden group hover:border-secondary-container transition-colors"><div className="absolute -right-4 -top-4 w-24 h-24 bg-secondary-container/20 rounded-full group-hover:scale-110 transition-transform"></div><p className="font-label-md text-label-md text-on-surface-variant z-10">Completed ANC-4</p><div className="flex items-baseline gap-2 z-10"><h3 className="font-display-lg text-display-lg text-on-surface">315</h3><span className="font-caption text-caption text-on-surface-variant">YTD</span></div></div></div>
<div className="flex flex-col md:flex-row gap-4 items-center justify-between bg-surface-container-low p-sm rounded-xl border border-surface-container"><div className="flex flex-wrap gap-2 w-full md:w-auto"><select className="bg-surface border border-outline-variant text-on-surface text-body-md rounded-lg focus:ring-primary focus:border-primary block p-2 min-h-[48px] md:min-h-[40px]"><option selected>All Villages</option><option value="v1">Rampur</option><option value="v2">Sitapur</option></select><select className="bg-surface border border-outline-variant text-on-surface text-body-md rounded-lg focus:ring-primary focus:border-primary block p-2 min-h-[48px] md:min-h-[40px]"><option selected>Risk Level</option><option value="high">High Risk</option><option value="medium">Medium Risk</option><option value="normal">Normal</option></select><select className="bg-surface border border-outline-variant text-on-surface text-body-md rounded-lg focus:ring-primary focus:border-primary block p-2 min-h-[48px] md:min-h-[40px]"><option selected>Trimester</option><option value="1">First</option><option value="2">Second</option><option value="3">Third</option></select></div><div className="flex gap-2 w-full md:w-auto"><button className="bg-surface-variant text-on-surface flex-1 md:flex-none hover:bg-surface-container-highest px-md py-2 rounded-lg font-label-md text-label-md transition-colors min-h-[48px] md:min-h-[40px] flex items-center justify-center gap-xs"><span className="material-symbols-outlined">filter_list</span>
                            More Filters
                        </button></div></div>
<div className="bg-surface border border-outline-variant rounded-xl overflow-hidden shadow-[0_2px_4px_rgba(0,0,0,0.05)]"><div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="bg-surface-container-low border-b border-outline-variant text-on-surface-variant font-label-md text-label-md"><th className="p-md font-semibold whitespace-nowrap">Patient Name / ID</th><th className="p-md font-semibold whitespace-nowrap">EDD</th><th className="p-md font-semibold whitespace-nowrap">Timeline</th><th className="p-md font-semibold whitespace-nowrap">Last ANC</th><th className="p-md font-semibold whitespace-nowrap">Risk Status</th><th className="p-md font-semibold whitespace-nowrap">ASHA Worker</th><th className="p-md font-semibold text-right">Actions</th></tr></thead><tbody className="text-body-md text-on-surface divide-y divide-surface-container">
<tr className="hover:bg-surface-container-lowest transition-colors relative"><td className="p-md"><div className="absolute left-0 top-0 bottom-0 w-1 bg-error"></div><div className="font-semibold">Sunita Devi</div><div className="text-caption text-on-surface-variant">PW-2023-0891</div></td><td className="p-md">15 Nov 2023</td><td className="p-md"><div>Week 32</div><div className="text-caption text-on-surface-variant">3rd Trimester</div></td><td className="p-md">12 Oct 2023</td><td className="p-md"><span className="inline-flex items-center gap-1 bg-error-container text-on-error-container px-2 py-1 rounded-full font-caption text-caption"><span className="w-2 h-2 rounded-full bg-error"></span> High
                                        </span></td><td className="p-md">Meena Kumari</td><td className="p-md text-right space-x-2 whitespace-nowrap"><button className="text-primary hover:text-primary-container font-label-md text-label-md px-2 py-1 min-h-[48px] md:min-h-[32px]">Details</button><button className="bg-primary text-on-primary hover:bg-primary/90 px-3 py-1 rounded-lg font-label-md text-label-md min-h-[48px] md:min-h-[32px]">Log Visit</button></td></tr>
<tr className="hover:bg-surface-container-lowest transition-colors relative bg-surface-bright"><td className="p-md"><div className="absolute left-0 top-0 bottom-0 w-1 bg-secondary"></div><div className="font-semibold">Aarti Sharma</div><div className="text-caption text-on-surface-variant">PW-2023-1022</div></td><td className="p-md">02 Feb 2024</td><td className="p-md"><div>Week 20</div><div className="text-caption text-on-surface-variant">2nd Trimester</div></td><td className="p-md">05 Oct 2023</td><td className="p-md"><span className="inline-flex items-center gap-1 bg-secondary-container text-on-secondary-container px-2 py-1 rounded-full font-caption text-caption"><span className="w-2 h-2 rounded-full bg-secondary"></span> Normal
                                        </span></td><td className="p-md">Rekha Patel</td><td className="p-md text-right space-x-2 whitespace-nowrap"><button className="text-primary hover:text-primary-container font-label-md text-label-md px-2 py-1 min-h-[48px] md:min-h-[32px]">Details</button><button className="border border-primary text-primary hover:bg-primary-container/10 px-3 py-1 rounded-lg font-label-md text-label-md min-h-[48px] md:min-h-[32px]">Log Visit</button></td></tr>
<tr className="hover:bg-surface-container-lowest transition-colors relative"><td className="p-md"><div className="absolute left-0 top-0 bottom-0 w-1 bg-[#F57C00]"></div>
<div className="font-semibold">Kamla Yadav</div><div className="text-caption text-on-surface-variant">PW-2023-1145</div></td><td className="p-md">28 Dec 2023</td><td className="p-md"><div>Week 26</div><div className="text-caption text-on-surface-variant">2nd Trimester</div></td><td className="p-md">20 Sep 2023</td><td className="p-md"><span className="inline-flex items-center gap-1 bg-[#FFF3E0] text-[#E65100] px-2 py-1 rounded-full font-caption text-caption"><span className="w-2 h-2 rounded-full bg-[#F57C00]"></span> Medium
                                        </span></td><td className="p-md">Sita Verma</td><td className="p-md text-right space-x-2 whitespace-nowrap"><button className="text-primary hover:text-primary-container font-label-md text-label-md px-2 py-1 min-h-[48px] md:min-h-[32px]">Details</button><button className="border border-primary text-primary hover:bg-primary-container/10 px-3 py-1 rounded-lg font-label-md text-label-md min-h-[48px] md:min-h-[32px]">Log Visit</button></td></tr></tbody></table></div>
<div className="p-sm border-t border-outline-variant bg-surface-container-low flex justify-between items-center text-body-md text-on-surface-variant"><span>Showing 1-10 of 1,248</span><div className="flex gap-2"><button className="p-1 rounded hover:bg-surface-variant disabled:opacity-50"><span className="material-symbols-outlined">chevron_left</span></button><button className="p-1 rounded hover:bg-surface-variant"><span className="material-symbols-outlined">chevron_right</span></button></div></div></div></div></div></main>
    </>
  )
}
