import { Link } from 'react-router-dom'
export default function VaccinationManagementPhcAdmin() {
  return (
    <>
<nav className="hidden md:flex flex-col h-screen fixed left-0 top-0 p-md gap-sm bg-surface-container-low border-r border-outline-variant docked left-0 h-full w-64 z-50"><div className="flex items-center gap-sm mb-lg px-sm"><span className="material-symbols-outlined fill text-primary text-[32px]">admin_panel_settings</span><div><h1 className="font-headline-md text-headline-md font-black text-primary">Admin Portal</h1><p className="font-caption text-caption text-on-surface-variant">District Health Office</p></div></div><button className="bg-primary-container text-on-primary-container font-label-md text-label-md rounded-lg py-sm px-md flex items-center justify-center gap-sm mb-md hover:bg-surface-container-highest transition-all min-h-[48px]"><span className="material-symbols-outlined">add</span>
            Add New Worker
        </button><div className="flex flex-col gap-xs flex-grow">

<Link className="text-on-surface-variant hover:bg-surface-container-high font-label-md text-label-md rounded-lg py-sm px-md flex items-center gap-md transition-all min-h-[48px]" to="/phc/dashboard"><span className="material-symbols-outlined">dashboard</span>
                Dashboard
            </Link><Link className="text-on-surface-variant hover:bg-surface-container-high font-label-md text-label-md rounded-lg py-sm px-md flex items-center gap-md transition-all min-h-[48px]" to="/phc/ashas"><span className="material-symbols-outlined">groups</span>
                Workers
            </Link>
<Link className="bg-secondary-container text-on-secondary-container font-bold rounded-lg py-sm px-md flex items-center gap-md scale-95 transition-transform duration-150 min-h-[48px]" to="/phc/beneficiaries"><span className="material-symbols-outlined fill">person_celebrate</span>
                Beneficiaries
            </Link><Link className="text-on-surface-variant hover:bg-surface-container-high font-label-md text-label-md rounded-lg py-sm px-md flex items-center gap-md transition-all min-h-[48px]" to="/phc/reports/maternal"><span className="material-symbols-outlined">analytics</span>
                Reports
            </Link><Link className="text-on-surface-variant hover:bg-surface-container-high font-label-md text-label-md rounded-lg py-sm px-md flex items-center gap-md transition-all min-h-[48px]" to="/phc/vaccination"><span className="material-symbols-outlined">inventory_2</span>
                Inventory
            </Link></div><div className="flex flex-col gap-xs mt-auto pt-md border-t border-outline-variant"><a className="text-on-surface-variant hover:bg-surface-container-high font-label-md text-label-md rounded-lg py-sm px-md flex items-center gap-md transition-all min-h-[48px]" href="#"><span className="material-symbols-outlined">settings</span>
                Settings
            </a><a className="text-on-surface-variant hover:bg-surface-container-high font-label-md text-label-md rounded-lg py-sm px-md flex items-center gap-md transition-all min-h-[48px]" href="#"><span className="material-symbols-outlined">help</span>
                Support
            </a></div></nav>
<main className="flex-1 md:ml-64 p-md md:p-lg lg:p-xl overflow-y-auto">
<header className="flex flex-col md:flex-row justify-between items-start md:items-center mb-xl gap-md"><div><h2 className="font-display-lg text-display-lg text-on-background">Vaccination Management</h2><p className="font-body-lg text-body-lg text-on-surface-variant">Overview of immunization programs across PHC jurisdiction.</p></div><div className="flex gap-sm"><button className="border border-primary text-primary font-label-md text-label-md rounded-lg px-md py-sm hover:bg-surface-container transition-colors min-h-[48px] flex items-center gap-sm"><span className="material-symbols-outlined">download</span>
                    Export Due List
                </button><button className="bg-primary text-on-primary font-label-md text-label-md rounded-lg px-md py-sm hover:opacity-90 transition-opacity min-h-[48px] flex items-center gap-sm shadow-sm"><span className="material-symbols-outlined">notifications_active</span>
                    Send Reminders to ASHA
                </button></div></header>
<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-md mb-xl">
<div className="bg-surface border border-outline-variant rounded-xl p-md shadow-sm"><div className="flex items-center justify-between mb-sm"><span className="font-label-md text-label-md text-on-surface-variant">Total Target (0-5 Yrs)</span><span className="material-symbols-outlined text-primary">child_care</span></div><div className="font-display-lg text-display-lg">4,250</div><div className="font-caption text-caption text-on-surface-variant mt-xs">+12% from last year</div></div>
<div className="bg-surface border border-outline-variant rounded-xl p-md shadow-sm"><div className="flex items-center justify-between mb-sm"><span className="font-label-md text-label-md text-on-surface-variant">Fully Immunized</span><span className="material-symbols-outlined text-secondary">verified</span></div><div className="font-display-lg text-display-lg">3,100</div><div className="flex items-center gap-xs mt-xs"><div className="w-full bg-surface-container-high rounded-full h-1.5"><div className="bg-secondary h-1.5 rounded-full" style={{ width: '73%' }}></div></div><span className="font-caption text-caption text-secondary">73%</span></div></div>
<div className="bg-surface border border-outline-variant rounded-xl p-md shadow-sm"><div className="flex items-center justify-between mb-sm"><span className="font-label-md text-label-md text-on-surface-variant">Overdue Doses</span><span className="material-symbols-outlined text-error">warning</span></div><div className="font-display-lg text-display-lg">450</div><div className="font-caption text-caption text-error mt-xs">Requires immediate attention</div></div>
<div className="bg-surface border border-outline-variant rounded-xl p-md shadow-sm"><div className="flex items-center justify-between mb-sm"><span className="font-label-md text-label-md text-on-surface-variant">Low Stock Alerts</span><span className="material-symbols-outlined text-tertiary">inventory</span></div><div className="font-display-lg text-display-lg">2</div><div className="font-caption text-caption text-on-surface-variant mt-xs">Polio, BCG below threshold</div></div></div>
<div className="grid grid-cols-1 lg:grid-cols-3 gap-lg">
<div className="lg:col-span-2 bg-surface border border-outline-variant rounded-xl shadow-sm overflow-hidden flex flex-col"><div className="p-md border-b border-outline-variant flex justify-between items-center bg-surface-container-lowest"><h3 className="font-headline-md text-headline-md">Due & Overdue List</h3><div className="flex gap-sm"><select className="bg-surface border border-outline-variant text-on-surface font-label-md text-label-md rounded-lg px-sm py-xs min-h-[36px]"><option>All Villages</option><option>Rampur</option><option>Shitla</option></select><select className="bg-surface border border-outline-variant text-on-surface font-label-md text-label-md rounded-lg px-sm py-xs min-h-[36px]"><option>All Vaccines</option><option>BCG</option><option>Polio</option></select></div></div><div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="bg-surface-container-low font-label-md text-label-md text-on-surface-variant border-b border-outline-variant"><th className="p-sm px-md font-semibold">Child Name</th><th className="p-sm font-semibold">Village / ASHA</th><th className="p-sm font-semibold">Due Vaccine</th><th className="p-sm font-semibold">Due Date</th><th className="p-sm font-semibold">Status</th><th className="p-sm px-md font-semibold text-right">Action</th></tr></thead><tbody className="font-body-md text-body-md">
<tr className="border-b border-outline-variant hover:bg-surface-container-lowest transition-colors group"><td className="p-sm px-md relative"><div className="absolute left-0 top-0 bottom-0 w-1 bg-error"></div><div className="font-semibold">Aarav Kumar</div><div className="font-caption text-caption text-on-surface-variant">ID: VC-8921</div></td><td className="p-sm"><div>Rampur</div><div className="font-caption text-caption text-on-surface-variant">Sita Devi</div></td><td className="p-sm">DPT-1</td><td className="p-sm">12 Oct 2023</td><td className="p-sm"><span className="bg-error-container text-on-error-container font-caption text-caption px-2 py-1 rounded-full whitespace-nowrap">Overdue by 14 days</span></td><td className="p-sm px-md text-right"><button className="text-primary hover:bg-primary-container p-sm rounded-full transition-colors"><span className="material-symbols-outlined text-[20px]">notifications</span></button></td></tr>
<tr className="border-b border-outline-variant hover:bg-surface-container-lowest transition-colors"><td className="p-sm px-md relative"><div className="absolute left-0 top-0 bottom-0 w-1 bg-tertiary"></div><div className="font-semibold">Priya Sharma</div><div className="font-caption text-caption text-on-surface-variant">ID: VC-8933</div></td><td className="p-sm"><div>Shitla</div><div className="font-caption text-caption text-on-surface-variant">Geeta</div></td><td className="p-sm">OPV-2</td><td className="p-sm">26 Oct 2023</td><td className="p-sm"><span className="bg-surface-container-highest text-on-surface font-caption text-caption px-2 py-1 rounded-full whitespace-nowrap">Due Today</span></td><td className="p-sm px-md text-right"><button className="text-primary hover:bg-primary-container p-sm rounded-full transition-colors"><span className="material-symbols-outlined text-[20px]">notifications</span></button></td></tr>
<tr className="border-b border-outline-variant hover:bg-surface-container-lowest transition-colors"><td className="p-sm px-md relative"><div className="absolute left-0 top-0 bottom-0 w-1 bg-outline-variant"></div><div className="font-semibold">Rohan Singh</div><div className="font-caption text-caption text-on-surface-variant">ID: VC-8945</div></td><td className="p-sm"><div>Kheri</div><div className="font-caption text-caption text-on-surface-variant">Sunita</div></td><td className="p-sm">Measles</td><td className="p-sm">05 Nov 2023</td><td className="p-sm"><span className="bg-surface-container text-on-surface font-caption text-caption px-2 py-1 rounded-full whitespace-nowrap">Upcoming</span></td><td className="p-sm px-md text-right"><button className="text-on-surface-variant hover:bg-surface-container p-sm rounded-full transition-colors"><span className="material-symbols-outlined text-[20px]">more_vert</span></button></td></tr></tbody></table></div><div className="p-sm border-t border-outline-variant flex justify-center bg-surface-container-lowest mt-auto"><button className="text-primary font-label-md text-label-md hover:underline">View All Records</button></div></div>
<div className="bg-surface border border-outline-variant rounded-xl shadow-sm p-md flex flex-col"><div className="flex justify-between items-center mb-md border-b border-outline-variant pb-sm"><h3 className="font-headline-md text-headline-md">Inventory Status</h3><button className="text-primary hover:bg-surface-container p-1 rounded"><span className="material-symbols-outlined">sync</span></button></div><div className="flex flex-col gap-md flex-grow">
<div><div className="flex justify-between font-label-md text-label-md mb-xs"><span>BCG</span><span className="text-error">150 Vials (Low)</span></div><div className="w-full bg-surface-container-high rounded-full h-2"><div className="bg-error h-2 rounded-full" style={{ width: '15%' }}></div></div></div>
<div><div className="flex justify-between font-label-md text-label-md mb-xs"><span>OPV</span><span className="text-secondary">850 Vials</span></div><div className="w-full bg-surface-container-high rounded-full h-2"><div className="bg-secondary h-2 rounded-full" style={{ width: '75%' }}></div></div></div>
<div><div className="flex justify-between font-label-md text-label-md mb-xs"><span>DPT</span><span className="text-tertiary">420 Vials</span></div><div className="w-full bg-surface-container-high rounded-full h-2"><div className="bg-tertiary h-2 rounded-full" style={{ width: '45%' }}></div></div></div>
<div><div className="flex justify-between font-label-md text-label-md mb-xs"><span>Measles</span><span className="text-error">80 Vials (Critial)</span></div><div className="w-full bg-surface-container-high rounded-full h-2"><div className="bg-error h-2 rounded-full" style={{ width: '8%' }}></div></div></div></div><button className="mt-md w-full border border-primary text-primary font-label-md text-label-md rounded-lg py-sm hover:bg-primary-container transition-colors min-h-[48px]">
                    Request Indent
                </button></div></div>
<div className="grid grid-cols-1 lg:grid-cols-2 gap-lg mt-lg">
<div className="bg-surface border border-outline-variant rounded-xl shadow-sm p-md"><h3 className="font-headline-md text-headline-md mb-md border-b border-outline-variant pb-sm">Vaccination Trend (Monthly)</h3>
<div className="h-64 bg-surface-container-lowest rounded flex items-center justify-center relative overflow-hidden border border-outline-variant border-dashed"><span className="text-on-surface-variant font-label-md text-label-md z-10 bg-surface px-2 py-1 rounded">Chart: Doses Administered vs Target</span>
<div className="absolute bottom-0 left-0 w-full h-full flex items-end px-md gap-sm opacity-20"><div className="w-1/6 bg-primary h-1/3 rounded-t"></div><div className="w-1/6 bg-primary h-1/2 rounded-t"></div><div className="w-1/6 bg-primary h-2/3 rounded-t"></div><div className="w-1/6 bg-primary h-1/2 rounded-t"></div><div className="w-1/6 bg-primary h-3/4 rounded-t"></div><div className="w-1/6 bg-primary h-full rounded-t"></div></div></div></div>
<div className="bg-surface border border-outline-variant rounded-xl shadow-sm p-md"><h3 className="font-headline-md text-headline-md mb-md border-b border-outline-variant pb-sm">Coverage by Village</h3>
<div className="h-64 bg-surface-container-lowest rounded flex items-center justify-center relative overflow-hidden border border-outline-variant border-dashed"><span className="text-on-surface-variant font-label-md text-label-md z-10 bg-surface px-2 py-1 rounded">Chart: % Fully Immunized by Village</span>
<div className="absolute top-0 left-0 w-full h-full flex flex-col justify-center px-md gap-md opacity-20"><div className="w-3/4 bg-secondary h-4 rounded-r"></div><div className="w-1/2 bg-tertiary h-4 rounded-r"></div><div className="w-5/6 bg-secondary h-4 rounded-r"></div><div className="w-1/3 bg-error h-4 rounded-r"></div></div></div></div></div></main>
<nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-sm py-xs bg-surface border-t border-outline-variant rounded-t-full shadow-lg h-[80px]"><Link className="flex flex-col items-center justify-center text-on-surface-variant w-[64px] h-[64px]" to="/phc/dashboard"><span className="material-symbols-outlined">home</span><span className="font-label-md text-label-md text-[10px]">Home</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant w-[64px] h-[64px]" to="/phc/households"><span className="material-symbols-outlined">cottage</span><span className="font-label-md text-label-md text-[10px]">Households</span></Link>
<Link className="flex flex-col items-center justify-center bg-primary-container text-on-primary-container rounded-full px-4 py-1 scale-90 transition-transform duration-200" to="/phc/beneficiaries"><span className="material-symbols-outlined fill">person_search</span><span className="font-label-md text-label-md text-[10px]">Patients</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant w-[64px] h-[64px]" to="/phc/alerts"><span className="material-symbols-outlined">assignment_turned_in</span><span className="font-label-md text-label-md text-[10px]">Tasks</span></Link><Link className="flex flex-col items-center justify-center text-on-surface-variant w-[64px] h-[64px]" to="/phc/dashboard"><span className="material-symbols-outlined">account_circle</span><span className="font-label-md text-label-md text-[10px]">Profile</span></Link></nav>
    </>
  )
}
